dxos/dxos

packages/core/mesh/messaging/src/signal-manager/memory-signal-manager.ts, packages/core/mesh/messaging/src/signal-manager/websocket-signal-manager.ts, packages/core/mesh/network-manager/src/network-manager.ts, packages/core/mesh/network-manager/src/swarm/swarm.ts, packages/core/mesh/network-manager/src/testing/test-builder.ts, packages/core/mesh/network-manager/src/tests/basic-test-suite.ts, packages/sdk/client-services/src/packlets/services/service-context.ts
TODOs: https://github.com/dxos/dxos/issues/2140
=> feat(network-manager): Add "Airplane mode"

packages/core/mesh/network-manager/src/network-manager.ts, packages/core/mesh/network-manager/src/testing/test-builder.ts, packages/core/protocols/src/proto/dxos/client/services.proto, packages/sdk/client-services/src/packlets/network/index.ts, packages/sdk/client-services/src/packlets/network/network-service.ts, packages/sdk/client-services/src/packlets/services/service-definitions.ts, packages/sdk/client-services/src/packlets/services/service-host.ts, packages/sdk/client-services/src/packlets/vault/worker-session.ts
TODOs: https://github.com/dxos/dxos/issues/2140
=> feat(client-services): Add NetworkService

packages/core/protocols/src/proto/dxos/devtools/host.proto, packages/devtools/devtools-extension/package.json, packages/devtools/devtools-extension/src/devtools.ts, packages/devtools/devtools-extension/src/panel.ts, packages/devtools/devtools-extension/src/sandbox.ts, packages/devtools/devtools-extension/tsconfig.json, packages/devtools/devtools/src/App.tsx, packages/devtools/devtools/src/containers/ConfigPanel/ConfigPanel.tsx, packages/devtools/devtools/src/containers/ItemsPanel/ItemsPanel.tsx, packages/devtools/devtools/src/index.ts, packages/devtools/devtools/src/initialize.tsx, packages/sdk/client-services/src/packlets/devtools/spaces.ts, packages/sdk/client/src/packlets/devtools/devtools.ts, pnpm-lock.yaml
https://user-images.githubusercontent.com/36420699/210776461-6e55b24b-4c40-4217-a4c7-b79054fe1ecd.mov
=> fix(devtools-extension): Make Devtools Extension work

packages/common/react-components/src/components/QrCode/QrCode.tsx
This PR fixes QR codes on mobile by rendering them as a popover rather than a tooltip.
=> fix: QR codes

packages/apps/patterns/react-ui/src/layouts/PanelSidebar/PanelSidebar.tsx, packages/common/react-components/src/components/Dialog/dialogStyles.ts, packages/experimental/kai/src/app/AppBar.tsx, packages/experimental/kai/src/app/Frames.tsx, packages/experimental/kai/src/app/Sidebar.tsx
https://user-images.githubusercontent.com/855039/212782420-6061f27b-6b1e-478c-aa46-053afec47adb.mp4
=> fix: Sidebar layout & motion

packages/apps/patterns/react-ui/src/layouts/PanelSidebar/PanelSidebar.tsx, packages/experimental/kai/src/app/Sidebar.tsx
Evaluate Sidebar on mount. Avoid toggling sidebar.
https://user-images.githubusercontent.com/855039/213009478-08b17df6-a907-4cf5-8925-b6a503449d4e.mp4
=> fix: Sidebar state

packages/core/echo/echo-schema/src/defs.ts
https://discord.com/channels/837138313172353095/837688740805476394/1065656190018789386
=> fix(echo-schema): Fix Symbols

packages/devtools/devtools-extension/package.json, packages/devtools/devtools-extension/project.json, packages/devtools/devtools-extension/scripts/build.js, pnpm-lock.yaml
Will turn it back on as I will finish fixing it
=> fix(devtools-extension): Skip bundle

packages/apps/tasks-app/package.json, packages/apps/tasks-app/tsconfig.json, packages/apps/templates/bare-template/package.json, packages/apps/templates/bare-template/src/config.t.ts, packages/apps/templates/bare-template/src/dx.yml.t.ts, packages/apps/templates/bare-template/src/package.json.t.ts, packages/apps/templates/bare-template/src/src/App.tsx.t.ts, packages/apps/templates/bare-template/src/utils.t/packageJson.ts, packages/apps/templates/bare-template/src/vite.config.ts.t.ts, packages/apps/templates/bare-template/tsconfig.json, packages/apps/templates/hello-template/package.json, packages/apps/templates/tasks-template/package.json, packages/common/plate/src/config.ts, packages/common/plate/src/executeDirectoryTemplate.ts, packages/common/plate/src/main.ts, packages/devtools/cli/src/commands/app/create.ts, pnpm-lock.yaml
=> feat: dx app cli and app template improvements

packages/sdk/client/src/packlets/client/client.ts, packages/sdk/client/src/packlets/tests/client.test.ts
https://github.com/dxos/dxos/issues/2406
=> feat: Add friendly error when accessing ECHO without identity

packages/sdk/client/src/packlets/client/client.ts, packages/sdk/client/src/packlets/tests/client.test.ts
=> Revert "feat: Add friendly error when accessing ECHO without identity"

packages/sdk/client-services/src/packlets/deprecated/space.ts, packages/sdk/client/src/packlets/tests/client.test.ts
https://github.com/dxos/dxos/issues/2406
=> feat: Add friendly error on Space creation without Identity

packages/apps/patterns/react-ui/src/components/InvitationList/InvitationList.stories.tsx, packages/apps/patterns/react-ui/src/components/InvitationList/InvitationStatusAvatar.stories.tsx, packages/apps/patterns/react-ui/src/components/InvitationList/InvitationStatusAvatar.tsx, packages/apps/patterns/react-ui/src/panels/JoinPanel/view-states/ViewState.tsx, packages/apps/patterns/react-ui/src/styles/index.ts, packages/apps/patterns/react-ui/src/styles/invitationStatusStyles.ts
=> feat: List item invitation status avatars

packages/common/react-components/src/components/List/List.tsx
Solution was terribly simple: https://docs.dndkit.com/api-documentation/draggable#touch-action
=> fix: Draggable behavior on touch devices

packages/core/echo/echo-schema/src/database-router.ts, packages/core/echo/echo-schema/src/react-integration.ts
=> feat: Add warning when withReactor is missing

packages/apps/patterns/react-appkit/src/components/FatalError/FatalError.tsx, packages/apps/patterns/react-appkit/src/components/SpacesPage/SpacesPage.tsx, packages/apps/patterns/react-appkit/src/components/SpacesPage/SpacesPageComponent.tsx, packages/apps/patterns/react-ui/src/layouts/PanelDialog/PanelDialog.tsx, packages/common/react-components/src/components/Alert/Alert.tsx, packages/common/react-components/src/components/Dialog/Dialog.tsx, packages/common/react-components/src/components/Input/BareTextInput.tsx, packages/common/react-components/src/components/Input/BareTextareaInput.tsx, packages/common/react-components/src/components/Input/Input.tsx, packages/experimental/kai/src/containers/AppBar/AppBar.tsx, packages/experimental/kai/src/containers/SpaceSettingsDialog/SpaceSettingsDialog.tsx
Based on a number of items from #2492.
=> fix: Component issues from kai

docs/docs/README.md, docs/docs/guide/getting-started.md, docs/docs/guide/platform/kube.md, packages/apps/templates/bare-template/src/README.md.t.ts, packages/apps/templates/bare-template/src/package.json.t.ts, packages/apps/templates/hello-template/src/src/Welcome.tsx.t.ts, packages/common/plate/src/executeDirectoryTemplate.ts
=> fix: broken links and peer deps in bare template

packages/experimental/kai/src/frames/Stack/StackFrame.tsx, packages/experimental/kai/src/hooks/useFrames.tsx
https://user-images.githubusercontent.com/3523355/222037011-c1316d24-bd17-4fb7-827d-ac905552fe01.mov
=> feat: Document stacks.

packages/common/random-access-storage/src/browser/firefox-storage.ts
=> fix(random-access-storage): works in create-react-app

packages/apps/composer-app/package.json, packages/apps/composer-app/src/pages/DocumentPage.tsx, packages/apps/composer-app/src/translations/en-US.ts, packages/apps/patterns/react-appkit/src/hooks/index.ts, packages/apps/patterns/react-appkit/src/hooks/useFileDownload.ts, packages/apps/patterns/react-composer/src/components/Composer/Composer.stories.tsx, packages/apps/patterns/react-composer/src/components/Composer/Composer.tsx, pnpm-lock.yaml
This PR enables export to and import from Markdown.
https://user-images.githubusercontent.com/855039/222934941-39e367e7-9880-49f8-bc43-71c7763e9dc4.mp4
=> feat(composer-app): Markdown export & import

packages/apps/composer-app/src/main.tsx, packages/apps/halo-app/src/App.tsx, packages/apps/halo-app/src/main.tsx, packages/apps/halo-app/src/pages/IdentityPage.tsx, packages/apps/halo-app/src/util/index.ts, packages/apps/halo-app/src/util/namespace.ts, packages/apps/halo-app/src/vault/main.ts, packages/apps/halo-app/src/vault/shared-worker.ts, packages/apps/halo-app/vite.config.ts, packages/apps/patterns/react-appkit/package.json, packages/apps/patterns/react-appkit/src/telemetry/telemetry.ts, packages/apps/tasks-app/src/main.tsx, packages/apps/todomvc/src/main.tsx, packages/common/sentry/src/index.ts, packages/common/telemetry/src/index.ts, packages/devtools/devtools/src/app/App.tsx, packages/experimental/kai/src/main.tsx, pnpm-lock.yaml
Note: Brave shields seem to block sentry requests in workers even when they are disabled https://github.com/brave/brave-browser/issues/25958
=> fix(halo-app): sentry in shared worker

packages/devtools/cli/src/base-command.ts, packages/devtools/cli/src/commands/app/publish-workflow.test.ts, packages/devtools/cli/src/util/exec.ts
The app publishing test is skipped, for now, I could not make it work properly in a test environment
=> chore: CLI test

packages/apps/patterns/react-ui/package.json, packages/apps/patterns/react-ui/src/panels/JoinPanel/JoinHeading.tsx, packages/apps/patterns/react-ui/src/panels/JoinPanel/JoinPanel.tsx, packages/apps/patterns/react-ui/src/panels/JoinPanel/joinMachine.ts, packages/apps/patterns/react-ui/src/panels/JoinPanel/view-states/InvitationAccepted.tsx, packages/apps/patterns/react-ui/src/panels/JoinPanel/view-states/InvitationRescuer.tsx, packages/apps/patterns/react-ui/src/playwright/invitations.spec.ts, packages/apps/patterns/react-ui/src/util/index.ts, packages/apps/patterns/react-ui/src/util/toEmoji.ts, pnpm-lock.yaml
(Deferred to invitations panel increment):
=> fix(react-ui): Usability, tests, and QOL increment

packages/apps/patterns/react-ui/src/components/InvitationEmoji/InvitationEmoji.tsx, packages/apps/patterns/react-ui/src/components/InvitationEmoji/index.ts, packages/apps/patterns/react-ui/src/components/InvitationList/InvitationListItem.tsx, packages/apps/patterns/react-ui/src/components/InvitationList/InvitationStatusAvatar.tsx, packages/apps/patterns/react-ui/src/components/index.ts, packages/apps/patterns/react-ui/src/panels/JoinPanel/JoinHeading.tsx
=> feat: Invitation list emoji

packages/apps/patterns/react-ui/src/components/Clipboard/ClipboardProvider.tsx, packages/apps/patterns/react-ui/src/components/Clipboard/CopyButton.tsx, packages/apps/patterns/react-ui/src/components/Clipboard/index.ts, packages/apps/patterns/react-ui/src/components/InvitationList/InvitationList.tsx, packages/apps/patterns/react-ui/src/components/InvitationList/InvitationListItem.tsx, packages/apps/patterns/react-ui/src/components/index.ts, packages/apps/patterns/react-ui/src/translations/locales/en-US.ts
https://user-images.githubusercontent.com/855039/228350141-bd861575-1c29-43d8-af42-df91a6f6e416.mp4
=> feat(react-ui): Copy-Copied button

packages/apps/composer-app/src/pages/DocumentPage.tsx, packages/apps/composer-app/src/translations/en-US.ts, packages/apps/patterns/react-composer/src/components/Markdown/Markdown.tsx
https://user-images.githubusercontent.com/855039/228377613-1117f277-dfd1-4948-8cfc-0d57f01d199d.mp4
=> feat(composer-app): Restore file I/O for Markdown

docs/docs/.vuepress/styles/index.scss, docs/docs/guide/README.md, docs/vuepress.config.ts, tools/executors/protobuf-compiler/README.md
- Fix main page title bug.
- Grouped related rules.
=> chore: Docs css housekeeping

packages/apps/patterns/react-composer/src/components/Markdown/Markdown.tsx, packages/apps/patterns/react-ui/src/panels/JoinPanel/view-states/InvitationInput.tsx
=> fix(react-composer): Composer zebra

packages/apps/patterns/react-ui/src/layouts/PanelSidebar/PanelSidebar.tsx
Resolves #3022.
https://user-images.githubusercontent.com/855039/231813948-42aded2e-c7f3-4144-86b5-6b6a169bc5cc.mp4
=> fix(react-ui): Sidebar no longer blocks pointer events

packages/ui/aurora/src/components/Message/Message.tsx
Did a dumb.
Tried to make it right!
Sorry for the error messages.
=> fix(aurora): Message refs

packages/apps/composer-app/src/components/Sidebar/SidebarTree.tsx
=> fix(composer-app): Overscroll

packages/ui/aurora/package.json
Fix typo which did not enable TurboSnap.
=> fix(aurora): TurboSnap

packages/ui/aurora/src/components/Avatars/AvatarGroup.stories.tsx
=> fix(aurora): `AvatarGroup` story

packages/apps/composer-app/package.json, packages/apps/composer-app/src/main.tsx, packages/apps/composer-app/tsconfig.json, packages/apps/labs-app/src/main.tsx, pnpm-lock.yaml
Promote the Sketch plugin to Composer for maximum TLDraw goodness.
Closes #4330
=> feat: promote sketch to Composer

packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
=> fix(plugin-space): Revert: set an index when a Space or SpaceObject is created

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx, packages/apps/plugins/plugin-markdown/src/components/EditorSection.tsx, packages/apps/plugins/plugin-markdown/src/components/StandaloneLayout.tsx, packages/sdk/examples/src/examples/Editor.tsx, packages/ui/react-ui-editor/src/components/Markdown/markdownTheme.ts
This PR fixes a number of issues that were breaking layout and causing other undesired phenomena in the editor.
Does what it says in the commit messages, please see the log below.
=> fix(react-ui-editor): Fix broken layouts

packages/devtools/devtools/src/components/PanelContainer.tsx, packages/devtools/devtools/src/panels/agent/DashboardPanel/DashboardPanel.tsx, packages/devtools/devtools/src/panels/client/StoragePanel/StoragePanel.tsx, packages/devtools/devtools/src/panels/echo/SpaceListPanel/SpaceListPanel.tsx, packages/devtools/devtools/src/panels/mesh/SignalPanel/SignalPanel.tsx, packages/devtools/devtools/src/panels/mesh/SwarmPanel/SwarmPanel.tsx
Does what it says on the tin! Also refactors `className` to `classNames` in another place where it’s passed to `mx`.
=> fix(devtools): Restore SwarmPanel state and show positive empty messages.

packages/devtools/devtools/vite.config.ts
=> fix: Revert fix: devtools wasm plugin

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx, packages/apps/plugins/plugin-table/src/components/TableMain.tsx, packages/apps/plugins/plugin-table/src/schema/builder.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/Table/props.ts, packages/ui/react-ui-table/src/helpers.tsx
=> fix(react-ui-table,plugin-table): Avoid giving objects with circular references to a recursive function

packages/apps/plugins/plugin-layout/src/components/MainLayout.tsx, packages/apps/plugins/plugin-table/src/translations.ts, packages/ui/react-ui-table/src/index.ts, packages/ui/react-ui-table/src/theme.ts, packages/ui/react-ui-theme/src/styles/components/main.ts, packages/ui/react-ui-theme/src/theme.css
This PR
- fixes sticky position and z-indexes
- fixes missing translations
=> fix(plugin-table): Fix integration bugs

packages/apps/plugins/plugin-stack/src/components/StackMain.tsx, packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx, packages/apps/plugins/plugin-table/src/components/TableMain.tsx, packages/apps/plugins/plugin-table/src/schema/builder.tsx, packages/ui/react-appkit/src/components/NavMenu/NavMenu.tsx, packages/ui/react-ui-table/src/components/ColumnMenu.tsx, packages/ui/react-ui-table/src/components/Table/props.ts, packages/ui/react-ui-table/src/helpers.tsx, packages/ui/react-ui-table/src/schema.ts, packages/ui/react-ui-table/src/theme.ts, packages/ui/react-ui-table/src/translations.ts, packages/ui/react-ui-theme/src/styles/components/button.ts
This PR:
- Fixes table layouts in Stack and Presenter
- Temporarily removes ‘Date’ as a column type in the UI until implementation is finished
- Fixes ‘Number’ column type
- Fixes/adjusts translations
=> fix(react-ui-table,plugin-table): Table bugs

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx, packages/apps/plugins/plugin-table/src/components/TableMain.tsx, packages/ui/react-ui-table/package.json, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/Table/props.ts, pnpm-lock.yaml
This PR implements virtualization for Table.
=> feat(react-ui-table): Virtualization

packages/apps/composer-app/src/stories/NavtreePresence.stories.tsx, packages/sdk/react-shell/src/stories/Invitations.e2e-stories.tsx, packages/ui/storybook-utils/src/decorators/with-theme.ts
This PR:
- establishes a pattern for connecting stories with translations
- fixes missing translations in the invitations e2e story
=> fix(stories): Translations

packages/ui/react-ui-editor/package.json, packages/ui/react-ui/src/components/Avatars/Avatar.stories.tsx, packages/ui/react-ui/src/components/Avatars/AvatarGroup.stories.tsx, packages/ui/react-ui/src/components/Breadcrumb/Breadcrumb.stories.tsx, packages/ui/react-ui/src/components/Buttons/Button.stories.tsx, packages/ui/react-ui/src/components/Buttons/Toggle.stories.tsx, packages/ui/react-ui/src/components/Buttons/ToggleGroup.stories.tsx, packages/ui/react-ui/src/components/Dialogs/AlertDialog.stories.tsx, packages/ui/react-ui/src/components/Dialogs/Dialog.stories.tsx, packages/ui/react-ui/src/components/DropdownMenu/DropdownMenu.stories.tsx, packages/ui/react-ui/src/components/Input/Input.stories.tsx, packages/ui/react-ui/src/components/Link/Link.stories.tsx, packages/ui/react-ui/src/components/Lists/List.stories.tsx, packages/ui/react-ui/src/components/Lists/Tree.stories.tsx, packages/ui/react-ui/src/components/Main/Main.stories.tsx, packages/ui/react-ui/src/components/Message/Message.stories.tsx, packages/ui/react-ui/src/components/Popover/Popover.stories.tsx, packages/ui/react-ui/src/components/ScrollArea/ScrollArea.stories.tsx, packages/ui/react-ui/src/components/Select/Select.stories.tsx, packages/ui/react-ui/src/components/Status/Status.stories.tsx, packages/ui/react-ui/src/components/Tag/Tag.stories.tsx, packages/ui/react-ui/src/components/Toast/Toast.stories.tsx, packages/ui/react-ui/src/components/Toolbar/Toolbar.stories.tsx, packages/ui/react-ui/src/components/Tooltip/Tooltip.stories.tsx, packages/ui/react-ui/src/playground/Controls.stories.tsx, packages/ui/react-ui/src/playground/Surfaces.stories.tsx, pnpm-lock.yaml, tools/stories/.storybook-shared/config.ts, tools/stories/package.json, tools/stories/ui-stories/main.mts
Resolves #4852 (finally).
Preview of the publishable Storybook here: https://657b8bd65608e7e275fd7ae8-jpdyesalui.chromatic.com
=> fix(stories,react-ui): Restore missing screen captures, polish publishable Storybook

.circleci/scripts/publish.sh, nx.json
closes https://github.com/dxos/security/issues/15
=> fix: remove NX token

packages/apps/plugins/plugin-mermaid/src/extensions/mermaid.ts
And make sure the editor's geometry gets re-measured after rendering finishes.
=> fix(plugin-mermaid): Make it possible to cursor into Mermaid diagrams

packages/ui/react-ui-navtree/src/components/NavTreeItem.tsx, packages/ui/react-ui-navtree/src/components/NavTreeItemAction.tsx
=> fix(react-ui-navtree): Fix NavTreeItemActionContextMenu without actions

packages/apps/composer-app/index.html, packages/apps/plugins/plugin-client/src/ClientPlugin.tsx, packages/devtools/devtools/index.html
=> fix: Use legacy echo by default

packages/apps/plugins/plugin-markdown/src/extensions.tsx, packages/apps/plugins/plugin-search/src/SearchPlugin.tsx, packages/apps/plugins/plugin-search/src/components/SearchMain.tsx, packages/apps/plugins/plugin-space/src/util.tsx, packages/core/agent/src/agent.ts, packages/core/echo/echo-schema/src/object/typed-object.ts, packages/sdk/app-graph/src/graph.ts, packages/ui/react-ui-table/src/helpers.tsx
Bypasses possible startup race condition with graph state to fix search plugin.
=> fix: search plugin

packages/core/mesh/network-manager/src/transport/simplepeer-transport-proxy.ts
=> fix: Increase WebRTC proxy sendData timeout

.idea/dictionaries/burdon.xml, packages/apps/composer-app/src/main.tsx, packages/apps/plugins/plugin-markdown/src/components/DocumentMain.tsx, packages/apps/plugins/plugin-markdown/src/extensions.tsx, packages/apps/plugins/plugin-thread/package.json, packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx, packages/apps/plugins/plugin-thread/src/components/CommentsSidebar.tsx, packages/apps/plugins/plugin-thread/src/components/Thread/ChatInput.tsx, packages/apps/plugins/plugin-thread/src/components/Thread/CommentThread.tsx, packages/ui/react-ui-editor/src/components/TextEditor/MarkdownEditor.stories.tsx, packages/ui/react-ui-editor/src/components/TextEditor/TextEditor.tsx, packages/ui/react-ui-editor/src/components/TextEditor/comments.stories.tsx, packages/ui/react-ui-editor/src/extensions/automerge/automerge.ts, packages/ui/react-ui-editor/src/extensions/automerge/defs.ts, packages/ui/react-ui-editor/src/extensions/automerge/semaphore.ts, packages/ui/react-ui-editor/src/extensions/comments.ts, packages/ui/react-ui-editor/src/extensions/cursor.ts, packages/ui/react-ui-editor/src/extensions/index.ts, packages/ui/react-ui-editor/src/extensions/sync.ts, packages/ui/react-ui-editor/src/hooks/automerge.ts, packages/ui/react-ui-editor/src/hooks/defs.ts, packages/ui/react-ui-editor/src/hooks/index.ts, packages/ui/react-ui-editor/src/hooks/useTextModel.ts, packages/ui/react-ui-editor/src/hooks/yjs.ts, pnpm-lock.yaml
=> chore: Codemirror comments/state

package.json
=> fix: guard husky

packages/apps/plugins/plugin-stack/src/components/StackSettings.tsx, packages/apps/plugins/plugin-thread/package.json, packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx, packages/apps/plugins/plugin-thread/src/components/ThreadSettings.tsx, packages/apps/plugins/plugin-thread/src/components/index.ts, packages/apps/plugins/plugin-thread/src/translations.ts, packages/apps/plugins/plugin-thread/src/types.ts, packages/apps/plugins/plugin-thread/tsconfig.json, packages/apps/plugins/plugin-undo/package.json, packages/apps/plugins/plugin-undo/tsconfig.json, packages/sdk/react-client/src/testing/ClientRepeater.tsx, pnpm-lock.yaml
=> feat(plugin-thread): add standalone thread setting

packages/apps/templates/bare-template/src/src/App.tsx.t.ts, packages/apps/templates/bare-template/src/src/ErrorBoundary.tsx.t.ts, packages/apps/templates/bare-template/src/src/translations.ts.t.ts
This PR attempts to resolves issues created in the app templates from the removal of react-appkit.
=> fix(bare-template): issues with appkit removal

packages/apps/tasks/project.json, packages/apps/templates/hello-template/project.json, packages/apps/templates/tasks-template/project.json, packages/gravity/proto-guard/project.json
* missing `tmp` directory for proto-guard
* missing build for templates `Error: Cannot find module '/home/circleci/project/dxos/packages/apps/templates/hello-template/node_modules/@dxos/bare-template/dist/src/template.t.js'. Please verify that the package.json has a valid "main" entry`
=> fix: test deps

packages/apps/composer-app/src/playwright/single-player.spec.ts
Addresses flakiness introduced into some e2e tests by #5372
=> test(composer-app): e2e fixes

packages/devtools/cli/src/commands/agent/start.ts
ref https://github.com/dxos/dxos/issues/5408
=> fix: agent cli logging

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts
=> fix: Warn if space key is not present for share policy check

docs/package.json, packages/devtools/devtools-extension/package.json, packages/devtools/devtools-extension/tsconfig.json, pnpm-lock.yaml
Fixes bundling issues introduced by #4454
=> chore: add missing deps to fix bundle

packages/core/echo/echo-schema/src/object/typed-object.ts, packages/core/echo/echo-schema/src/query/query.ts, packages/core/echo/echo-schema/src/testing/testing.ts, packages/devtools/cli/src/base-command.ts, packages/devtools/devtools/src/panels/client/TracingPanel/MetricsView.tsx, packages/sdk/client/src/client/client.ts, packages/sdk/client/src/echo/space-list.ts, packages/sdk/client/src/services/iframe-service-host.ts, packages/sdk/client/src/services/iframe-service-proxy.ts, packages/sdk/client/src/services/local-client-services.ts, packages/sdk/client/src/services/service-proxy.ts, packages/sdk/client/src/services/worker-client-services.ts, packages/sdk/client/src/tests/text.test.ts
=> chore: Extra diagnostics for space list

packages/apps/composer-app/src/main.tsx
Resolves #5449 by moving theme plugin ahead of pwa plugin
Also ensure pwa/native plugins don't show up in settings list
=> fix(composer-app): ensure toast provider is available to pwa plugin

packages/apps/plugins/plugin-files/package.json, packages/apps/plugins/plugin-files/src/FilesPlugin.tsx, packages/apps/plugins/plugin-layout/src/LayoutPlugin.tsx, packages/apps/plugins/plugin-markdown/package.json, packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/apps/plugins/plugin-markdown/src/components/DocumentMain.tsx, packages/apps/plugins/plugin-markdown/src/components/DocumentSection.tsx, packages/apps/plugins/plugin-markdown/src/extensions.tsx, packages/apps/plugins/plugin-markdown/src/types.ts, packages/apps/plugins/plugin-markdown/src/util.tsx, packages/apps/plugins/plugin-markdown/tsconfig.json, packages/apps/plugins/plugin-mermaid/src/MermaidPlugin.tsx, packages/apps/plugins/plugin-thread/package.json, packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx, packages/apps/plugins/plugin-thread/src/components/ThreadsContainer.tsx, packages/apps/plugins/plugin-thread/src/types.ts, packages/apps/plugins/plugin-thread/tsconfig.json, packages/ui/react-ui-editor/src/components/TextEditor/MarkdownEditor.stories.tsx, packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.stories.tsx, packages/ui/react-ui-editor/src/extensions/comments.ts, packages/ui/react-ui-thread/src/Thread/Comments.stories.tsx, pnpm-lock.yaml
Resolves #5464
- inverts the dependency between thread and markdown plugins, markdown plugin is more core/essential so i
t should not require threads plugin to work properly
- cleans up markdown extension provides, removes the vestigial `onChange`
- stops thread selection from clearing existing thread positions state
=> fix(plugin-thread): fix flashing when creating a new thread

packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.tsx, packages/ui/react-ui-editor/src/extensions/markdown/formatting.ts, packages/ui/react-ui-editor/src/hooks/useActionHandler.ts, packages/ui/react-ui/src/components/Select/Select.tsx
- Update header toolbar selector (change to icon).
- Review and test formatting code.
=> chore: Toolbar style

packages/apps/templates/bare-template/src/src/ServiceWorkerToast.tsx.t.ts
fixed broken bare template when pwa was on
=> fix: absence of toast.provider in templates for pwa

packages/apps/plugins/plugin-chain/src/components/PromptTemplate/PromptTemplate.stories.tsx, packages/apps/plugins/plugin-chain/src/components/PromptTemplate/PromptTemplate.tsx, packages/apps/plugins/plugin-chain/src/presets.ts, packages/apps/plugins/plugin-thread/src/components/command-extension.ts, packages/ui/react-ui-editor/src/components/TextEditor/MarkdownEditor.stories.tsx, packages/ui/react-ui-editor/src/components/TextEditor/TextEditor.stories.tsx, packages/ui/react-ui-editor/src/components/TextEditor/TextEditor.tsx, packages/ui/react-ui-editor/src/components/TextEditor/automerge.stories.tsx, packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.stories.tsx, packages/ui/react-ui-editor/src/extensions/annotations.ts, packages/ui/react-ui-editor/src/extensions/index.ts, packages/ui/react-ui-editor/src/hooks/useTextModel.ts, packages/ui/react-ui-theme/src/config/tailwind.ts, packages/ui/react-ui-thread/src/Thread/Thread.stories.tsx, packages/ui/react-ui-thread/src/Thread/Thread.tsx
=> feat: Make thread processing animation more prominent.

packages/core/agent/src/plugins/query/plugin.ts, packages/core/echo/echo-schema/src/automerge/automerge-array.ts, packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.test.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.ts, packages/core/echo/echo-schema/src/automerge/index.ts, packages/core/echo/echo-schema/src/automerge/types.ts, packages/core/echo/echo-schema/src/database.ts, packages/core/echo/echo-schema/src/object/clone.ts, packages/core/echo/echo-schema/src/object/types.ts, packages/core/echo/echo-schema/src/object/util.ts, packages/core/echo/echo-schema/src/serializer.test.ts
- Simplify automerge-object core
- Separate proxy API from the core implemtentaion
This Pull Request ...
Create an `AutomergeObjectCore` class to handle:
- DB binding
- Doc management
- TODO: update tracking
- TODO: link resolution
- TODO: encoding/decoding partially
=> refactor: Extract core automerge-object functions 

packages/apps/templates/bare-template/src/tsconfig.json.t.ts, tools/monitors/bare-template-monitor/test/template.spec.ts, tools/monitors/hello-template-monitor/test/template.spec.ts
Tests are currently timing out in CI
=> test: give template build monitors more time to run

packages/sdk/examples/project.json, packages/sdk/examples/src/examples/Editor.tsx, packages/sdk/examples/src/main.tsx, packages/sdk/examples/src/playwright/app-manager.ts, packages/sdk/examples/src/playwright/basic.spec.ts, packages/sdk/examples/src/playwright/playwright.config.ts
This demo has broken a couple times recently, putting some baseline tests in place to help catch those issues earlier.
=> test(examples): add basic e2e tests

packages/common/async/src/mutex.test.ts, packages/common/async/src/mutex.ts, packages/common/util/src/defer.ts, packages/common/util/src/explicit-resource-management-polyfill.ts, packages/core/echo/echo-schema/src/automerge/automerge-array.ts, packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.ts, packages/core/echo/echo-schema/src/automerge/doc-semaphore.ts
=> fix: Remove recursive doc changes

packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.ts, packages/core/echo/echo-schema/src/object/subscription.test.ts
=> fix: Make updates synchronous again

packages/core/echo/automerge/package.json, packages/core/echo/echo-db/package.json, packages/gravity/kube-testing/package.json, packages/ui/react-ui-editor/package.json, pnpm-lock.yaml
closes [#5555](https://github.com/dxos/dxos/issues/5555)
=> chore: Bump automerge

packages/core/echo/echo-schema/src/automerge/automerge-array.ts, packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.ts, packages/core/echo/echo-schema/src/automerge/types.ts, packages/core/echo/echo-schema/src/object/array.ts, packages/core/echo/echo-schema/src/object/typed-object.ts
=> refactor: Move encoding & decoding into AutomergeObjectCore

packages/core/echo/echo-schema/src/automerge/automerge-db.ts, packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.test.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.ts, packages/core/echo/echo-schema/src/object/subscription.test.ts, packages/core/echo/echo-schema/src/util/signal.ts, packages/core/echo/echo-signals/src/core.ts, packages/core/echo/echo-signals/src/preact.ts, packages/core/echo/echo-signals/src/react.ts
=> feat: ECHO objects can be bound again to a different DocHandle

packages/apps/templates/bare-template/src/src/App.tsx.t.ts, packages/apps/templates/bare-template/src/src/main.ts.t.ts
Ensures that shell is available in app template output.
=> fix(bare-template): configure shell for client

packages/common/random-access-storage/src/browser/web-fs.ts, packages/common/random-access-storage/src/common/memory-storage.ts, packages/common/random-access-storage/src/node/node-storage.ts, packages/common/random-access-storage/src/testing/storage.blueprint-test.ts, vitest.shared.ts
Brings back https://github.com/dxos/dxos/commit/8e7563ceeb7a6ebdb3892c95a1a9024bd5ec5558 with race condition fix.
=> test: random access storage concurrent test fixes + extra tests

packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/apps/plugins/plugin-space/src/components/SpaceMain/SpaceMain.tsx
This PR restores copy functionality for `SpaceMain`.
https://github.com/dxos/dxos/assets/855039/1e1cb3f4-77c0-4025-a0e9-94844cddaa4e
https://github.com/dxos/dxos/assets/855039/f638ef55-0d9c-450f-8d68-b1aee868fb22
=> fix(plugin-space): Add missing `ClipboardProvider`s.

packages/apps/plugins/plugin-help/src/components/Shortcuts/ShortcutsList.tsx
=> fix(plugin-help): Fix ShortcutsList layout

packages/core/echo/echo-schema/src/effect/proxy.test.ts, packages/core/echo/echo-schema/src/effect/proxy.ts, packages/core/echo/echo-schema/src/effect/reactive.ts, packages/core/echo/echo-schema/src/effect/untyped-handler.ts
=> feat: Finalize in-memory reactive object

packages/apps/plugins/plugin-thread/src/components/ChatContainer.tsx, packages/apps/plugins/plugin-thread/src/components/CommentContainer.tsx, packages/sdk/shell/package.json, packages/ui/react-ui-editor/package.json, packages/ui/react-ui-stack/package.json, packages/ui/react-ui-table/package.json, packages/ui/react-ui-thread/src/Message/Message.tsx, packages/ui/react-ui-thread/src/Thread/Comments.stories.tsx, packages/ui/react-ui/package.json, pnpm-lock.yaml
Resolves #5711.
This PR passes a ref between thread containers and `MessageTextbox` to better control editor focus on remounts.
https://github.com/dxos/dxos/assets/855039/ffdc5255-bcaf-4431-81d5-9e9b9b92a846
=> fix: MessageTextbox autoFocus

packages/core/echo/echo-schema/src/hypergraph.ts, packages/core/echo/echo-schema/src/indexing/indexing.test.ts
resolves https://github.com/dxos/dxos/issues/5717
=> test: Add indexing unit test

packages/apps/composer-app/src/playwright/app-manager.ts, packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx, packages/apps/plugins/plugin-space/src/components/PersistenceStatus.tsx, packages/apps/plugins/plugin-space/src/components/SpaceMain/SpaceMain.tsx, packages/apps/plugins/plugin-stack/src/components/StackMain.tsx, packages/ui/react-ui-stack/src/components/Section.tsx, packages/ui/react-ui-stack/src/components/Stack.tsx, packages/ui/react-ui-theme/src/styles/components/main.ts, packages/ui/react-ui-theme/src/styles/fragments/focus.ts, packages/ui/react-ui/src/components/Main/Main.tsx
Resolves #5741. Resolves #5742. Resolves #5740.
Fixes an e2e regression caused by #5695.
=> fix: Layout bugs

packages/devtools/cli/src/base-command.ts, packages/devtools/cli/src/commands/agent/start.ts, packages/devtools/cli/src/commands/agent/stop.ts, packages/devtools/cli/src/commands/app/create.ts, packages/devtools/cli/src/commands/debug/error.ts, packages/devtools/cli/src/commands/halo/credential/list.ts, packages/devtools/cli/src/commands/halo/identity.ts, packages/devtools/cli/src/commands/halo/join.ts, packages/devtools/cli/src/commands/kube/auth.ts, packages/devtools/cli/src/commands/kube/deploy.ts, packages/devtools/cli/src/commands/space/create.ts, packages/devtools/cli/src/commands/space/list.ts, packages/devtools/cli/src/errors.ts
resolves https://github.com/dxos/dxos/issues/4933
resolves https://github.com/dxos/dxos/issues/5203
resolves https://github.com/dxos/dxos/issues/5749
=> feat(cli): Improve Error handling; fix(cli): Fix UX bugs

packages/apps/composer-app/src/devtools.tsx, packages/apps/plugins/plugin-debug/src/DebugPlugin.tsx
This Pull Request ensures that devtools is accessible even if it wasn't turned on beforehand.
- sets the default values for the debug plugin settings to true
- adds a confirm dialog to enter devtools if you haven't turned it on before
=> chore(composer-app): make devtools easier to access

packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts
To avoid disruptive popping of the content around the cursor.
Issue https://github.com/dxos/dxos/issues/5755
=> fix(react-ui-editor): Delay hiding/unhiding of markdown markup during cursor motion

packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/apps/plugins/plugin-markdown/src/util.tsx, packages/apps/plugins/plugin-space/src/util.tsx, packages/core/echo/echo-schema/src/automerge/automerge-db.ts, packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/automerge-object.ts, packages/core/echo/echo-schema/src/guarded-scope.ts, packages/core/echo/echo-schema/src/hypergraph.ts, packages/core/echo/echo-schema/src/query/filter.ts, packages/core/echo/echo-schema/src/query/query.ts, packages/core/echo/echo-signals/src/core.ts, packages/core/echo/echo-signals/src/preact.ts, packages/core/echo/echo-signals/src/react.ts, packages/core/echo/echo-signals/src/runtime/index.ts
=> fix: Signal oversubscriptions 

packages/core/echo/echo-schema/package.json, packages/core/echo/echo-schema/project.json, packages/core/echo/echo-schema/src/effect/non-echo-proxy.test.ts, packages/core/echo/echo-schema/src/effect/untyped-handler.ts, packages/core/echo/echo-schema/src/schema.ts
=> feat: Support getters in E.object and add a @dxos/echo-schema/schema entrypoint

packages/apps/plugins/plugin-chain/package.json, packages/apps/plugins/plugin-mermaid/package.json, packages/apps/plugins/plugin-outliner/package.json, packages/apps/plugins/plugin-script/package.json, packages/apps/plugins/plugin-thread/package.json, packages/ui/react-ui-editor/package.json, pnpm-lock.yaml
To fix the cursor position issue noted in https://github.com/dxos/dxos/pull/5821
=> fix(react-ui-editor): Upgrade @codemirror/view to 6.25.0

packages/apps/plugins/plugin-chain/src/ChainPlugin.tsx, packages/apps/plugins/plugin-chess/src/ChessPlugin.tsx, packages/apps/plugins/plugin-debug/src/DebugPlugin.tsx, packages/apps/plugins/plugin-explorer/src/ExplorerPlugin.tsx, packages/apps/plugins/plugin-files/src/FilesPlugin.tsx, packages/apps/plugins/plugin-github/src/GithubPlugin.tsx, packages/apps/plugins/plugin-gpt/src/GptPlugin.tsx, packages/apps/plugins/plugin-grid/src/GridPlugin.tsx, packages/apps/plugins/plugin-inbox/src/InboxPlugin.tsx, packages/apps/plugins/plugin-kanban/src/KanbanPlugin.tsx, packages/apps/plugins/plugin-map/src/MapPlugin.tsx, packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/apps/plugins/plugin-outliner/src/OutlinerPlugin.tsx, packages/apps/plugins/plugin-presenter/src/PresenterPlugin.tsx, packages/apps/plugins/plugin-script/src/ScriptPlugin.tsx, packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx, packages/apps/plugins/plugin-space/src/util.tsx, packages/apps/plugins/plugin-stack/src/StackPlugin.tsx, packages/apps/plugins/plugin-table/src/TablePlugin.tsx, packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx
This pull request batches graph updates in plugin graph builders in order to improve performance by avoiding recomputing the navtree more than is necessary.
=> chore: wrap graph updates in batch

packages/core/echo/echo-schema/src/effect/non-echo-proxy.test.ts, packages/core/echo/echo-schema/src/effect/untyped-handler.ts
=> fix: Do not proxify getters that return arrays

packages/sdk/client-services/src/packlets/vault/shared-worker-connection.ts, packages/sdk/client/src/services/service-proxy.ts
=> fix: Increase timeouts to prevent crashes during boot

packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts
=> fix: Reference decoding

packages/apps/composer-app/script-frame/main.tsx, packages/apps/composer-app/vite.config.ts, packages/apps/plugins/plugin-script/src/compiler/compiler.test.ts, packages/apps/plugins/plugin-script/src/compiler/compiler.ts, packages/apps/plugins/plugin-script/src/components/FrameContainer/FrameContainer.tsx, packages/apps/plugins/plugin-script/src/components/ScriptBlock.tsx
=> fix: Script Plugin

packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/types.ts, packages/core/echo/echo-schema/src/effect/echo-proxy.test.ts, packages/core/echo/echo-schema/src/effect/reactive.ts, packages/core/echo/echo-schema/src/type-collection.ts
=> feat: Support references in ECHO-effect schema

packages/apps/plugins/plugin-space/src/serializer/clone.ts, packages/apps/plugins/plugin-space/src/serializer/file-serializer.ts, packages/apps/plugins/plugin-space/src/serializer/serializers.ts, packages/core/echo/echo-schema/src/serializer.ts
clone was using wrong serializer
=> fix: Fix move objects cross spaces

packages/apps/composer-app/src/playwright/app-manager.ts, packages/apps/composer-app/src/playwright/collaboration.spec.ts, packages/apps/composer-app/src/playwright/plugins/markdown.ts, packages/core/mesh/rpc/src/rpc.ts, packages/sdk/client-services/src/packlets/vault/shared-worker-connection.ts, packages/sdk/client/src/services/service-proxy.ts
This PR fixes e2e tests which were failing because of key binding issues.
Reverts #5856
=> chore: Fix keybinding in e2e tests

docs/content/composer/plugins/README.md, packages/apps/templates/plugin-template/LICENSE, packages/apps/templates/plugin-template/README.md, packages/apps/templates/plugin-template/package.json, packages/devtools/initializers/create-app-plugin/.eslintrc.js, packages/devtools/initializers/create-app-plugin/LICENSE, packages/devtools/initializers/create-app-plugin/README.md, packages/devtools/initializers/create-app-plugin/README.yml, packages/devtools/initializers/create-app-plugin/bin/main.js, packages/devtools/initializers/create-app-plugin/package.json, packages/devtools/initializers/create-app-plugin/project.json, packages/devtools/initializers/create-app-plugin/src/main.ts, packages/devtools/initializers/create-app-plugin/tsconfig.json, packages/sdk/examples/src/template/LICENSE, packages/sdk/examples/src/template/README.md, pnpm-lock.yaml, release-please-config.json
this ensures new plugin template is configured for public publishing
=> feat: new composer plugin template app

packages/apps/composer-app/src/internal.ts
=> feat: set group from param on internal.html

packages/core/echo/echo-schema/src/automerge/automerge-db.ts, packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/automerge/types.ts, packages/core/echo/echo-schema/src/hypergraph.ts, packages/core/echo/echo-schema/src/query/filter.test.ts, packages/core/echo/echo-schema/src/query/filter.ts, packages/core/echo/echo-schema/src/query/query.ts
=> refactor: Remove proxy usages from `db.query`

packages/core/echo/echo-schema/src/automerge/automerge-db.ts, packages/sdk/client/src/echo/space-proxy.ts
=> fix: Only call update when db is initialized

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/indexing/package.json, packages/core/echo/indexing/src/index-service.ts, packages/core/echo/indexing/src/index-store.ts, packages/core/echo/indexing/src/indexer.test.ts, packages/core/echo/indexing/src/indexer.ts, packages/core/echo/indexing/src/types.ts, packages/core/echo/indexing/tsconfig.json, packages/core/protocols/src/indexing.ts, packages/sdk/client-services/src/packlets/indexing/index.ts, packages/sdk/client-services/src/packlets/indexing/util.ts, packages/sdk/client-services/src/packlets/services/service-context.ts, packages/sdk/client/src/echo/agent-query-source-provider.ts, packages/sdk/client/src/tests/indexing.test.ts, pnpm-lock.yaml
When you introduce a new index it should get updated with all existing data
=> feat: Add indexing of all documents on index creation

packages/common/log/src/options.ts, packages/common/log/src/platform/browser/index.ts
This reverts commit f03409d959a5d7d60ebb436128b08970abdbeed6.
=> revert: "fix: allow localStorage.dxlog to override config"

packages/apps/plugins/plugin-presenter/src/PresenterPlugin.tsx, packages/apps/plugins/plugin-presenter/src/types.ts
fixes a bug where presenter was removing stacks from the graph
=> fix(plugin-presenter): give present actions unique ids

packages/apps/templates/plugin-template/src/.npmignore
=> chore(plugin-template): remove .npmignore file

packages/apps/plugins/plugin-chain/src/components/ChainMain.tsx, packages/apps/plugins/plugin-chain/src/components/PromptTemplate/PromptTemplate.tsx
Fixes a bug with chain plugin where source wasn't being updated on preset selection.
Pass deps to useTextEditor to fix it. 
Also remove prompts from echo if we remove them from chain.
=> fix(composer): fixed prompt source not updating

packages/common/context/src/context.test.ts, packages/common/context/src/context.ts
=> fix: Context dispose mutating callback list during dispose process

packages/core/agent/src/agent.ts, packages/core/mesh/messaging/src/signal-client/signal-rpc-client.ts, packages/core/mesh/network-manager/src/transport/libdatachannel-transport.ts, packages/sdk/observability/package.json, packages/sdk/observability/src/observability.ts, packages/sdk/observability/src/segment/browser.ts, packages/sdk/observability/src/segment/node.ts, pnpm-lock.yaml
* [signal-client] wait for WS connection to close
* [libdatachannel-transport] cleanup libdatachannel native resources
* [observability] upgrade from EOL Segment lib
* [agent] stop listening on UNIX domain socket
=> fix: free resources on close

packages/ui/react-ui-stack/src/components/Stack.tsx
This PR finishes an incomplete refactor from #5733.
=> fix(react-ui-stack): Finish a prop rename

packages/core/echo/echo-pipeline/src/space/data-pipeline.ts, packages/sdk/client/src/echo/space-list.ts, packages/sdk/client/src/echo/space-proxy.ts, packages/sdk/client/src/tests/indexing.test.ts, packages/sdk/client/src/tests/spaces.test.ts
Cached properties were broken for a while now so I am deleting them
=> chore: Delete cached properties

packages/apps/composer-app/project.json, packages/apps/plugins/plugin-registry/project.json, packages/apps/plugins/plugin-script/project.json, packages/apps/templates/bare-template/project.json, packages/apps/templates/hello-template/project.json, packages/apps/templates/plugin-template/project.json, packages/apps/templates/tasks-template/project.json, packages/common/plate/project.json, packages/common/react-async/project.json, packages/core/agent/project.json, packages/core/echo/echo-db/project.json, packages/core/echo/echo-generator/project.json, packages/core/echo/echo-query/project.json, packages/core/echo/echo-schema/project.json, packages/core/functions/project.json, packages/gravity/proto-guard/project.json, packages/sdk/migrations/project.json
resolves https://github.com/dxos/dxos/issues/5680
=> chore: Disable forceExit in tests

packages/core/echo/indexing/package.json, packages/core/echo/indexing/src/index-metadata-store.ts, packages/core/echo/indexing/src/indexer.ts, packages/core/echo/indexing/tsconfig.json, pnpm-lock.yaml
=> feat: Use traces in indexing

packages/apps/plugins/plugin-outliner/src/components/Outliner/Outliner.tsx
OutlinerItem was crashing asserting text is not equal to null.
=> fix(composer): fixed outliner broken with automerge fragmentation

packages/apps/plugins/plugin-debug/src/components/DebugSettings.tsx
Finish changes from https://github.com/dxos/dxos/pull/6150
=> fix: Preserve storage config on disk

packages/core/echo/echo-schema/src/automerge/automerge-db.ts, packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts, packages/core/echo/echo-schema/src/effect/echo-handler.ts, packages/core/echo/echo-schema/src/effect/echo-proxy.test.ts, packages/core/echo/echo-schema/src/effect/reactive.ts, packages/core/echo/echo-schema/src/serializer.test.ts, packages/core/echo/echo-schema/src/serializer.ts, packages/core/echo/echo-schema/src/tests/schema.ts
=> feat: Upgrade JSON serializer to new API

packages/sdk/config/src/loaders/browser.js
I am getting a weird error if trying to dynamically load localforage
=> fix: Fix Storage config loading

packages/core/echo/automerge/package.json, packages/core/echo/echo-db/package.json, packages/gravity/kube-testing/package.json, packages/ui/react-ui-editor/package.json, pnpm-lock.yaml
=> chore: Bump automerge packages

packages/devtools/cli/src/base-command.ts
avoid writing non-ASCII characters to JSONL log
=> fix(cli): JSONL logging

packages/apps/composer-app/project.json
=> fix: Enable force-exit for composer tests

.circleci/publish-config/config-development.yml, .circleci/publish-config/config-production.yml, .circleci/publish-config/config-staging.yml, packages/apps/composer-app/dx.yml, packages/apps/composer-app/src/migrations/migrations.test.ts, packages/apps/templates/plugin-template/src/composer/dx.yml, packages/core/agent/src/plugins/query/plugin.test.ts, packages/core/echo/echo-generator/src/generator.test.ts, packages/core/echo/echo-schema/src/database.ts, packages/core/echo/echo-schema/src/effect/dynamic/dynamic-schema.test.ts, packages/core/echo/echo-schema/src/effect/dynamic/schema-registry.test.ts, packages/core/echo/echo-schema/src/effect/echo-object-class.test.ts, packages/core/echo/echo-schema/src/effect/echo-proxy.test.ts, packages/core/echo/echo-schema/src/effect/proxy.test.ts, packages/core/echo/echo-schema/src/serializer.test.ts, packages/core/echo/echo-schema/src/testing/testing.ts, packages/core/protocols/src/proto/dxos/config.proto, packages/devtools/cli/config/config-default.yml, packages/devtools/cli/config/config-local.yml, packages/devtools/cli/src/base-command.ts, packages/devtools/cli/testing/config/user-1.yml, packages/devtools/cli/testing/config/user-2.yml, packages/sdk/client/src/client/client.ts, packages/sdk/client/src/echo/space-list.ts, packages/sdk/client/src/echo/space-proxy.ts, packages/sdk/client/src/tests/client.test.ts, packages/sdk/shell/dx.yml, packages/ui/react-ui-editor/dx.yml
The flag was enabled in main and is no longer needed.
=> chore(echo): remove useReactiveObjectApi defaulting to true

packages/apps/plugins/plugin-registry/project.json, packages/apps/plugins/plugin-script/project.json, packages/apps/templates/bare-template/project.json, packages/apps/templates/hello-template/project.json, packages/apps/templates/plugin-template/project.json, packages/apps/templates/tasks-template/project.json, packages/common/plate/project.json, packages/common/react-async/project.json, packages/core/agent/project.json, packages/core/echo/echo-db/project.json, packages/core/echo/echo-generator/project.json, packages/core/echo/echo-query/project.json, packages/core/echo/echo-schema/project.json, packages/core/functions/project.json, packages/gravity/proto-guard/project.json, packages/sdk/migrations/project.json
Revert "chore: Disable forceExit in tests (#6067)"
This reverts commit 8bba6f820aa5944fedea86e79d573f92c35c6ec9.
=> fix: re-enable forceExit for rest of tests

package.json, pnpm-lock.yaml
Closes https://github.com/dxos/dxos/issues/4946
=> fix: node 21 build

packages/core/echo/indexing/src/index-service.ts
=> fix: Fix context warning `large number of dispose callbacks`

packages/core/echo/echo-schema/src/effect/echo-handler.ts, packages/core/echo/echo-schema/src/effect/reactive.ts, packages/core/echo/echo-schema/src/query/filter.test.ts, packages/core/echo/echo-schema/src/query/filter.ts
* Don't throw on schema access if database is not set. There's code that handles unresolvable schema on attempt to write.
* Also don't lookup static schema in dynamic schema registry by checking reference protocol.
=> fix(echo): fixed trying to resolve static schema as dynamic schema

packages/core/echo/indexing/src/indexer.test.ts, packages/core/echo/indexing/src/indexer.ts, packages/sdk/client/src/tests/halo-persistent.test.ts, packages/sdk/client/src/tests/indexing.test.ts
=> test: Fix clean up of indexing test

packages/core/echo/echo-schema/src/database.ts
=> fix: Options object being mutated in db.query

packages/common/random-access-storage/package.json, packages/common/random-access-storage/project.json, pnpm-lock.yaml
=> fix: Revert: Bundle random-access-idb

packages/core/echo/echo-schema/src/effect/echo-proxy.test.ts, packages/core/echo/echo-schema/src/effect/reactive.ts
=> fix(echo-schema): reexpose deleted attribute with isDeleted

packages/apps/composer-app/src/playwright/app-manager.ts, packages/apps/composer-app/src/playwright/folders.spec.ts, packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/apps/plugins/plugin-space/src/util.tsx, packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx, packages/sdk/app-framework/src/plugins/IntentPlugin/plugin.tsx
Fixes some of the e2e tests that have been failing over the last week.
=> fix(composer-app): undo thread delete and space creation fixes

packages/apps/plugins/plugin-navtree/src/components/CommandsDialog.tsx
=> fix: add to space action missing from cmd-k

packages/common/keys/src/public-key.ts, packages/common/log/src/processors/common.ts, packages/common/log/src/processors/console-processor.ts, packages/common/log/src/processors/file-processor.ts, packages/common/util/src/json.ts
try and manage the overall size of the log messages
=> fix: jsonl logging

packages/apps/testbench-app/src/components/ItemList.tsx, packages/ui/react-ui-editor/src/components/TextEditor/TextEditor.stories.tsx, packages/ui/react-ui-editor/src/components/TextEditor/TextEditor.tsx, packages/ui/react-ui-editor/src/hooks/useTextEditor.ts
Resolves https://github.com/dxos/dxos/issues/6305
=> fix: initial selection bug

packages/core/echo/indexing/src/index-service.ts
=> fix: Defer indexing updates

packages/apps/composer-app/src/playwright/collaboration.spec.ts, packages/apps/testbench-app/src/main.tsx
Run client in worker by default in testbench to more closely emulate real world use cases.
=> chore(testbench): run client in worker

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/local-host-network-adapter.ts, packages/core/echo/echo-schema/src/automerge/automerge-context.ts, packages/sdk/client/src/common.ts, packages/sdk/client/src/echo/space-list.ts, packages/sdk/client/src/echo/space-proxy.ts, packages/sdk/client/src/halo/halo-proxy.ts, packages/sdk/client/src/invitations/invitations-proxy.ts, packages/sdk/client/src/mesh/mesh-proxy.ts, packages/sdk/client/src/services/iframe-service-proxy.ts, packages/sdk/client/src/services/shell-manager.ts, packages/sdk/client/src/services/worker-client-services.ts, packages/sdk/client/src/tests/client-services.test.ts
=> fix: Increase client RPC timeouts

packages/core/echo/echo-pipeline/src/automerge/automerge-host.test.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/index.ts, packages/core/echo/echo-pipeline/src/automerge/level.test.ts, packages/core/echo/echo-pipeline/src/automerge/leveldb-storage-adapter.ts, packages/core/echo/echo-pipeline/src/automerge/migrations.ts, packages/core/echo/echo-pipeline/src/automerge/storage-adapter.test.ts, packages/core/echo/echo-pipeline/src/automerge/types.ts, packages/core/echo/echo-pipeline/src/testing/level.ts, packages/core/echo/indexing/src/index-metadata-store.test.ts, packages/core/echo/indexing/src/index-metadata-store.ts, packages/core/echo/indexing/src/index-schema.ts, packages/core/echo/indexing/src/index-store.test.ts, packages/core/echo/indexing/src/index-store.ts, packages/core/echo/indexing/src/index.ts, packages/core/echo/indexing/src/indexer.test.ts, packages/core/echo/indexing/src/indexer.ts, packages/core/echo/indexing/src/storage-callbacks.ts, packages/core/protocols/src/indexing.ts, packages/sdk/client-services/src/packlets/indexing/util.ts, packages/sdk/client-services/src/packlets/services/service-context.ts, packages/sdk/client-services/src/packlets/services/service-host.ts, packages/sdk/client-services/src/packlets/testing/test-builder.ts, packages/sdk/client/src/testing/test-builder.ts, packages/sdk/client/src/tests/indexing.test.ts
=> feat: Batch automerge save with marking dirty

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-repo.test.ts, packages/sdk/client/src/client/client.ts, packages/sdk/client/src/tests/client.test.ts
=> fix: Workaround for the flush issue

packages/gravity/kube-testing/package.json, packages/gravity/kube-testing/src/spec/echo.ts, packages/gravity/kube-testing/src/spec/storage.ts, packages/gravity/kube-testing/tsconfig.json, pnpm-lock.yaml
=> fix: Fix storage testbench

packages/apps/plugins/plugin-space/src/components/AwaitingObject.tsx, packages/sdk/client-protocol/src/index.ts, packages/sdk/react-client/src/echo/useQuery.ts, packages/sdk/react-client/src/echo/useSpaceInvitations.ts, packages/sdk/react-client/src/halo/useContacts.ts, packages/sdk/react-client/src/halo/useDevices.ts, packages/sdk/react-client/src/halo/useHaloInvitations.ts, packages/sdk/react-client/src/mesh/useNetworkStatus.ts
=> fix: Incorrect useSyncExternalStore usages

packages/devtools/devtools/src/containers/DataSpaceSelector.tsx, packages/devtools/devtools/src/containers/index.ts, packages/devtools/devtools/src/hooks/useDevtoolsContext.tsx, packages/devtools/devtools/src/panels/echo/FeedsPanel/FeedsPanel.tsx, packages/devtools/devtools/src/panels/echo/MembersPanel/MembersPanel.tsx, packages/devtools/devtools/src/panels/echo/ObjectsPanel/ObjectsPanel.tsx, packages/devtools/devtools/src/panels/echo/SpaceInfoPanel/SpaceInfoPanel.tsx, packages/devtools/devtools/src/panels/halo/CredentialsPanel/CredentialsPanel.tsx, packages/devtools/devtools/src/panels/mesh/NetworkPanel/NetworkPanel.tsx
subset of https://github.com/dxos/dxos/pull/5757
=> feat(devtools): view HALO credentials

packages/core/echo/indexing/src/index-schema.ts, packages/core/mesh/messaging/src/signal-client/signal-client.test.ts, packages/core/mesh/messaging/src/signal-client/signal-client.ts, packages/core/mesh/messaging/src/signal-manager/memory-signal-manager.ts, packages/core/mesh/messaging/src/signal-manager/signal-manager.ts, packages/core/mesh/messaging/src/signal-manager/websocket-signal-manager.ts, packages/core/mesh/messaging/src/signal-methods.ts, packages/core/mesh/network-manager/src/swarm/peer.ts, packages/core/protocols/src/proto/dxos/mesh/swarm.proto, packages/gravity/kube-testing/src/spec/transport.ts
Enables the possibility of a compatible signaling client variant (e.g., for CF worker).
=> chore: Factor out signal client interface.

packages/core/echo/indexing/src/index-schema.test.ts, packages/core/echo/indexing/src/index-schema.ts, packages/core/echo/indexing/src/index-service.ts, packages/core/echo/indexing/src/index-text.ts, packages/sdk/client-services/src/packlets/indexing/util.ts, packages/sdk/client/src/echo/space-proxy.ts, packages/sdk/react-client/src/echo/useQuery.ts
=> refactor: Refactor IndexSchema to use map of sets

packages/sdk/client/package.json, packages/sdk/react-client/package.json
=> fix: `package.json` exports for `@dxos/client`

.syncpackrc.yml, packages/core/echo/automerge/package.json, packages/core/echo/echo-db/src/automerge/automerge-db.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.test.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-repo.test.ts, packages/core/echo/echo-pipeline/src/testing/level.ts, packages/core/protocols/src/proto/dxos/echo/service.proto, pnpm-lock.yaml, tools/executors/test/src/helpers/resource.ts
Revert because dependency difference brakes apps
=> revert: fix: Fix flush method on automergeDB (#6409)

packages/core/echo/indexing/src/index-schema.ts, packages/sdk/client/src/client/client.ts
=> fix: Fix empty typename query behavior

packages/apps/composer-app/src/migrations/migrations.test.ts, packages/apps/plugins/plugin-client/src/ClientPlugin.tsx, packages/apps/types/src/serializer/space-serializer.test.ts, packages/core/echo/echo-db/src/automerge/automerge-context.ts, packages/core/echo/echo-db/src/client/echo-client.ts, packages/core/echo/echo-db/src/client/index.ts, packages/core/echo/echo-db/src/database.ts, packages/core/echo/echo-db/src/index.ts, packages/gravity/kube-testing/src/spec/echo.ts, packages/sdk/client/src/client/client.ts, packages/sdk/client/src/echo/echo-client.ts, packages/sdk/client/src/echo/space-list.ts, packages/sdk/client/src/echo/space-proxy.ts, packages/sdk/client/src/tests/indexing.test.ts, packages/sdk/client/src/tests/spaces.test.ts
=> refactor: Introduce EchoClient

packages/sdk/shell/src/components/EmojiPicker.tsx, packages/sdk/shell/src/components/HuePicker.tsx, packages/sdk/shell/src/panels/IdentityPanel/IdentityPanel.tsx
This PR resolves a code quality issue introduced by using an effect instead of calling the async updater as a secondary action of setting state.
=> fix(shell): Remove IdentityPanel effect

packages/common/async/src/trigger.test.ts, packages/common/async/src/trigger.ts, packages/core/echo/echo-db/package.json, packages/core/echo/echo-db/src/automerge/automerge-db.ts, packages/core/echo/echo-db/src/client/echo-client.ts, packages/core/echo/echo-db/src/client/index-query-source-provider.ts, packages/core/echo/echo-db/src/host/echo-host.ts, packages/core/echo/echo-db/src/hypergraph.test.ts, packages/core/echo/echo-db/src/hypergraph.ts, packages/core/echo/echo-db/src/query/query-service.ts, packages/core/echo/echo-db/src/testing/echo-test-builder.ts, packages/core/echo/echo-db/src/testing/index.ts, packages/core/echo/echo-db/src/testing/integration.test.ts, packages/core/echo/echo-db/src/testing/testing.ts, packages/sdk/client-services/src/packlets/storage/level.ts, packages/sdk/client/src/client/client.ts, packages/sdk/client/src/echo/space-list.ts, packages/sdk/client/src/echo/space-proxy.ts, pnpm-lock.yaml
=> chore: Introduce EchoTestBuilder & add basic integration tests for ECHO

packages/core/echo/echo-db/src/host/echo-host.ts
=> chore: Delete flush workaround in EchoHost

packages/sdk/client-services/src/packlets/services/service-host.ts
see also: https://github.com/dxos/dxos/issues/6473
=> fix: show debug info for agent device join

packages/sdk/client/src/echo/space-proxy.ts
=> fix: Add toJSON to SpaceProxy

packages/devtools/devtools/src/panels/echo/SpaceListPanel/SpaceListPanel.tsx
=> fix(devtools): SpaceListPanel

packages/core/echo/echo-db/src/host/documents-iterator.ts, packages/core/echo/echo-db/src/query/query-service.ts, packages/core/echo/echo-pipeline/src/automerge/level.test.ts, packages/core/echo/echo-pipeline/src/automerge/leveldb-storage-adapter.ts, packages/core/echo/echo-pipeline/src/automerge/types.ts, packages/core/echo/indexing/package.json, packages/core/echo/indexing/src/index-metadata-store.test.ts, packages/core/echo/indexing/src/index-metadata-store.ts, packages/core/echo/indexing/src/indexer.test.ts, packages/core/echo/indexing/src/indexer.ts, packages/core/echo/indexing/src/storage-callbacks.ts, packages/core/echo/indexing/src/types.ts, packages/core/protocols/src/proto/dxos/echo/query.proto, pnpm-lock.yaml
resolves https://github.com/dxos/dxos/issues/6501
resolves https://github.com/dxos/dxos/issues/6416
=> feat: Index document on specified heads

packages/core/echo/indexing/src/index-metadata-store.test.ts, packages/core/echo/indexing/src/index-metadata-store.ts
=> fix: Fix `Error: Iterator could not decode entries`

packages/core/echo/echo-db/src/automerge/automerge-db.test.ts, packages/core/echo/echo-db/src/automerge/automerge-db.ts, packages/core/echo/echo-db/src/serializer.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-doc-loader.ts
Large space timeout during export.
Reschedule timeout while objects are being loaded.
=> fix(echo): dynamic serializer timeout

packages/core/echo/echo-db/src/database.ts
=> fix: make less astonishing error about hypergraphs

.vscode/settings.json, packages/apps/plugins/plugin-space/src/util.tsx, packages/core/echo/echo-db/src/query/query-state.ts, packages/core/echo/indexing/src/index-schema.ts, packages/core/echo/indexing/src/types.ts
- Narrows main Composer graph query to skip loading text documents.
=> fix: Test graph query filter

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx, packages/apps/plugins/plugin-table/src/components/ObjectTable/utils.ts, packages/apps/plugins/plugin-table/src/schema/columns.tsx, packages/ui/react-ui-table/src/components/ColumnMenu/ColumnMenu.stories.tsx, packages/ui/react-ui-table/src/components/ColumnMenu/ColumnMenu.tsx, packages/ui/react-ui-table/src/components/ColumnMenu/ColumnSettingsForm.tsx, packages/ui/react-ui-table/src/components/Table/props.ts
- Add buttons to the column menu to move a column left or right.
=> feat(tables): Column ordering

packages/core/echo/indexing/src/indexer.ts
=> fix: Make indexer error non-critical

packages/core/echo/echo-db/src/automerge/automerge-db.ts
=> fix: Do not flush unloaded documents

packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts, packages/core/echo/echo-schema/src/handler/typed-handler.ts
Fixes stack-table interop
cc @ZaymonFC 
- Resolves #6321
=> fix(echo): fixed trying to make EchoArray reactive

.vscode/settings.json, packages/common/async/src/task-scheduling.test.ts, packages/common/async/src/task-scheduling.ts, packages/core/echo/echo-db/src/host/echo-host.ts, packages/core/echo/echo-db/src/testing/integration.test.ts, packages/core/echo/indexing/src/index-metadata-store.ts, packages/core/echo/indexing/src/indexer.test.ts, packages/core/echo/indexing/src/indexer.ts
=> fix: Make indexer re-entrant & fix runaway tasks and unit-tests 

packages/apps/plugins/plugin-ipfs/package.json, packages/devtools/cli/package.json, pnpm-lock.yaml
maybe relevant to https://github.com/dxos/dxos/issues/5473 ?
=> fix: peer dependencies

packages/core/echo/echo-db/src/echo-handler/create.ts
Correct handling of `DynamicEchoSchema` in `validateInitialProps`.
=> fix(echo): fixed table in a stack not serialized

packages/apps/plugins/plugin-help/src/HelpPlugin.tsx
=> fix: disable joyride on startup

packages/common/kv-store/package.json
Closes https://github.com/dxos/dxos/issues/6631
=> fix: Publish @dxos/kv-store package

packages/apps/composer-app/src/playwright/folders.spec.ts, packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
- fixes folder tests failing due to folders being collapsed
- fixes collab test failing due to not sending an array for removed ids
=> test(composer-app): e2e test fixes

.idea/scopes/Sources.xml, packages/apps/composer-app/src/beta/BetaPlugin.tsx, packages/apps/plugins/plugin-debug/src/components/DebugStatus.tsx, packages/core/echo/echo-db/src/automerge/automerge-context.ts, packages/devtools/cli/package.json, packages/devtools/cli/src/base-command.ts, packages/devtools/cli/src/commands/agent/start.ts, packages/devtools/cli/src/commands/debug/error.ts, packages/devtools/cli/src/commands/halo/share.ts, packages/devtools/cli/src/commands/space/share.ts, packages/devtools/cli/src/errors.ts, packages/devtools/cli/src/hooks/command-not-found.ts, packages/devtools/cli/src/typings.d.ts, packages/devtools/cli/src/util/spaces.ts, packages/devtools/devtools/src/components/performance/panels/PerformancePanel.tsx, packages/devtools/devtools/src/components/performance/panels/QueriesPanel.tsx, packages/devtools/devtools/src/components/performance/panels/SpansPanel.tsx, packages/experimental/labs-functions/package.json, packages/experimental/labs-functions/src/auth/oauth.ts, packages/sdk/shell/src/components/DeviceList/DeviceListItem.tsx, pnpm-lock.yaml
=> feat: Clean-up CLI invitations and auto open connection.

packages/apps/composer-app/src/beta/BetaPlugin.tsx, packages/apps/composer-app/src/beta/notice.md
this tweaks the beta notice and disables it for now
=> chore: fix up beta notice and disable notice

packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/core/echo/echo-db/src/serializer.ts
Autocomplete is not working and this query is causing performance issues so omit it for now.
=> chore(plugin-markdown): comment out runaway query

packages/apps/composer-app/src/playwright/folders.spec.ts, packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/apps/plugins/plugin-space/src/util.tsx
=> fix(plugin-space): fix navigation to objects on creation

packages/common/log/src/decorators.ts, packages/common/util/src/map-values.test.ts, packages/common/util/src/map-values.ts, packages/core/echo/echo-db/src/automerge/automerge-context.ts, packages/core/echo/echo-db/src/automerge/automerge-object-core.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.ts
closes https://github.com/dxos/dxos/issues/6700
=> fix: Remove nesting from ECHO object JSON serialization

packages/core/echo/echo-db/src/serializer.test.ts, packages/core/echo/echo-db/src/serializer.ts
=> fix: References serialization

packages/apps/composer-app/src/beta/BetaPlugin.tsx, packages/apps/composer-app/src/beta/notice.md
=> fix: tweak beta notice and enable

packages/apps/testbench-app/vite.config.ts
=> chore: Disable testbench minification

packages/core/echo/echo-db/src/query/query-state.ts, packages/core/echo/indexing/src/index-schema.test.ts, packages/core/echo/indexing/src/index-schema.ts, packages/core/echo/indexing/src/index-store.test.ts, packages/core/echo/indexing/src/index-text.ts, packages/core/echo/indexing/src/indexer.test.ts, packages/core/echo/indexing/src/indexer.ts, packages/core/echo/indexing/src/types.ts, packages/sdk/client/src/tests/indexing.test.ts
resolves https://github.com/dxos/dxos/issues/6725
=> feat: Support indexed queries with `Filter.or`

packages/core/echo/echo-db/src/host/echo-host.ts, packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator.ts
=> chore: Code review fixes for #6635

packages/core/echo/indexing/src/indexer.ts
=> fix: Budget indexing time

packages/core/echo/echo-db/src/automerge/automerge-object-core.ts, packages/core/echo/echo-db/src/query/filter.ts, packages/core/echo/echo-schema/src/expando.ts, packages/core/echo/indexing/package.json, packages/core/echo/indexing/src/index-schema.ts, packages/core/echo/indexing/src/types.ts, packages/core/echo/indexing/tsconfig.json, packages/sdk/client/src/tests/indexing.test.ts, pnpm-lock.yaml
=> feat: Add ability to query Expando

packages/apps/plugins/plugin-debug/package.json, packages/apps/plugins/plugin-debug/src/components/DebugStatus.tsx, packages/apps/plugins/plugin-debug/tsconfig.json, packages/apps/plugins/plugin-layout/src/components/MainLayout.tsx, packages/apps/plugins/plugin-status-bar/src/components/StatusBar.tsx, packages/apps/plugins/plugin-status-bar/src/components/StatusBarImpl.tsx, packages/apps/plugins/plugin-status-bar/src/index.ts, pnpm-lock.yaml
Moves the debug plugin status into the new status bar.
=> refactor(plugin-debug): move debug status to status bar

packages/apps/plugins/plugin-inbox/src/components/Email/Mailbox.tsx, packages/apps/plugins/plugin-inbox/src/components/Email/MessageList.stories.tsx, packages/apps/plugins/plugin-inbox/src/components/Email/MessageList.tsx, packages/apps/plugins/plugin-inbox/src/testing/testing.ts
Updated to semantic colours so dark mode should work now as well.
=> feat(composer): Reflow `Inbox` for demo

packages/apps/plugins/plugin-chess/src/ChessPlugin.tsx, packages/apps/plugins/plugin-chess/src/components/Chess.tsx, packages/apps/plugins/plugin-chess/src/components/ChessArticle.tsx, packages/apps/plugins/plugin-chess/src/components/ChessMain.tsx, packages/apps/plugins/plugin-chess/src/components/index.ts, packages/apps/plugins/plugin-explorer/src/ExplorerPlugin.tsx, packages/apps/plugins/plugin-explorer/src/components/ExplorerArticle.tsx, packages/apps/plugins/plugin-explorer/src/components/index.ts, packages/apps/plugins/plugin-map/src/MapPlugin.tsx, packages/apps/plugins/plugin-map/src/components/MapArticle.tsx, packages/apps/plugins/plugin-map/src/components/index.ts, packages/apps/plugins/plugin-table/src/components/TableArticle.tsx, packages/experimental/chess-app/src/Chessboard.tsx
=> chore(deck): Deckify Explorer, Chess, Maps

packages/core/echo/echo-db/src/query/filter.ts, packages/core/echo/echo-schema/src/expando.ts, packages/core/echo/indexing/src/index-schema.ts, packages/sdk/client/src/tests/indexing.test.ts
=> test: Updated index tests

packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx, packages/apps/plugins/plugin-presenter/src/components/MarkdownSlideMain.tsx
=> chore(deck): Add `StatusBar` to DeckLayout

packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator.ts, packages/sdk/client-services/src/packlets/spaces/data-space-manager.ts, packages/sdk/client-services/src/packlets/spaces/data-space.ts
=> chore: Add space list diagnostic

.syncpackrc.yml, package.json, packages/core/echo/automerge/package.json, pnpm-lock.yaml
=> feat: Change automerge-wasm allocator to allocate in chunks of 64 MB

packages/apps/composer-app/src/main.tsx, packages/apps/halo-app/src/vault/iframe.ts, packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx, packages/apps/plugins/plugin-deck/src/components/LayoutSettings.tsx, packages/apps/plugins/plugin-deck/src/translations.ts, packages/apps/plugins/plugin-deck/src/types.ts, packages/apps/plugins/plugin-layout/src/LayoutPlugin.tsx, packages/apps/plugins/plugin-layout/src/components/LayoutSettings.tsx, packages/apps/plugins/plugin-layout/src/translations.ts, packages/apps/plugins/plugin-layout/src/types.ts, packages/apps/plugins/plugin-navtree/src/components/NavTreeContainer.tsx, packages/apps/plugins/plugin-settings/src/components/SettingsDialog.tsx, packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/apps/plugins/plugin-space/src/components/SpacePresence.tsx, packages/apps/plugins/plugin-stack/src/components/StackMain.tsx, packages/ui/react-ui-deck/src/components/Attention/AttentionGlyph.tsx, packages/ui/react-ui-stack/src/components/Section.tsx, packages/ui/react-ui-theme/src/styles/components/dialog.ts
This PR:
- Resolves #6820
- Resolves #6776
- Adds UI for toggling between Deck and conventional layouts
- Augments the attention glyph to become a button for closing open items.
- Fixes a z-index issue involving the notch and dialogs
- Suppresses navigation to SpaceMain
=> feat: Deck improvements, fixes

packages/core/echo/echo-db/src/host/documents-iterator.ts
=> fix: Fix stop loading absent objects in indexer

packages/sdk/client-services/src/packlets/spaces/data-space.ts
=> fix: Warn if database root already exists

packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx, packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx
=> fix: Complementary sidebar opening behavior

packages/apps/plugins/plugin-navtree/src/components/HaloButton.tsx, packages/sdk/shell/src/components/DeviceList/DeviceList.tsx, packages/sdk/shell/src/components/DeviceList/DeviceListItem.tsx, packages/sdk/shell/src/components/DeviceList/DeviceListProps.ts, packages/sdk/shell/src/panels/IdentityPanel/IdentityPanel.tsx
This PR
- resolves #6637.
- also refactors the device list to use the same signifier in the current device
https://github.com/dxos/dxos/assets/855039/61e9b260-3d7c-4d85-8a84-5ef9b4b06c06
=> fix: Halo button signals appropriate status color when intentionally disconnected

packages/apps/plugins/plugin-presenter/src/components/PresenterMain.tsx
This PR
- resolves #6872.
https://github.com/dxos/dxos/assets/855039/ff6ac46e-a553-4594-ad3d-17f07653362d
=> fix(plugin-presenter): Only emit close intent when in Deck

packages/core/functions/package.json, packages/core/functions/project.json, packages/core/functions/src/function/function-registry.test.ts, packages/core/functions/src/function/function-registry.ts, packages/core/functions/src/runtime/dev-server.test.ts, packages/core/functions/src/runtime/dev-server.ts, packages/core/functions/src/testing/functions-integration.test.ts, packages/core/functions/src/testing/index.ts, packages/core/functions/src/testing/manifest.ts, packages/core/functions/src/testing/plugin-init.ts, packages/core/functions/src/testing/setup.ts, packages/core/functions/src/testing/util.ts, packages/experimental/agent-functions/src/chain/model-invoker.ts, packages/experimental/agent-functions/src/chain/resources.ts, packages/experimental/agent-functions/src/functions/email-worker/handler.ts, packages/experimental/agent-functions/src/functions/email/handler.ts, packages/experimental/agent-functions/src/functions/gpt/handler.ts, packages/experimental/agent-functions/src/functions/gpt/processor.test.ts, packages/experimental/agent-functions/src/functions/gpt/processor.ts, packages/experimental/agent-functions/src/functions/gpt/resolvers/discord.ts, packages/experimental/agent-functions/src/functions/gpt/resolvers/type.ts, packages/experimental/agent-functions/src/functions/gpt/response.ts, packages/experimental/agent-functions/src/functions/gpt/testing/builder.ts, packages/experimental/agent-functions/src/functions/hello/handler.ts, packages/experimental/agent-functions/src/tests/functions/chess.test.ts, packages/experimental/agent-functions/src/tests/functions/gpt.test.ts, packages/experimental/agent-functions/src/tests/setup.ts, packages/experimental/agent-functions/src/tests/stub-invoker.ts, packages/experimental/agent-functions/src/tests/test-chain-builder.ts, packages/experimental/agent-functions/src/util.ts
* DevServer correctly manages functionsRegistry lifecycle
* Langchain classes are abstracted and gpt handler covered with tests
* Incorrect type (ChainType instead of ChainPromptType) fixed 
* Function call timeout (20s)
=> fix(functions): function test suite and minor fixes

packages/core/functions/package.json, packages/core/functions/project.json, packages/core/functions/src/function/function-registry.test.ts, packages/core/functions/src/function/function-registry.ts, packages/core/functions/src/runtime/dev-server.test.ts, packages/core/functions/src/runtime/dev-server.ts, packages/core/functions/src/testing/functions-integration.test.ts, packages/core/functions/src/testing/index.ts, packages/core/functions/src/testing/manifest.ts, packages/core/functions/src/testing/plugin-init.ts, packages/core/functions/src/testing/setup.ts, packages/core/functions/src/testing/util.ts, packages/experimental/agent-functions/src/chain/model-invoker.ts, packages/experimental/agent-functions/src/chain/resources.ts, packages/experimental/agent-functions/src/functions/email-worker/handler.ts, packages/experimental/agent-functions/src/functions/gpt/handler.ts, packages/experimental/agent-functions/src/functions/gpt/processor.test.ts, packages/experimental/agent-functions/src/functions/gpt/processor.ts, packages/experimental/agent-functions/src/functions/gpt/resolvers/discord.ts, packages/experimental/agent-functions/src/functions/gpt/resolvers/type.ts, packages/experimental/agent-functions/src/functions/gpt/response.ts, packages/experimental/agent-functions/src/functions/gpt/testing/builder.ts, packages/experimental/agent-functions/src/functions/hello/handler.ts, packages/experimental/agent-functions/src/tests/functions/chess.test.ts, packages/experimental/agent-functions/src/tests/functions/gpt.test.ts, packages/experimental/agent-functions/src/tests/setup.ts, packages/experimental/agent-functions/src/tests/stub-invoker.ts, packages/experimental/agent-functions/src/tests/test-chain-builder.ts
* DevServer correctly manages functionsRegistry lifecycle
* Langchain classes are abstracted and gpt handler covered with tests
* Incorrect type (ChainType instead of ChainPromptType) fixed
* Function call timeout (20s)
=> chore(functions): gpt functions tests and minor fixes 

docs/content/guide/echo/README.md
Close: https://github.com/dxos/dxos/issues/4338
Also:
- Fix two links that were pointing to the wrong pages
=> docs: describe allowed values in an ECHO object

packages/experimental/agent-functions/src/functions/email-worker/handler.ts
Fixed missing schema registration.
=> fix(functions): email-worker missing schema registration

packages/experimental/agent-functions/src/functions/chess/handler.ts
cherry-picking [the fix](https://github.com/dxos/dxos/pull/6899)
=> fix(functions): fix chess in labs

packages/core/functions/src/runtime/dev-server.test.ts, packages/core/functions/src/runtime/scheduler.test.ts, packages/core/functions/src/testing/setup.ts, packages/experimental/agent-functions/src/functions/chess/handler.ts, packages/experimental/agent-functions/src/tests/functions/gpt.test.ts
=> fix(functions): fixed the logic for determining whose turn is next

packages/core/functions/src/trigger/type/websocket-trigger.ts
Give up trying to reconnect if trigger was deactivated (context disposed).
=> fix(functions): fix websocket reconnects

packages/core/echo/echo-db/src/automerge/automerge-db.ts, packages/core/echo/echo-db/src/automerge/automerge-object-core.ts, packages/core/echo/echo-db/src/database.ts, packages/core/echo/echo-db/src/echo-handler/create.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.ts, packages/experimental/agent-functions/project.json
=> refactor: Do not do automatic reference lookup during decode/encode in AutomergeObjectCore

packages/common/util/src/throw-unhandled-error.ts, packages/core/echo/echo-db/src/automerge/automerge-object-core.ts, packages/core/echo/echo-db/src/echo-handler/create.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.ts, packages/core/echo/echo-db/src/echo-handler/echo-proxy-target.ts
=> refactor: Remove signal from automerge object core

tsconfig.json
=> chore: Do not include all files in root tsconfig

packages/sdk/client/src/devtools/devtools.ts
=> feat: Fetch button in console diagnostics

packages/apps/plugins/plugin-sketch/src/components/Sketch.tsx, packages/ui/react-ui-theme/src/styles/layers/index.css, packages/ui/react-ui-theme/src/styles/layers/tldraw.css
- Resolves https://github.com/dxos/dxos/issues/6572
=> chore(composer): Bring tldraw colors under our control

packages/apps/plugins/plugin-deck/package.json, packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx, packages/apps/plugins/plugin-deck/tsconfig.json, packages/ui/react-ui-navtree/package.json, packages/ui/react-ui-navtree/src/components/NavTreeItemHeading.tsx, packages/ui/react-ui-navtree/tsconfig.json, packages/ui/react-ui-text-tooltip/.eslintrc.js, packages/ui/react-ui-text-tooltip/LICENSE, packages/ui/react-ui-text-tooltip/README.md, packages/ui/react-ui-text-tooltip/package.json, packages/ui/react-ui-text-tooltip/project.json, packages/ui/react-ui-text-tooltip/src/components/TextTooltip.tsx, packages/ui/react-ui-text-tooltip/src/components/index.ts, packages/ui/react-ui-text-tooltip/src/index.ts, packages/ui/react-ui-text-tooltip/tsconfig.json, pnpm-lock.yaml, release-please-config.json
This PR:
- adds `TextTooltip`, an intermediate component which optimizes for some of the most common use-cases for `Tooltip`, also including logic for suppressing the tooltip if its content is not truncating 
- resolves #6106
https://github.com/dxos/dxos/assets/855039/687e1ed0-3c99-4046-80fb-5cd826461cd8
=> feat: TextTooltip

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.stories.tsx, packages/apps/plugins/plugin-table/src/components/TableArticle.tsx, packages/apps/plugins/plugin-table/src/components/TableMain.tsx, packages/apps/plugins/plugin-table/src/components/TableSection.tsx, packages/apps/testbench-app/src/components/ItemTable.tsx, packages/devtools/devtools/src/panels/client/TracingPanel/TracingPanel.tsx, packages/devtools/devtools/src/panels/mesh/SwarmPanel/SwarmPanel.tsx, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/schema/SchemaToTable.stories.tsx
- Resolves https://github.com/dxos/dxos/issues/6670
=> chore(tables): Upstream overflow-auto into `Viewport`

packages/apps/composer-app/src/shell.ts, packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/apps/plugins/plugin-space/src/util.tsx, packages/core/echo/echo-db/src/automerge/automerge-context.ts, packages/core/echo/echo-db/src/client/index-query-source-provider.ts, packages/core/echo/echo-db/src/hypergraph.ts, packages/sdk/client/src/devtools/devtools.ts
=> fix: Narrow down space order query

packages/devtools/devtools/src/components/performance/StatsPanel.tsx, packages/devtools/devtools/src/components/performance/panels/NetworkPanel.tsx, packages/devtools/devtools/src/components/performance/panels/index.ts, packages/devtools/devtools/src/hooks/useStats.ts
=> feat: Add connection info to network panel 

packages/apps/testbench-app/src/main.tsx, packages/common/log/src/platform/browser/index.ts, packages/devtools/devtools-extension/src/background.ts, packages/devtools/devtools/index.html, packages/devtools/devtools/package.json, packages/devtools/devtools/src/app/Devtools.tsx, packages/devtools/devtools/src/components/JsonView.tsx, packages/devtools/devtools/src/components/performance/StatsPanel.tsx, packages/devtools/devtools/src/containers/RootContainer.tsx, packages/devtools/devtools/src/panels/agent/DashboardPanel/DashboardPanel.tsx, packages/devtools/devtools/src/panels/client/TracingPanel/MetricsView.tsx, packages/devtools/devtools/tsconfig.json, packages/devtools/devtools/vite.config.ts, pnpm-lock.yaml
=> fix: Fix devtools-extension

packages/core/echo/echo-db/src/automerge/automerge-object-core.ts, packages/core/echo/echo-db/src/database.test.ts, packages/core/echo/echo-db/src/echo-handler/clone.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts, packages/core/echo/echo-db/src/query/filter.test.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-doc-loader.test.ts, packages/core/echo/echo-schema/package.json, packages/core/echo/echo-schema/src/handler/object.ts, pnpm-lock.yaml
closes https://github.com/dxos/dxos/issues/6955
=> refactor: Change ECHO ids to use Ulid

packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.ts
Fixes crash on reset where we do:
```ts
const props = db.add(create(Properties, {...}));
const folder = create(FolderType, {...});
props.folder = folder;
folder.objects.push(...);
```
=> fix(echo): fixed broken object linking

packages/apps/plugins/plugin-chess/src/ChessPlugin.tsx, packages/apps/plugins/plugin-debug/src/DebugPlugin.tsx, packages/apps/plugins/plugin-explorer/src/ExplorerPlugin.tsx, packages/apps/plugins/plugin-github/src/GithubPlugin.tsx, packages/apps/plugins/plugin-gpt/src/GptPlugin.tsx, packages/apps/plugins/plugin-grid/src/GridPlugin.tsx, packages/apps/plugins/plugin-inbox/src/InboxPlugin.tsx, packages/apps/plugins/plugin-kanban/src/KanbanPlugin.tsx, packages/apps/plugins/plugin-map/src/MapPlugin.tsx, packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/apps/plugins/plugin-outliner/src/OutlinerPlugin.tsx, packages/apps/plugins/plugin-script/src/ScriptPlugin.tsx, packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx, packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/apps/plugins/plugin-space/src/types.ts, packages/apps/plugins/plugin-space/src/util.tsx, packages/apps/plugins/plugin-table/src/TablePlugin.tsx, packages/apps/plugins/plugin-template/src/TemplatePlugin.tsx, packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx, packages/sdk/client/src/echo/util.ts
- Resolves https://github.com/dxos/dxos/issues/6969
Changes:
- **Change usages of `space.key` in graph**
- **Switch `SpacePlugin.enabled` to use space ids instead of keys**
=> chore(composer): Change usages of `space.key` -> `space.id` in composer graph identifiers

packages/apps/plugins/plugin-stack/src/components/StackMain.tsx
=> fix(plugin-stack): remove section from stack

packages/sdk/client-services/src/packlets/spaces/data-space-manager.ts
=> fix: Fix default space id

packages/apps/composer-app/vite.config.ts
cloudflare doesn't differentiate between preview envs so need another way to differentiate between deployments
=> chore: update vite config to check branch rather than env var

packages/sdk/client-services/src/packlets/identity/identity-service.ts
=> fix: Fix default space migration when encountering corrupted spaces 

packages/apps/composer-app/vite.config.ts
`getCurrentGitBranch` didn't work in Cloudflare
=> chore: tweak vite config for composer-app

packages/sdk/client-services/src/packlets/spaces/data-space.ts, packages/sdk/client-services/src/packlets/spaces/spaces-service.ts
=> fix: Filter immediate space updates

packages/sdk/client/src/echo/space-proxy.ts
closes https://github.com/dxos/dxos/issues/7080
=> fix: Increase timeout on space open

packages/core/echo/echo-db/src/host/echo-host.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator.ts, packages/sdk/client-services/src/packlets/spaces/data-space.ts
closes https://github.com/dxos/dxos/issues/7047
=> fix: Remove share policy workaround

packages/sdk/shell/src/components/DeviceList/DeviceList.tsx, packages/sdk/shell/src/panels/IdentityPanel/steps/IdentityActionChooser.tsx
This PR:
- resolves #7027.
https://github.com/dxos/dxos/assets/855039/eea762c9-ba3d-4104-bb38-8a5a913fa9c0
=> fix(shell): DeviceList overflow

packages/common/random-access-storage/src/common/file.ts
=> fix: Mute slow storage operation log

packages/apps/composer-app/src/help.ts, packages/apps/composer-app/src/playwright/app-manager.ts, packages/apps/composer-app/src/playwright/first-run.spec.ts, packages/apps/plugins/plugin-help/package.json, packages/apps/plugins/plugin-help/src/HelpPlugin.tsx, packages/apps/plugins/plugin-help/src/components/Tooltip/Tooltip.tsx, packages/apps/plugins/plugin-help/tsconfig.json, pnpm-lock.yaml
This PR:
- resolves #7107
https://github.com/dxos/dxos/assets/855039/fb7e692d-1e9f-426d-b539-1296d07924bf
=> feat(plugin-help): Enable joyride FRE

packages/apps/composer-app/src/playwright/first-run.spec.ts
https://playwright.dev/docs/api/class-locator#locator-is-visible
=> test(composer-app): use playwright expect to improve test robustness

packages/sdk/client-protocol/package.json, packages/sdk/client-protocol/src/space.ts, packages/sdk/client-protocol/tsconfig.json, packages/sdk/client/src/echo/space-proxy.ts, packages/sdk/client/src/tests/spaces.test.ts, pnpm-lock.yaml
=> feat: Add space.internal.getEpochs API

packages/ui/react-ui-editor/src/extensions/markdown/formatting.ts
- Resolves https://github.com/dxos/dxos/issues/6324
=> fix(authoring): `meta+i` should toggle *emphasis*

packages/core/echo/echo-db/src/host/documents-iterator.ts, packages/core/echo/echo-db/src/host/echo-host.ts, packages/core/echo/echo-db/src/query/query-service.ts, packages/core/echo/echo-db/src/query/query-state.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/echo-network-adapter.ts, packages/sdk/client-services/src/packlets/identity/identity-service.ts, packages/sdk/client-services/src/packlets/spaces/data-space.ts, packages/sdk/client-services/src/packlets/spaces/epoch-migrations.ts
=> refactor: Partially abstract automerge-repo inside EchoHost

packages/sdk/client-services/src/packlets/storage/profile-archive.ts, packages/sdk/client/src/devtools/devtools.ts
=> feat: Add profile import to browser devtools

packages/sdk/shell/src/components/AgentConfig.tsx, packages/sdk/shell/src/translations/locales/en-US.ts
This PR:
- resolves #6547.
https://github.com/dxos/dxos/assets/855039/c29a0ab7-9139-440b-a2db-34a1dd4598f2
=> feat(sdk): Add terms of service clickwrap to agent creation action

.github/workflows/staging.yml
https://github.com/pnpm/action-setup/issues/135 plus align with other workflows
=> ci: bump pnpm action version

packages/apps/templates/plugin-template/src/vite.config.ts.t.ts
stop overriding the process polyfill with vite define
=> fix(plugin-template): ensure composer runs

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx
⚠️ Do not merge if branch rc-20240703-7be0 gets merged to main
This PR
- resolves #6798.
=> fix(plugin-markdown): Document fills plank when toolbar is disabled

packages/common/crypto-names/src/names.test.ts
=> fix: Crypto names test

packages/core/echo/echo-db/src/core-db/automerge-context.ts, packages/core/echo/echo-db/src/core-db/core-database.ts, packages/core/echo/echo-pipeline/src/db-host/data-service.ts, packages/core/protocols/src/proto/dxos/echo/service.proto
=> feat: Add ability to query heads of all documents in a space

packages/core/echo/echo-db/src/core-db/automerge-context.ts, packages/core/echo/echo-db/src/core-db/core-database.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-repo.test.ts, packages/core/echo/echo-pipeline/src/db-host/data-service.ts, packages/core/mesh/teleport/src/muxing/muxer.ts, packages/core/protocols/src/proto/dxos/echo/service.proto
=> feat: Add ability to re-index document heads

packages/core/echo/echo-db/src/testing/integration.test.ts
=> test: Add references test

packages/common/tracing/src/diagnostic.ts, packages/common/tracing/src/diagnostics-channel.ts, packages/common/tracing/src/index.ts, packages/core/echo/echo-db/src/host/echo-host.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/devtools/devtools/src/components/performance/panels/DatabasePanel.tsx, packages/devtools/devtools/src/components/performance/panels/NetworkPanel.tsx, packages/devtools/devtools/src/hooks/useStats.ts, packages/sdk/client/src/devtools/devtools.ts
=> feat: Add worker loaded docs count to stats

packages/core/echo/echo-db/src/echo-handler/echo-handler.ts, packages/core/echo/echo-db/src/echo-handler/proxy.blueprint-test.ts, packages/core/echo/echo-schema/src/handler/untyped-handler.ts
=> fix: Object.keys subscribes to signal updates on reactive objects

packages/core/echo/echo-db/src/core-db/automerge-context.ts, packages/core/echo/echo-db/src/core-db/core-database.ts, packages/core/echo/echo-db/src/host/echo-host.ts, packages/core/echo/echo-db/src/testing/echo-test-builder.ts, packages/core/echo/echo-db/src/testing/integration.test.ts, packages/core/echo/echo-db/src/testing/test-replicator.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-repo.test.ts, packages/core/echo/echo-pipeline/src/db-host/data-service.ts, packages/core/echo/indexing/src/indexer.ts, packages/core/protocols/src/proto/dxos/echo/service.proto, packages/sdk/client-services/src/packlets/services/automerge-host.test.ts
=> feat: Add database methods to wait for replication & index updates

packages/apps/plugins/plugin-sketch/package.json, packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx, packages/apps/plugins/plugin-sketch/src/components/SketchComponent.tsx, packages/apps/plugins/plugin-sketch/src/components/SketchMain.tsx, packages/apps/plugins/plugin-sketch/src/components/custom/DottedGrid.tsx, packages/apps/plugins/plugin-sketch/src/components/custom/index.ts, packages/apps/plugins/plugin-sketch/tsconfig.json, pnpm-lock.yaml
- Resolves #7199
- May also resolve #7200, can't repro now
=> fix(sketch): Decouple state across sketch instances

packages/core/echo/echo-db/src/testing/echo-test-builder.ts, packages/core/echo/echo-db/src/testing/integration.test.ts, packages/core/echo/echo-db/src/testing/test-replicator.ts
related https://github.com/dxos/dxos/issues/7240
=> test: Workaround for stale query data issue

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx, packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.tsx, packages/ui/react-ui-editor/src/extensions/comments.ts
- Resolves https://github.com/dxos/dxos/issues/7210
=> chore(comments): No selection, no comment

packages/apps/composer-app/scripts/put_secrets.sh
- updated composer.space secrets in 1password with sentry release token and ipfs api secret
- updated script to align with manual changes that had been applied to secrets
=> chore: update put_secrets

packages/ui/react-ui-editor/src/extensions/comments.ts
The `scrollThreadIntoView` function was causing an infinite loop when selecting threads. This was due to unnecessary updates being triggered even when no actual changes were needed, leading to a cycle of re-renders and state updates.
Optimized the `scrollThreadIntoView` function to only trigger updates when absolutely necessary. Key changes include:
Added checks to determine if scrolling is actually needed.
Implemented a check to only update the selection if it's different from the current selection.
=> fix(comments): Infinite loop

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/db-host/documents-synchronizer.ts
closes https://github.com/dxos/dxos/issues/7285
=> fix: Make client Automerge sync non-blocking and fix `waitUntilHeadsReplicated` flushing

packages/core/echo/echo-db/src/hypergraph.ts, packages/core/echo/echo-db/src/query/filter.ts
A query was crashing trying to getMeta from object in filter predicate.
=> fix(echo): fixed incorrect filterMatch argument

packages/apps/plugins/plugin-deck/src/hooks/useNode.ts
`useNode` exception was not caught.
=> fix(composer): fixed waitForNode uncaught exception

packages/apps/plugins/plugin-space/src/util.tsx
resolves the following issue ![image](https://github.com/user-attachments/assets/9da67ffa-9d33-4379-89a8-44e3564c1fdb)
=> fix: filter unknown object types

packages/apps/plugins/plugin-space/src/util.tsx
- metadata object always exists, base condition on whether or not it has keys
- also include fallback label & icon for edge cases
=> fix: better unknown object filtering

packages/apps/composer-app/src/playwright/comments.spec.ts, packages/apps/plugins/plugin-thread/src/components/MessageContainer.tsx
- Resolves https://github.com/dxos/dxos/issues/5462
This also fixes an issue where comment edits were not being persisted.
=> chore(comments): Click to edit

packages/apps/plugins/plugin-help/src/components/HelpContextProvider/HelpContextProvider.tsx
The welcome plugin starts the joyride now but when it starts it the app hasn't rendered yet. This deals with that race condition by having the help context wait for the initial step to be available before setting running to true.
=> chore(plugin-help): make sure that joyride starts even if the target isn't immediately available

packages/apps/plugins/plugin-observability/src/ObservabilityPlugin.tsx
it was not being rendered previously because of the splash screen
=> chore: send privacy notice after identity is created

packages/ui/react-ui-editor/package.json, packages/ui/react-ui-editor/src/extensions/markdown/linkPaste.test.ts, packages/ui/react-ui-editor/src/extensions/markdown/linkPaste.ts, pnpm-lock.yaml
- Related https://github.com/dxos/dxos/issues/7331 (sorta).
We should consider logging an issue with the upstream library.
`¯\_(ツ)_/¯`
=> fix(authoring): Link pasting

packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/apps/plugins/plugin-space/src/components/LimitDialog.tsx, packages/apps/plugins/plugin-space/src/components/index.ts, packages/apps/plugins/plugin-space/src/translations.ts, packages/sdk/client/src/echo/util.ts
=> feat(plugin-space): add space limit dialog

packages/apps/plugins/plugin-space/src/components/MenuFooter.tsx
=> fix(plugin-space): fallback personal space name wasn't being used

packages/core/echo/automerge/src/automerge/next.ts, packages/sdk/client/src/client/client.ts, packages/sdk/client/src/services/local-client-services.ts
Pulled from [dm/echo-edge-replication](https://github.com/dxos/dxos/tree/dm/echo-edge-replication).
=> chore: fixes for client use in edge repo

packages/apps/plugins/plugin-debug/src/DebugPlugin.tsx, pnpm-lock.yaml
also rollback pnpm-lock.yaml changes which looked odd (some packages were downgraded while others were upgraded)
=> chore: fix debug plugin catch-all for article role

packages/apps/plugins/plugin-deck/package.json, packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx, packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx, packages/apps/plugins/plugin-deck/src/hooks/useNodeFromSlug.ts, packages/apps/plugins/plugin-deck/src/util/apply-active-adjustment.ts, packages/apps/plugins/plugin-deck/tsconfig.json, packages/apps/plugins/plugin-navtree/src/components/NavTreeFooter.tsx, packages/sdk/app-framework/src/plugins/common/navigation.ts, packages/ui/react-ui-deck/src/components/Deck/Deck.tsx, packages/ui/react-ui-deck/src/components/PlankHeading/PlankHeading.tsx, pnpm-lock.yaml
- Resolves https://github.com/dxos/dxos/issues/7347
=> feat(deck): Solo planks

packages/apps/plugins/plugin-sketch/src/hooks/useStoreAdapter.tsx
=> fix(plugin-sketch): force render when store updates

packages/apps/composer-app/src/playwright/collections.spec.ts, packages/ui/react-ui-stack/src/components/Stack.stories.tsx, packages/ui/react-ui-stack/src/playwright/smoke.spec.ts, packages/ui/react-ui-stack/src/testing/stack-manager.ts, packages/ui/react-ui-theme/src/config/colors.ts
This PR:
- does what it says on the tin.
=> test: Fix react-ui-stack e2e, a composer test for FF in CI, revert minor color change

packages/common/util/src/chunk-array.ts, packages/common/util/src/index.ts, packages/core/echo/echo-db/src/core-db/core-database.ts
=> feat: Add unlinkObjects method

packages/apps/types/src/schema/address-book.ts, packages/apps/types/src/schema/tree.ts, packages/core/echo/echo-db/src/query/filter.ts, packages/core/echo/echo-db/src/runtime-schema-registry.ts, packages/core/echo/echo-db/src/testing/schema.ts, packages/core/echo/echo-schema/src/annotations.ts, packages/core/echo/echo-schema/src/getter.ts, packages/core/echo/echo-schema/src/handler/object.ts, packages/core/echo/echo-schema/src/ref-annotation.ts, packages/core/echo/echo-schema/src/typed-object-class.ts, packages/core/echo/echo-schema/src/types.ts, packages/sdk/client/src/testing/data.ts
=> feat: Include encoded data types in schema

packages/apps/plugins/plugin-navtree/src/NavTreePlugin.tsx, packages/apps/plugins/plugin-navtree/src/components/CommandsDialog.tsx, packages/apps/plugins/plugin-space/src/SpacePlugin.tsx, packages/sdk/app-graph/src/graph.ts
Resolves #7442
this was debt from updated graph api, the nested create actions weren't finding the related node to pass to the action callback
=> fix: add to space from command dialog + closing plank on delete

packages/sdk/client-services/src/packlets/invitations/invitations-handler.test.ts
changes were merged in [this branch](https://github.com/dxos/dxos/pull/7396)
=> chore: fix tests after replicator binding code changes

packages/sdk/shell/src/components/AuthCode.tsx
This PR:
- resolves #7471
https://github.com/user-attachments/assets/35038d2d-50d0-47ec-b439-781cd0bc3019
=> fix(shell): Auth code copying

packages/apps/plugins/plugin-markdown/src/components/DocumentEditor.tsx
=> fix(plugin-markdown): comments shifting on typing

packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/apps/plugins/plugin-markdown/src/components/DocumentEditor.tsx, packages/apps/plugins/plugin-markdown/src/util.tsx, packages/apps/types/src/schema/document.ts
=> fix(plugin-markdown): typing latency on unnamed documents

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx
=> chore: fix EditorMain rte

packages/apps/plugins/plugin-debug/package.json, packages/apps/plugins/plugin-debug/src/components/Wireframe.tsx, packages/apps/plugins/plugin-debug/tsconfig.json, packages/apps/plugins/plugin-settings/src/components/SettingsDialog.tsx, packages/apps/plugins/plugin-sheet/package.json, packages/apps/plugins/plugin-sheet/src/components/Grid/Grid.stories.tsx, packages/apps/plugins/plugin-sheet/src/components/Grid/Grid.tsx, packages/apps/plugins/plugin-sheet/src/components/SheetArticle.tsx, packages/apps/plugins/plugin-sheet/src/components/SheetMain.tsx, packages/apps/plugins/plugin-sheet/src/components/SheetSection.tsx, packages/apps/plugins/plugin-sheet/src/model/model.ts, packages/apps/plugins/plugin-sheet/tsconfig.json, pnpm-lock.yaml
- Fixes ECHO reactivity for column/row sizes and ordering.
- Fixes Attention.
=> feat: Make sheet reactive

packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx, packages/apps/plugins/plugin-deck/src/util/index.ts, packages/apps/plugins/plugin-deck/src/util/layout-parts.ts
Applies the same logic in CLOSE as OPEN was using.
=> fix(plugin-deck): handle deletion better in solo mode

.github/workflows/publish-all.yml, .github/workflows/scripts/publish-apps.sh
- **chore: only bundle apps which are being published (#7534)**
- **ci: update publish-apps.sh**
- **ci: bundle after env vars are set**
=> fix(composer-app): env var configuration

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.stories.tsx, packages/ui/react-ui-table/src/components/Cell/Cell.tsx, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx
- Resolve: https://github.com/dxos/dxos/issues/7539
https://github.com/user-attachments/assets/a312f176-a712-473d-9631-ee5e3de93661
=> feat(tables): Fast data entry

packages/core/echo/echo-db/src/client/echo-client.ts, packages/core/echo/echo-db/src/client/repo-proxy.test.ts, packages/core/echo/echo-db/src/client/repo-proxy.ts, packages/core/echo/echo-db/src/core-db/automerge-context.ts, packages/core/echo/echo-db/src/core-db/automerge-doc-loader.test.ts, packages/core/echo/echo-db/src/core-db/core-database.ts, packages/core/echo/echo-db/src/core-db/core-databasse.test.ts, packages/core/echo/echo-db/src/proxy-db/database.ts, packages/core/protocols/src/proto/dxos/echo/service.proto, packages/devtools/devtools/src/panels/echo/AutomergePanel/AutomergePanel.tsx, packages/sdk/migrations/src/migration-builder.ts
=> refactor: Separate RepoProxy for each database keyed by space id

packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts, packages/ui/react-ui-editor/src/hooks/TextEditor.stories.tsx, packages/ui/react-ui-theme/src/config/semanticColors.ts, packages/ui/react-ui-theme/src/config/tailwind.ts
=> fix: editor list hanging indent

packages/core/echo/echo-db/src/core-db/core-database.ts
=> refactor: DB update propagation logic

packages/apps/plugins/plugin-deck/src/util/overscroll.ts, packages/ui/react-ui-deck/src/components/Deck/Deck.tsx
- Resolves: https://github.com/dxos/dxos/issues/7582
=> fix(deck): Overscroll centering

packages/sdk/app-graph/src/graph-builder.ts
A few instances of runtime errors have occured where it seems likely the error is coming from a graph extension but it's not clear which one, this should help zero in on those errors and also prevent them from breaking the app.
=> fix(app-graph): catch errors thrown in graph builder extensions and log them

packages/ui/react-ui-deck/src/components/Deck/Deck.tsx
This PR prevents `Deck.Root`’s `scrollTop` from being set to a value other than `0` by any downstream callers.
`overflow-y-clip` is added to `Deck.Root` to signal this intention, even though it’s unsupported.
https://github.com/user-attachments/assets/4cfe0411-bbaf-4401-9347-0dfc25769c65
=> fix: Prevent `scrollIntoView` from scrolling elements that should not be scrolled

packages/core/mesh/messaging/src/signal-client/signal-client.test.ts
=> fix: Fix flaky messaging test

packages/core/echo/echo-pipeline/src/space/space-protocol.ts, packages/core/mesh/edge-client/src/client.ts, packages/core/mesh/network-manager/src/connection-log.ts, packages/core/mesh/network-manager/src/network-manager.ts, packages/core/mesh/network-manager/src/swarm/connection.ts, packages/core/mesh/network-manager/src/swarm/peer.ts, packages/core/mesh/network-manager/src/swarm/swarm-mapper.ts, packages/core/mesh/network-manager/src/swarm/swarm.test.ts, packages/core/mesh/network-manager/src/swarm/swarm.ts, packages/sdk/client-services/src/packlets/invitations/invitations-handler.ts, packages/sdk/client-services/src/packlets/services/service-context.ts, packages/sdk/client-services/src/packlets/services/service-host.ts
TODOs https://github.com/dxos/dxos/issues/7614
=> fix: Fix EDGE client reconnect race condition

packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
- Resolves: https://github.com/dxos/dxos/issues/7632
=> fix(comments): Restore click to view thread

packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
- Resolves https://github.com/dxos/dxos/issues/7636
https://github.com/user-attachments/assets/ef97bf96-529f-4d1a-8887-8916387ca6d5
=> fix(comments): Bidirectional thread highlighting

packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
- Resolves: https://github.com/dxos/dxos/issues/7605
=> fix(authoring): Toolbar should overflow at narrow widths

packages/plugins/experimental/plugin-script/src/components/ScriptEditor.tsx, packages/plugins/experimental/plugin-script/src/components/TypescriptEditor.tsx, packages/plugins/plugin-deck/src/DeckPlugin.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/Plank.tsx, packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx, packages/sdk/app-framework/src/plugins/common/navigation.ts, packages/ui/react-ui-editor/src/defaults.ts, packages/ui/react-ui-editor/src/index.ts, packages/ui/react-ui-editor/src/styles/theme.ts
- Temp. disable scroll into view
- Fix margin/gutter/scrolling for script editor
- Fix monospace for script editor
=> fix: Deck/solo section.

packages/plugins/plugin-space/src/SpacePlugin.tsx, packages/plugins/plugin-space/src/components/SpacePresence.tsx, packages/ui/react-ui-attention/src/components/AttentionGlyph.tsx
=> fix(react-ui-attention): Remove close action, fix colors

packages/plugins/experimental/plugin-excalidraw/src/SketchPlugin.tsx, packages/plugins/experimental/plugin-map/src/MapPlugin.tsx, packages/plugins/experimental/plugin-outliner/src/OutlinerPlugin.tsx, packages/plugins/experimental/plugin-script/src/ScriptPlugin.tsx, packages/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/plugins/plugin-sheet/src/SheetPlugin.tsx, packages/plugins/plugin-sketch/src/SketchPlugin.tsx, packages/plugins/plugin-table/src/TablePlugin.tsx
=> fix(stack): Stack creator intent might be an array

packages/plugins/experimental/plugin-script/src/edge/functions.ts, packages/plugins/plugin-sheet/src/components/ComputeGraph/async-function.ts, packages/sdk/client/src/devtools/devtools.ts
=> chore: Point composer functions to edge-main

packages/plugins/plugin-space/src/SpacePlugin.tsx
=> fix(plugin-space): incorrect names for graph serializer

packages/ui/react-ui-editor/src/styles/tokens.ts, packages/ui/react-ui-theme/src/config/index.ts, packages/ui/react-ui-theme/src/config/tailwind.ts, packages/ui/react-ui-theme/src/config/tokens.ts, packages/ui/react-ui-theme/src/index.ts, packages/ui/react-ui-theme/src/plugin.ts, packages/ui/react-ui-theme/src/styles/fragments/hue.ts, packages/ui/react-ui-theme/src/types.ts
Split from previously reviewed pr: burdon/map-tweaks
=> fix: react-ui-theme tweaks

packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/Plank.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/StatusBar.tsx, packages/plugins/plugin-deck/src/hooks/index.ts, packages/plugins/plugin-deck/src/hooks/useMainSize.ts, packages/ui/react-ui-deck/src/components/Deck/Deck.tsx, packages/ui/react-ui-theme/src/styles/components/main.ts
This PR:
- ⚠️ is mutually exclusive with #7692
- resolves #7514.
https://github.com/user-attachments/assets/10c7d1af-bfbb-4f59-87a1-bd329ede0830
=> fix(plugin-deck): Plank focus and scroll position, variation 2

packages/plugins/plugin-help/src/HelpPlugin.tsx, packages/plugins/plugin-help/src/components/Shortcuts/ShortcutsDialog.tsx
- change shortcut to avoid conflicts with comments shortcut
- fix dialog rendering
=> fix: shortcuts dialog

packages/core/mesh/edge-client/package.json, pnpm-lock.yaml
=> chore: Fix edge-client deps

packages/devtools/cli-composer/project.json, tools/vite-plugin-icons/package.json, tools/vite-plugin-icons/project.json, tools/vite-plugin-icons/tsconfig.json
=> build: Cleanup vite-plugin-icons config

packages/apps/composer-app/dx.yml, packages/core/echo/echo-db/src/core-db/core-database-query-context.ts, packages/core/echo/echo-db/src/core-db/core-database.ts, packages/core/echo/echo-db/src/core-db/core-databasse.test.ts, packages/core/echo/echo-db/src/core-db/crud-api.ts, packages/core/echo/echo-db/src/core-db/object-core.ts, packages/core/echo/echo-db/src/query/filter.test.ts, packages/core/echo/echo-db/src/query/filter.ts, packages/core/echo/echo-db/src/query/query.ts, packages/core/echo/echo-db/src/testing/echo-test-builder.ts, packages/core/echo/echo-schema/src/types.ts
=> feat: CRUD api improvements

docs/content/guide/echo/react/README.md, docs/content/guide/echo/react/mutations.md, docs/content/guide/echo/react/queries.md, docs/content/guide/echo/tutorial.md, docs/content/guide/echo/typescript/queries.md, docs/content/guide/echo/typescript/subscriptions.md
Not sure how so many of these ended up one short.
=> docs: fix incorrect code snippet highlight locations

packages/plugins/experimental/plugin-script/src/components/ScriptEditor.tsx
=> fix: Include functions/ fragment in copied URL

packages/plugins/experimental/plugin-script/src/components/ScriptEditor.tsx
=> fix: Function URL copy

packages/apps/composer-app/dx-local.yml, packages/plugins/experimental/plugin-script/src/ScriptPlugin.tsx, packages/plugins/experimental/plugin-script/src/components/ScriptEditor.tsx
=> fix: Update default script example & fix url copy

packages/plugins/plugin-attention/src/AttentionPlugin.tsx
=> feat: Expose attention state in console global

packages/core/echo/echo-db/src/core-db/core-databasse.test.ts
=> test: Extend crud test

packages/ui/react-ui-editor/src/extensions/folding.tsx, packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts, packages/ui/react-ui-editor/src/styles/theme.ts, pnpm-lock.yaml
https://github.com/user-attachments/assets/8fc73d88-4fb9-4179-863c-445d7fcf9397
=> fix: Fix editor code folding

packages/plugins/experimental/plugin-script/src/components/TypescriptEditor.tsx, packages/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx, packages/plugins/plugin-markdown/src/components/Toolbar.stories.tsx, packages/plugins/plugin-mermaid/src/extensions/mermaid.stories.tsx, packages/ui/react-ui-editor/src/InputMode.stories.tsx, packages/ui/react-ui-editor/src/TextEditor.stories.tsx, packages/ui/react-ui-editor/src/extensions/factories.ts, packages/ui/react-ui-editor/src/extensions/folding.tsx, packages/ui/react-ui-editor/src/extensions/markdown/bundle.ts, packages/ui/react-ui-editor/src/extensions/util/react.tsx, packages/ui/react-ui-editor/src/styles/theme.ts, packages/ui/react-ui-stack/src/testing/EditorContent.tsx
- line number fix
- move syntax highlighting into theme
=> fix: editor styles

.idea/compiler.xml, packages/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/ui/react-ui-editor/src/defaults.ts, packages/ui/react-ui-stack/src/components/Section.tsx, packages/ui/react-ui-theme/src/styles/components/dialog.ts, packages/ui/react-ui-theme/src/styles/layers/attention.css
https://github.com/user-attachments/assets/f35e1517-20a2-46bd-a351-2170eb90eac6
=> fix: attention styles

packages/ui/react-ui-editor/src/defaults.ts, packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts
https://github.com/user-attachments/assets/1733739c-fa20-49c8-86a3-527384879dbe
=> fix: Task list checkbox

packages/core/functions/src/trigger/type/websocket-trigger.ts, packages/plugins/experimental/plugin-function/src/components/TriggerEditor.tsx
* Websocket trigger works in browser.
* Fix for trigger reload.
=> feat(functions): make ws trigger work in browser

packages/sdk/react-client/src/echo/useQuery.ts
=> fix: useQuery filter deps

packages/apps/testbench-app/dx.yml, packages/apps/testbench-app/src/components/AppToolbar.tsx, packages/apps/testbench-app/src/components/Main.tsx, packages/apps/testbench-app/src/main.tsx, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/devtools/devtools/src/app/Devtools.tsx, packages/devtools/devtools/src/hooks/useRoutes.tsx, packages/devtools/devtools/src/hooks/useSections.tsx, packages/devtools/devtools/src/panels/edge/EdgeDashboardPanel/EdgeDashboardPanel.tsx, packages/devtools/devtools/src/panels/edge/EdgeDashboardPanel/index.ts, packages/devtools/devtools/src/panels/edge/index.ts, packages/devtools/devtools/src/panels/index.ts
=> feat: Fix collection sync & add edge panel to devtools

packages/apps/composer-app/vite.config.ts
=> build: Add source map plugin to worker config in composer

packages/plugins/plugin-deck/src/DeckPlugin.tsx, packages/plugins/plugin-navtree/src/components/NavTreeContainer.tsx, packages/plugins/plugin-stack/src/components/StackMain.tsx, packages/ui/react-ui-stack/src/components/Section.tsx
improves performance for resizing planks when stacks are open by
removing the global mosaic root for the mean time
=> refactor: multiple mosaic roots

packages/apps/composer-app/src/constants.ts, packages/plugins/experimental/plugin-script/src/ScriptPlugin.tsx, packages/ui/react-ui-editor/src/styles/theme.ts
- fix formatting in initial content
- fix script plugin icon
- fix gutter border when folding turned on in light mode
=> chore: cleanup

packages/sdk/client-services/src/packlets/identity/authenticator.ts, packages/sdk/client-services/src/packlets/spaces/data-space.ts, packages/sdk/client-services/src/packlets/spaces/edge-feed-replicator.ts
=> chore: Add logs 

docs/content/guide/dxos-ui/snippets/vite-config.ts, docs/package.json, docs/src/config/api-sidebar-hope.ts, docs/src/plugins/showcase-plugin.ts, docs/src/plugins/telemetry/telemetry-plugin.ts, docs/vuepress.config.ts, pnpm-lock.yaml, tools/apidoc/package.json, tools/apidoc/src/apiDocDirective.ts, tools/apidoc/src/remarkDocumentation.ts
=> fix: Docs deps

packages/apps/testbench-app/src/components/ItemTable.tsx, packages/devtools/devtools/src/panels/echo/SpaceInfoPanel/SpaceInfoPanel.tsx, packages/sdk/client-services/src/packlets/spaces/data-space-manager.ts
=> feat: Reactively update edge replication setting

packages/core/mesh/edge-client/src/edge-client.ts
=> feat: Enable router auth

packages/core/echo/echo-pipeline/src/edge/echo-edge-replicator.test.ts, packages/core/echo/echo-pipeline/src/edge/echo-edge-replicator.ts, packages/core/mesh/edge-client/src/edge-client.ts, packages/core/mesh/edge-client/src/testing/test-utils.ts
=> fix: Race conditions in EdgeClient & EchoEdgeReplicator

packages/plugins/plugin-navtree/src/components/NavTreeContainer.tsx, packages/plugins/plugin-table/project.json, packages/ui/react-ui-editor/src/TextEditor.stories.tsx, packages/ui/react-ui-editor/src/hooks/useTextEditor.ts, packages/ui/react-ui-navtree/src/components/NavTreeItemAction.tsx, packages/ui/react-ui-navtree/src/components/NavTreeItemHeading.tsx
=> fix: prevent invalid initial selection.

packages/core/echo/echo-pipeline/src/metadata/metadata-store.ts
=> fix: Public key comparison in metadata store

packages/plugins/plugin-markdown/src/components/MarkdownContainer.tsx, packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx, packages/plugins/plugin-markdown/src/components/index.ts
Fixes inner scrollbar issue for editor sections.
=> fix: Markdown editor scrolling bug

packages/apps/composer-app/dx-local.yml, packages/common/keys/src/dxn.ts, packages/core/echo/echo-db/src/core-db/core-database-query-context.ts, packages/core/echo/echo-db/src/echo-handler/util.ts, packages/core/echo/echo-db/src/query/filter.ts, packages/core/echo/echo-db/src/testing/echo-test-builder.ts, packages/core/echo/echo-db/src/testing/integration.test.ts, packages/core/echo/echo-pipeline/src/db-host/query-state.ts, packages/core/echo/indexing/src/index-schema.ts
=> fix: Dynamic schema queries

packages/sdk/observability/src/observability.ts
=> chore: Add observability session tag

packages/apps/composer-app/src/plugins/welcome/components/WelcomeScreen.tsx
=> fix: unauthed space join flow

packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx, packages/plugins/plugin-sheet/src/components/GridSheet/util.ts, packages/plugins/plugin-table/src/components/Table/ColumnActionsMenu.tsx, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/react-ui-grid/package.json, packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx, packages/ui/react-ui-grid/src/Grid/Grid.stories.tsx, pnpm-lock.yaml
This PR:
- resolves #7955
- resolves #7956
- resolves #7955
https://github.com/user-attachments/assets/26d5a7bc-9a8f-4898-a4ba-c4748de947cd
https://github.com/user-attachments/assets/aa917b23-4392-47a0-877c-45551cbd0cef
https://github.com/user-attachments/assets/283682f7-8f76-4b4c-9002-2b81b58e9c6b
=> feat: Grid & Sheet selection interactivity & model integration increment

packages/core/echo/echo-db/src/core-db/core-databasse.test.ts
=> test: Test dynamic schema with CRUD api

packages/apps/testbench-app/src/components/Main.tsx, packages/sdk/client-services/src/packlets/services/service-context.ts
* Don't try joining a space before identity is created.
* Better error message.
=> fix: testbench join space without identity

packages/apps/testbench-app/src/components/Main.tsx
Fixes space initialization race with the default space selection in testbench.
=> fix(testbench): fixed broken default state

packages/common/local-storage/package.json, packages/common/local-storage/project.json, packages/common/local-storage/src/index.ts, packages/common/local-storage/src/local-store.ts, packages/common/local-storage/src/store.test.ts, packages/common/local-storage/src/store.ts, packages/common/local-storage/src/testing.ts, packages/common/local-storage/vitest.config.ts, pnpm-lock.yaml
=> feat: Replace LocalStore with effect based SettingsStore

packages/experimental/script-toolbox/src/transform-server-sent-events.ts
=> fix: SSE transformer end-of-stream handling

packages/plugins/experimental/plugin-automation/src/components/index.ts, packages/plugins/experimental/plugin-script/src/ScriptPlugin.tsx, packages/plugins/experimental/plugin-script/src/components/AutomationPanel/AutomationPanel.tsx, packages/plugins/experimental/plugin-script/src/components/index.ts, packages/plugins/plugin-navtree/src/components/NavTree.tsx, packages/plugins/plugin-navtree/src/components/NavTreeContainer.tsx, packages/sdk/schema/src/types/annotations.ts, packages/ui/react-ui-list/src/components/Tree/Tree.tsx, packages/ui/react-ui-list/src/components/Tree/TreeItem.tsx, packages/ui/react-ui-list/src/components/Tree/index.ts
=> chore: NavTree generics

packages/sdk/client-services/src/packlets/invitations/invitation-state.ts
=> chore: Add log on invitation success

packages/plugins/plugin-sheet/src/components/GridSheet/util.ts, packages/plugins/plugin-sheet/src/components/Toolbar/Toolbar.tsx
This PR:
- resolves #8017 
- enables commenting on ranges
https://github.com/user-attachments/assets/9b4e734d-03b5-4d12-a82c-fcb9ca2d7899
=> fix(plugin-sheet): Style empty cells & allow commenting on ranges

.github/workflows/check.yml
appears to be causing failures, skip for now
=> ci: skip coverage

.github/workflows/check.yml, packages/apps/composer-app/index.html, packages/devtools/cli/package.json, packages/devtools/cli/scripts/patch_dx_environment.sh, packages/sdk/observability/src/observability.ts
- disable flaky gh action check
- fix meta tag warning
- guard observability from missing document in workers
- cli prepublish/prepack fixes
=> chore: misc cleanup

packages/devtools/cli/bin/dx.js, packages/sdk/observability/src/observability.ts
=> chore: try fix window reference error

packages/plugins/plugin-table/src/TablePlugin.tsx
=> fix: Register view type

packages/plugins/plugin-thread/src/components/CommentContainer.tsx, packages/plugins/plugin-thread/src/components/MessageContainer.tsx
This PR resolves issues with comment and message action buttons.
https://github.com/user-attachments/assets/c791add2-cf51-4840-b513-818da18643eb
=> fix(plugin-thread): Button design debt

packages/plugins/plugin-sheet/src/SheetPlugin.tsx, packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx, packages/plugins/plugin-sheet/src/components/GridSheet/util.ts, packages/plugins/plugin-sheet/src/defs/util.ts, packages/plugins/plugin-sheet/src/model/sheet-model.ts, packages/plugins/plugin-sheet/src/translations.ts, packages/plugins/plugin-sheet/src/types.ts, packages/ui/react-ui-grid/src/Grid/Grid.tsx
This PR:
- resolves #8107
- resolves #8109
https://github.com/user-attachments/assets/9cb4fcde-0ca3-485a-b833-4ea5a01b32b5
https://github.com/user-attachments/assets/16b77a9f-6c4e-432c-a8a1-eb60fd3f2c66
https://github.com/user-attachments/assets/2727ff9c-0976-4b17-bbc5-c2be4dfb5d9d
=> feat(plugin-sheet): Restore axis dropping

packages/plugins/plugin-deck/src/components/DeckLayout/Plank.tsx, packages/plugins/plugin-graph/package.json, packages/plugins/plugin-graph/src/GraphPlugin.tsx, packages/plugins/plugin-graph/src/meta.ts, packages/sdk/app-graph/src/graph-builder.test.ts, packages/sdk/app-graph/src/graph-builder.ts, packages/sdk/app-graph/src/graph.test.ts, packages/sdk/app-graph/src/graph.ts, pnpm-lock.yaml
- allow app graph to be serialized and restored
- hook up to localstorage in the graph plugin
Before:
https://github.com/user-attachments/assets/87b5e4a2-cdb9-4101-b5dd-ddf8317017d2
After:
https://github.com/user-attachments/assets/33175368-369a-46b0-850e-d2c288e8f6af
=> feat(app-graph): pickle

packages/apps/composer-app/src/plugins.tsx, packages/plugins/plugin-navtree/src/NavTreePlugin.tsx
=> feat(plugin-navtree): open branches when direct linked to an object

packages/plugins/experimental/plugin-automation/src/meta.ts, packages/plugins/experimental/plugin-excalidraw/src/meta.ts, packages/plugins/experimental/plugin-explorer/src/meta.ts, packages/plugins/experimental/plugin-github/src/meta.ts, packages/plugins/experimental/plugin-grid/src/meta.ts, packages/plugins/experimental/plugin-inbox/src/meta.ts, packages/plugins/experimental/plugin-ipfs/src/meta.ts, packages/plugins/experimental/plugin-kanban/src/meta.ts, packages/plugins/experimental/plugin-map/src/meta.ts, packages/plugins/experimental/plugin-outliner/src/meta.ts, packages/plugins/experimental/plugin-script/src/meta.ts, packages/plugins/experimental/plugin-search/src/meta.ts, packages/plugins/experimental/plugin-template/src/meta.ts, packages/plugins/experimental/plugin-wnfs/project.json, packages/plugins/experimental/plugin-wnfs/src/meta.ts, packages/plugins/plugin-chess/src/meta.ts, packages/plugins/plugin-debug/src/meta.ts, packages/plugins/plugin-files/src/meta.ts, packages/plugins/plugin-markdown/src/meta.ts, packages/plugins/plugin-mermaid/src/meta.ts, packages/plugins/plugin-presenter/src/meta.ts, packages/plugins/plugin-registry/src/components/PluginList.tsx, packages/plugins/plugin-registry/src/translations.ts, packages/plugins/plugin-sheet/src/meta.ts, packages/plugins/plugin-sketch/src/meta.ts, packages/plugins/plugin-table/src/meta.ts, packages/plugins/plugin-thread/src/meta.ts, packages/sdk/app-framework/src/plugins/plugin-host/plugin.ts, tsconfig.paths.json
=> chore: add plugin source links

.circleci/config.yml, packages/apps/composer-app/project.json, packages/apps/composer-app/src/plugins/welcome/WelcomePlugin.tsx
fails to fetch when offline but that shouldn't prevent composer usage
=> fix(plugin-welcome): catch fetch profile

packages/ui/lit-grid/src/dx-grid-axis-resize-handle.ts
This PR:
- resolves #8175.
https://github.com/user-attachments/assets/84841421-472e-4ce4-8f1f-50cc5cb8c361
=> fix(lit-grid): Restore `data-dx-grid-action` to resize handle to fix pointer interactivity issue

packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx, packages/plugins/plugin-sheet/src/components/GridSheet/util.ts, packages/ui/lit-grid/src/defs.ts, packages/ui/lit-grid/src/dx-grid.lit-stories.ts, packages/ui/lit-grid/src/dx-grid.pcss, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/lit-grid/src/index.ts, packages/ui/lit-grid/src/util.ts, packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx, packages/ui/react-ui-grid/src/index.ts
30px results in natural centering of the text.
=> chore: Change grid row size and sheet label formatting

packages/ui/react-ui-data/src/components/FieldEditor/FieldEditor.tsx, packages/ui/react-ui-table/src/components/Table/ColumnSettings.tsx
- Resolves #8227 
- Fixes ref format issue in column settings
=> fix(tables): Column settings issues

packages/plugins/plugin-space/src/SpacePlugin.tsx, packages/plugins/plugin-space/src/meta.ts, packages/plugins/plugin-space/src/translations.ts, packages/plugins/plugin-space/src/util.tsx, packages/plugins/plugin-stack/src/components/StackMain.tsx, packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/ui/react-ui-data/src/util/field.ts, packages/ui/react-ui-table/src/components/Table/RowActionsMenu.tsx, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/hooks/useTableModel.ts, packages/ui/react-ui-table/src/model/selection-model.ts, packages/ui/react-ui-table/src/model/table-model.test.ts, packages/ui/react-ui-table/src/model/table-model.ts, packages/ui/react-ui-table/src/translations.ts, packages/ui/react-ui-table/src/util/table-controls.ts
- Resolves #8027 
- Supports bulk deletion
- Selection is durable through sort and row order changes, insertions and deletions etc.
https://github.com/user-attachments/assets/b279a2cf-a49f-4953-9e9e-b1a787f6f0f9
=> feat(tables): Selection

packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/Plank.tsx, packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx, packages/plugins/plugin-sheet/src/components/FunctionEditor/FunctionEditor.tsx, packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx, packages/plugins/plugin-sheet/src/components/SheetContainer/SheetContainer.tsx, packages/plugins/plugin-stack/src/components/StackMain.tsx, packages/plugins/plugin-stack/src/components/StackSection.tsx, packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx, packages/ui/react-ui-grid/src/CellEditor/GridCellEditor.tsx, packages/ui/react-ui-stack/src/components/StackItemContent.tsx, packages/ui/react-ui-stack/src/testing/EditorContent.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/Toolbar/Toolbar.tsx
This PR fixes some minor visual & layout issues.
=> fix: Adjust how border is applied, fix table layout in planks

packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/PlankControls.tsx, packages/plugins/plugin-deck/src/translations.ts, packages/plugins/plugin-navtree/src/components/NavTreeFooter.tsx, packages/ui/react-ui-stack/src/components/LayoutControls.tsx, packages/ui/react-ui-stack/src/translations.ts, packages/ui/react-ui-table/src/components/Toolbar/Toolbar.tsx, packages/ui/react-ui-table/src/components/Toolbar/common.tsx, packages/ui/react-ui-theme/src/styles/components/main.ts, packages/ui/react-ui/src/components/Buttons/IconButton.tsx
- Increase size of plank buttons
- Simplify plank/solo to "maximize" / "deck" labels
=> chore: Update plank buttons

packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/PlankControls.tsx, packages/plugins/plugin-table/src/components/TableContainer.tsx
This fixes a regression from merge conflicts.
=> fix(plugin-table): Restore `role` passing

packages/plugins/plugin-deck/src/components/DeckLayout/ComplementarySidebar.tsx, packages/plugins/plugin-thread/src/components/CommentsContainer.tsx, packages/plugins/plugin-thread/src/components/ThreadComplementary.tsx, packages/ui/react-ui-theme/src/styles/components/scroll-area.ts, packages/ui/react-ui-theme/src/styles/fragments/arrow.ts, packages/ui/react-ui-thread/src/Message/Message.tsx, packages/ui/react-ui-thread/src/Thread/Thread.tsx
This PR:
- fixes missing tokens
- fixes thread overflow by moving ScrollArea into the sidebar
- adjusts how spacing is applied to threads
=> fix: Complementary sidebar layout issues

packages/core/echo/echo-db/src/echo-handler/create.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.ts, packages/core/echo/echo-db/src/proxy-db/database.test.ts, packages/core/echo/echo-db/src/proxy-db/database.ts, packages/core/echo/echo-generator/src/generator.ts, packages/core/echo/echo-generator/src/types.ts, packages/core/echo/echo-schema/docs/schema.drawio.svg, packages/core/echo/echo-schema/src/ast/annotations.ts, packages/core/echo/echo-schema/src/ast/types.ts, packages/core/echo/echo-schema/src/formats/types.ts, packages/core/echo/echo-schema/src/handler/typed-handler.ts, packages/core/echo/echo-schema/src/handler/untyped-handler.ts, packages/core/echo/echo-schema/src/mutable/mutable-schema.ts, packages/core/echo/echo-schema/src/mutable/runtime-schema-registry.ts, packages/core/echo/echo-schema/src/object/typed-object.test.ts, packages/core/echo/echo-schema/src/object/typed-object.ts, packages/core/echo/echo-schema/src/proxy/proxy.ts, packages/core/echo/echo-schema/src/testing/schema.ts, packages/core/echo/echo-schema/src/types.ts
=> docs: Update docs and tests

packages/plugins/plugin-sheet/src/testing/playwright/sheet-manager.ts, packages/plugins/plugin-sheet/src/testing/playwright/sheet.spec.ts, packages/ui/lit-grid/src/dx-grid.pcss, packages/ui/lit-grid/src/testing/playwright/dx-grid-manager.ts
This PR fixes e2e tests for SheetPlugin.
=> fix(plugin-sheet): Fix e2e tests

packages/plugins/plugin-sheet/src/SheetPlugin.tsx, packages/plugins/plugin-sheet/src/components/SheetObjectSettings.tsx, packages/plugins/plugin-sheet/src/components/index.ts, packages/plugins/plugin-space/src/SpacePlugin.tsx
This PR restores sheet settings.
=> fix(plugin-sheet): Sheet settings

packages/sdk/shell/src/components/AgentConfig.tsx, packages/sdk/shell/src/components/DeviceList/DeviceList.tsx, packages/sdk/shell/src/panels/IdentityPanel/steps/IdentityActionChooser.tsx, packages/sdk/shell/src/styles/invitationStatusStyles.ts
Is there a more systematic fix?
=> fix: focus indicator clipping.

packages/plugins/plugin-deck/src/DeckPlugin.tsx, packages/plugins/plugin-space/src/SpacePlugin.tsx, packages/sdk/app-framework/src/plugins/common/navigation.ts
- updates closed state in deck again
- updates viewing messages to more accurately reflect peers state
- end result is that presence should be more accurate
=> fix: improve object presence

packages/core/echo/echo-schema/docs/schema.drawio.svg, packages/core/echo/echo-schema/src/object/object-id.ts, packages/core/protocols/src/edge.ts, packages/experimental/assistant/src/testing/test-schema.ts, packages/plugins/plugin-sheet/src/extensions/editor/extension.ts, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/lit-grid/src/types.ts, packages/ui/lit-grid/src/util.ts, packages/ui/react-ui-editor/src/extensions/autocomplete.ts, packages/ui/react-ui-editor/src/extensions/mention.ts, packages/ui/react-ui-form/src/components/Form/Form.tsx, packages/ui/react-ui-form/src/hooks/useForm.ts, packages/ui/react-ui-grid/src/Grid/Grid.tsx, packages/ui/react-ui-table/src/components/Table/CreateRefPanel.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.stories.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/extension.ts, packages/ui/react-ui-table/src/model/modal-controller.ts, packages/ui/react-ui-table/src/translations.ts, packages/ui/react-ui-table/src/types/table.ts
This PR:
- resolves #8356
https://github.com/user-attachments/assets/6f89fbff-46af-461a-a778-420c0bb9ac76
=> feat(react-ui-table): Create object when editing a cell in a ref column

packages/core/echo/echo-schema/src/ast/annotations.ts, packages/core/echo/echo-schema/src/ast/index.ts, packages/core/echo/echo-schema/src/ast/ref.ts, packages/core/echo/echo-schema/src/experimental.test.ts, packages/core/echo/echo-schema/src/mutable/index.ts, packages/plugins/plugin-debug/package.json, packages/plugins/plugin-debug/src/DebugPlugin.tsx, packages/plugins/plugin-debug/src/components/SpaceGenerator/ObjectGenerator.tsx, packages/plugins/plugin-debug/src/components/SpaceGenerator/SchemaTable.tsx, packages/plugins/plugin-debug/src/components/SpaceGenerator/SpaceGenerator.tsx, packages/plugins/plugin-debug/src/components/SpaceGenerator/draw-util.ts, packages/plugins/plugin-markdown/src/MarkdownPlugin.tsx, packages/plugins/plugin-sheet/src/components/FunctionEditor/FunctionEditor.tsx, packages/plugins/plugin-sheet/src/defs/sheet-range-types.ts, packages/plugins/plugin-sheet/src/defs/types.ts, packages/plugins/plugin-sheet/src/defs/util.ts, packages/plugins/plugin-sheet/src/index.ts, packages/plugins/plugin-sheet/src/model/sheet-model.test.ts, packages/plugins/plugin-sheet/src/model/sheet-model.ts, packages/plugins/plugin-sheet/src/model/testing.ts, packages/plugins/plugin-sheet/src/testing/data.ts, packages/plugins/plugin-sheet/src/testing/index.ts, packages/plugins/plugin-sheet/src/testing/testing.tsx, packages/sdk/react-client/src/banner.ts, packages/ui/react-ui-form/src/components/Form/Form.stories.tsx, packages/ui/react-ui-theme/src/styles/components/input.ts, pnpm-lock.yaml
https://github.com/user-attachments/assets/e277c8ed-5b7c-4af3-9f5f-0790028ca170
=> test: experimental object refs

packages/core/echo/echo-schema/src/experimental.test.ts, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/react-ui-table/src/components/Table/ColumnSettings.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/model/table-model.ts, packages/ui/react-ui-table/src/playwright/smoke.spec.ts
- Resolves https://github.com/dxos/dxos/issues/8327
- Resolves https://github.com/dxos/dxos/issues/8257
https://github.com/user-attachments/assets/e6d5c2e0-d7d3-43e1-9c49-e15851ae66d4
=> fix(tables): Scroll new row, column into view

packages/sdk/client-services/src/packlets/agents/edge-agent-manager.ts
When an agent is created we start active `/notarization` endpoint polling to ensure agent feed is added to all the spaces we're in. Periodically check if the desired state was reached and disabled the active polling mode.
Fixes a lot of unnecessary extra requests on agent setup.
=> fix: infinite active edge polling when agent is first enabled

packages/core/echo/echo-schema/src/query/query.ts, packages/plugins/experimental/plugin-automation/src/components/AssistantPanel/system-instructions.ts, packages/plugins/plugin-debug/src/components/SpaceGenerator/ObjectGenerator.tsx, packages/plugins/plugin-table/src/TablePlugin.tsx, packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/plugins/plugin-table/src/components/TableViewEditor.tsx, packages/sdk/schema/src/view.test.ts, packages/sdk/schema/src/view.ts, packages/ui/react-ui-form/src/components/ViewEditor/ViewEditor.tsx, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.stories.tsx, tools/executors/toolbox/src/toolbox.ts
=> fix: Revert query schema type change

packages/plugins/plugin-debug/src/DebugPlugin.tsx, packages/plugins/plugin-graph/src/GraphPlugin.tsx, packages/plugins/plugin-navtree/src/NavTreePlugin.tsx, packages/plugins/plugin-space/src/SpacePlugin.tsx, packages/sdk/app-graph/src/graph-builder.ts
- ensure cached nodes resolve before adding connected nodes
- change storage key because of overlap with previously too aggressive
cached values
=> refactor: graph cache improvements

packages/common/effect/src/ast.test.ts, packages/common/effect/src/ast.ts, packages/common/util/src/deep.ts, packages/core/echo/echo-schema/src/types.test.ts, packages/core/echo/echo-schema/src/types.ts, packages/sdk/schema/src/properties.test.ts, packages/sdk/schema/src/properties.ts, packages/sdk/schema/src/validate.ts, packages/ui/react-ui-form/src/components/Form/Form.stories.tsx, packages/ui/react-ui-form/src/components/Form/Form.tsx, packages/ui/react-ui-form/src/components/Form/Input.tsx, packages/ui/react-ui-form/src/hooks/useForm.ts
=> chore(forms): Support Partial<T>

packages/plugins/plugin-client/src/components/RecoveryCodeDialog.stories.tsx, packages/plugins/plugin-client/src/components/RecoveryCodeDialog.tsx, packages/plugins/plugin-client/src/translations.ts, packages/plugins/plugin-debug/src/DebugPlugin.tsx, packages/plugins/plugin-space/src/components/CreateDialog/CreateObjectDialog.stories.tsx
=> refactor: Update recover key ux.

REPOSITORY_GUIDE.md, package.json, packages/apps/composer-app/package.json, packages/common/effect/package.json, packages/core/echo/echo-db/package.json, packages/core/echo/echo-schema/package.json, packages/core/echo/live-object/package.json, packages/core/functions/package.json, packages/devtools/cli-base/package.json, packages/experimental/agent-functions/package.json, packages/plugins/plugin-debug/package.json, packages/plugins/plugin-deck/package.json, packages/plugins/plugin-files/package.json, packages/plugins/plugin-markdown/package.json, packages/plugins/plugin-sketch/package.json, packages/plugins/plugin-space/package.json, packages/plugins/plugin-status-bar/package.json, packages/sdk/app-framework/package.json, packages/sdk/schema/package.json, packages/ui/react-ui-canvas/package.json, packages/ui/react-ui-form/package.json, packages/ui/react-ui-list/package.json, pnpm-lock.yaml
```bash
npx npm-check-updates --deep -u effect "@effect/*"
```
=> chore: effect version upgrade

packages/devtools/cli/package.json, packages/devtools/cli/src/commands/function/upload.ts, packages/devtools/cli/tsconfig.json, pnpm-lock.yaml
CLI deployment fails on `prepack` step with an error 
We agreed with @wittjosiah  to comment plugin dependency from CLI to unblock me, and fix it later.
=> chore: Comment out cli `upload` command to fix deploy

packages/ui/react-ui-table/src/model/table-presentation.ts, packages/ui/react-ui-theme/src/config/tokens/sememes-sheet.ts
- Resolves https://github.com/dxos/dxos/issues/8359
Dark mode
Dark mode selection
Light mode
Light mode selection
=> chore(tables): Header color lift

packages/sdk/client-services/src/packlets/spaces/notarization-plugin.ts
Allow calling `setActiveEdgePolling` method when notarizationPlugin is closed.
Agent manager calls it on inactive (closed) spaces to ensure the setting is off.
Fixes invariant violations reported in sentry.
=> fix: invariant violation when disabling activeEdgePolling

packages/ui/react-ui-form/src/components/FieldEditor/FieldEditor.tsx, packages/ui/react-ui-table/src/components/Table/ColumnActionsMenu.tsx, packages/ui/react-ui-table/src/model/table-model.ts, packages/ui/react-ui-table/src/model/table-sorting.ts
- Pull sorting out into its own module
- Supports #8256
=> fix(tables): Sorting overhaul

packages/plugins/experimental/plugin-automation/src/components/AutomationPanel/AutomationPanel.tsx, packages/plugins/experimental/plugin-automation/src/components/TriggerEditor/TriggerEditor.tsx, packages/plugins/experimental/plugin-automation/src/translations.ts, packages/sdk/schema/src/properties.ts
Trigger meta field is passed to a function when it's invoked by trigger dispatcher.
This can be used to pass arbitrary properties, like ID of an object that we want to modify during execution or gpt prompt.
=> feat: trigger meta editor

packages/plugins/experimental/plugin-script/src/templates/email.ts
1. Choose the new template and deploy it.
2. Create a document and copy its ID.
3. Open automations panel and configure an Email trigger to point to the deployed function and have targetDocumentId set in meta.
4. Click on copy Email and send something to the address.
=> feat: document mailbox script template

packages/plugins/plugin-deck/src/components/DeckLayout/ContentEmpty.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx, packages/plugins/plugin-deck/src/components/fragments.ts, packages/ui/react-ui-menu/src/components/ToolbarMenu.tsx, packages/ui/react-ui-theme/src/styles/fragments/dimension.ts
This PR fixes a number of issues with the mobile and tablet breakpoints.
=> fix: iPhone layout

packages/apps/composer-app/socket.ini, packages/ui/react-ui-attention/src/components/AttentionProvider.tsx, packages/ui/react-ui-theme/src/theme.css
This PR resolves part of #8532.
=> fix: Touch actions on iOS

packages/plugins/experimental/plugin-kanban/src/components/KanbanContainer.tsx, packages/ui/react-ui-form/src/components/Form/Form.tsx, packages/ui/react-ui-kanban/src/components/Kanban.tsx, packages/ui/react-ui-kanban/src/defs/kanban-model.ts
- **Don't crash when composer intially loads**
- **Hide the column field in Kanban form**
=> fix(kanban): QOL Improvements

packages/apps/composer-app/socket.ini, packages/apps/composer-app/vite.config.ts, packages/plugins/experimental/plugin-native/src/initialize.ts, packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/PlankControls.tsx, packages/plugins/plugin-navtree/src/components/L0Menu.tsx, packages/plugins/plugin-navtree/src/components/L1Panels.tsx, packages/plugins/plugin-navtree/src/components/NavTreeItemColumns.tsx, packages/plugins/plugin-navtree/src/components/NotchStart.tsx, packages/ui/react-ui-stack/src/components/StackItemSigil.tsx, packages/ui/react-ui-theme/src/styles/layers/index.css, packages/ui/react-ui-theme/src/styles/layers/native.css, packages/ui/react-ui-theme/src/styles/layers/tldraw.css, packages/ui/react-ui-theme/src/styles/layers/tokens.css, packages/ui/react-ui-theme/src/theme.css
This PR:
- resolves #8573.
https://github.com/user-attachments/assets/b3564339-b87a-4921-b70f-bf23b99260f7
=> fix: macOS windowing, platform annotation, L0 design

packages/plugins/plugin-deck/src/capabilities/intent-resolver.ts, packages/plugins/plugin-deck/src/capabilities/state.ts, packages/plugins/plugin-deck/src/components/DeckLayout/ComplementarySidebar.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/SidebarButton.tsx, packages/plugins/plugin-deck/src/components/fragments.ts, packages/plugins/plugin-deck/src/hooks/useMainSize.ts, packages/plugins/plugin-deck/src/types.ts, packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx, packages/sdk/app-framework/src/common/layout.ts, packages/ui/react-ui-theme/src/styles/layers/main.css, packages/ui/react-ui-theme/src/styles/layers/tokens.css, packages/ui/react-ui/src/components/Buttons/IconButton.tsx, packages/ui/react-ui/src/components/Main/Main.stories.tsx, packages/ui/react-ui/src/components/Main/Main.tsx
=> feat: “R0” tabs pattern for complementary sidebar

packages/plugins/plugin-deck/src/components/DeckLayout/ComplementarySidebar.tsx, packages/plugins/plugin-navtree/src/components/L0Menu.tsx, packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts
This PR:
- removes glass effect on L0 & R0
- fixes overflow issues in R1
- clicking an active tab in R0 toggles the expanded/collapsed state
=> fix: R0 feedback

packages/plugins/plugin-navtree/src/components/NavTreeItemAction.tsx, packages/plugins/plugin-space/src/capabilities/react-surface.tsx, packages/plugins/plugin-space/src/util.tsx
=> refactor: shift space action from plank headings to L1

packages/ui/react-ui-stack/src/components/StackItemResizeHandle.tsx
This PR:
- does what it says on the tin
https://github.com/user-attachments/assets/7c8a330b-13fe-4f88-81c6-6aee7858117c
=> fix(react-ui-stack): Finish implementation of vertical resizing

packages/plugins/experimental/plugin-calls/src/meta.ts, packages/plugins/experimental/plugin-canvas/src/meta.ts, packages/plugins/experimental/plugin-excalidraw/src/meta.ts, packages/plugins/experimental/plugin-explorer/src/meta.ts, packages/plugins/experimental/plugin-kanban/src/meta.ts, packages/plugins/experimental/plugin-script/src/meta.ts, packages/plugins/plugin-chess/src/meta.ts, packages/plugins/plugin-sheet/src/meta.ts, packages/plugins/plugin-sketch/src/meta.ts, packages/ui/react-ui-kanban/src/components/Kanban.tsx, packages/ui/react-ui-stack/src/components/StackItem.tsx, packages/ui/react-ui-theme/src/styles/layers/focus-ring.css
This PR:
- resolves #8631.
https://github.com/user-attachments/assets/bcae6a7f-8227-46d9-a1cb-1f8ee52ea8e9
=> fix(react-ui-stack,react-ui-kanban): Keyboard access, DOM order, focus indicators

packages/plugins/experimental/plugin-automation/src/capabilities/app-graph-builder.ts, packages/plugins/experimental/plugin-automation/src/capabilities/react-surface.tsx, packages/plugins/experimental/plugin-automation/src/components/AmbientChatDialog/AmbientChatDialog.tsx, packages/plugins/experimental/plugin-automation/src/components/AmbientChatDialog/index.ts, packages/plugins/experimental/plugin-automation/src/components/index.ts, packages/plugins/experimental/plugin-automation/src/meta.ts, packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx, packages/plugins/plugin-deck/src/types.ts, packages/plugins/plugin-navtree/src/capabilities/app-graph-builder.ts, packages/sdk/app-framework/src/common/layout.ts, packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts, packages/ui/react-ui-theme/src/styles/components/dialog.ts, packages/ui/react-ui-theme/src/styles/fragments/elevation.ts, packages/ui/react-ui-theme/src/styles/fragments/motion.ts, packages/ui/react-ui-theme/src/styles/layers/dialog.css, packages/ui/react-ui-theme/src/styles/layers/index.css, packages/ui/react-ui/src/components/Dialogs/AlertDialog.tsx, packages/ui/react-ui/src/components/Dialogs/Dialog.tsx
This PR:
- resolves #8641.
- adds a stub ambient chat dialog to AutomationPlugin
- replaces Cmd+K keybinding to open the dialog
https://github.com/user-attachments/assets/6e57179f-91de-4ef0-9a63-8507304e6691
=> feat: Ambient chat dialog

packages/plugins/experimental/plugin-automation/package.json, packages/plugins/experimental/plugin-automation/src/components/AmbientChatDialog/AmbientChatDialog.tsx, packages/plugins/experimental/plugin-automation/tsconfig.json, packages/ui/react-ui-dnd/project.json, packages/ui/react-ui-dnd/src/components/ResizeHandle.tsx, packages/ui/react-ui-dnd/src/index.ts, packages/ui/react-ui-dnd/src/types.ts, packages/ui/react-ui-dnd/src/util/index.ts, packages/ui/react-ui-dnd/src/util/rem.ts, packages/ui/react-ui-dnd/src/util/sizeStyle.ts, packages/ui/react-ui-stack/src/components/StackItem.tsx, pnpm-lock.yaml
This PR:
- resolves #8667
https://github.com/user-attachments/assets/5802dbcb-ed44-44d6-9f39-40deb44abe0d
=> feat: Ambient chat dialog resizing

packages/plugins/plugin-kanban/src/capabilities/intent-resolver.ts, packages/plugins/plugin-kanban/src/components/KanbanContainer.tsx, packages/plugins/plugin-kanban/src/translations.ts, packages/plugins/plugin-kanban/src/types.ts, packages/ui/react-ui-form/src/components/Form/Defaults.tsx, packages/ui/react-ui-form/src/components/Form/Form.tsx, packages/ui/react-ui-form/src/components/Form/FormContent.tsx, packages/ui/react-ui-form/src/components/Form/factory.tsx, packages/ui/react-ui-kanban/src/components/Kanban.stories.tsx, packages/ui/react-ui-kanban/src/components/Kanban.tsx, packages/ui/react-ui-kanban/src/testing/initialize-kanban.ts, packages/ui/react-ui-stack/src/components/Stack.tsx, packages/ui/react-ui-stack/src/hooks/index.ts, packages/ui/react-ui-stack/src/hooks/useStackDropForElements.ts
- Resolves #8665
- Resolves #8666 
Changes:
- Fix kanban initialisation in stories
- Implement auto-focus
- Scope form auto-focus
- Implement undo for kanban card deletion
- Add card button should stay at the bottom of a column and auto-scroll new cards.
- Add multi-line input for Markdown format
- Kanban columns visually hug cards
https://github.com/user-attachments/assets/7f867381-a7de-482c-b0e0-c179e1fb32de
=> feat(kanban): UX Pass

packages/plugins/experimental/plugin-automation/src/components/AmbientChatDialog/AmbientChatDialog.stories.tsx, packages/plugins/experimental/plugin-automation/src/components/AmbientChatDialog/AmbientChatDialog.tsx, packages/plugins/experimental/plugin-automation/src/components/Prompt/prompt-autocomplete.ts, packages/plugins/experimental/plugin-calls/package.json, packages/plugins/experimental/plugin-calls/src/components/ResponsiveGrid/ResponsiveGrid.tsx, packages/plugins/experimental/plugin-calls/tsconfig.json, packages/ui/react-ui-dnd/src/components/ResizeHandle.tsx, packages/ui/react-ui/src/components/Dialogs/Dialog.stories.tsx, pnpm-lock.yaml
https://github.com/user-attachments/assets/8984e749-5429-40b1-a528-b3a0d5dad1d3
=> feat: Add resize handle to calls grid

packages/plugins/plugin-navtree/src/components/L0Menu.tsx, packages/plugins/plugin-space/src/components/SpaceSettings/SpaceSettingsPanel.tsx, packages/plugins/plugin-space/src/translations.ts, packages/plugins/plugin-space/src/util.tsx, packages/sdk/shell/src/panels/IdentityPanel/IdentityPanel.tsx, packages/sdk/shell/src/panels/IdentityPanel/steps/ProfileForm.tsx, packages/sdk/shell/src/translations/locales/en-US.ts, packages/ui/react-ui-form/src/components/Form/custom/SelectOptionsInput.tsx, packages/ui/react-ui-pickers/src/components/EmojiPicker.stories.tsx, packages/ui/react-ui-pickers/src/components/EmojiPicker.tsx, packages/ui/react-ui-pickers/src/components/HuePicker.stories.tsx, packages/ui/react-ui-pickers/src/components/HuePicker.tsx, packages/ui/react-ui-pickers/src/components/IconPicker.stories.tsx, packages/ui/react-ui-pickers/src/components/IconPicker.tsx, packages/ui/react-ui-pickers/src/components/ToolbarPicker.tsx, packages/ui/react-ui-pickers/src/components/index.ts
=> feat: icon picker

packages/plugins/experimental/plugin-automation/src/components/AmbientChatDialog/AmbientDialog.tsx, packages/plugins/experimental/plugin-automation/src/components/Prompt/PromptBar.tsx, packages/plugins/experimental/plugin-automation/src/translations.ts, packages/plugins/plugin-navtree/src/components/L0Menu.tsx, packages/ui/primitives/react-hooks/src/useResize.ts, packages/ui/react-ui-theme/src/styles/layers/dialog.css
This PR:
- resolves #8697 
- resolves #8698 
- simplifies state for the ambient chat dialog’s expand/collapse action
- cleans up some other related technical debt
=> fix: Polish

packages/apps/composer-app/src/help.ts, packages/apps/composer-app/src/playwright/app-manager.ts, packages/plugins/plugin-deck/src/capabilities/intent-resolver.ts, packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx, packages/plugins/plugin-deck/src/types.ts, packages/plugins/plugin-navtree/src/components/L0Menu.tsx, packages/plugins/plugin-navtree/src/components/NavTreeContainer.tsx, packages/plugins/plugin-space/src/capabilities/app-graph-builder.ts, packages/plugins/plugin-space/src/capabilities/intent-resolver.ts, packages/plugins/plugin-space/src/capabilities/react-surface.tsx, packages/plugins/plugin-space/src/components/PopoverAddSpace.tsx, packages/plugins/plugin-space/src/components/index.ts, packages/plugins/plugin-space/src/translations.ts, packages/plugins/plugin-space/src/types/types.ts, packages/sdk/app-framework/src/common/layout.ts
This PR:
- resolves #8674.
- appears to resolve an issue where the global popover moves when first mounted
- maintains e2e
https://github.com/user-attachments/assets/b441bedf-a40f-4fb2-aba9-581d63b7a882
=> feat: Nested “add space” menu

packages/plugins/experimental/plugin-automation/src/components/AmbientDialog/AmbientDialog.tsx, packages/plugins/experimental/plugin-automation/src/components/Thread/Thread.tsx, packages/ui/react-ui-dnd/src/components/ResizeHandle.tsx, packages/ui/react-ui-dnd/src/util/sizeStyle.ts, packages/ui/react-ui-theme/src/styles/layers/dialog.css, packages/ui/react-ui-theme/src/styles/layers/tokens.css
This PR:
- adds `calc-size` tokens with fallbacks when unsupported
- makes some other minor adjustments
https://github.com/user-attachments/assets/51244e01-c37c-4323-9d8e-1cadafb6a42c
=> feat: `calc-size` tokens

packages/core/echo/echo-db/src/core-db/core-database.ts, packages/plugins/plugin-debug/src/components/SpaceGenerator/ObjectGenerator.tsx, packages/plugins/plugin-debug/src/components/SpaceGenerator/presets.ts, packages/ui/react-ui-canvas-compute/src/shapes/Trigger.tsx
* Allow partial backups by returning references that we managed to load within the specified timeout.
* Ensure queues in presets are scoped to the space a Trigger is in.
=> fix: partial backups

packages/plugins/plugin-deck/src/capabilities/intent-resolver.ts, packages/plugins/plugin-deck/src/capabilities/url-handler.ts, packages/plugins/plugin-deck/src/components/DeckLayout/Plank.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/PlankControls.tsx, packages/plugins/plugin-deck/src/layout.ts, packages/plugins/plugin-registry/src/capabilities/app-graph-builder.ts, packages/plugins/plugin-registry/src/capabilities/react-surface.tsx, packages/plugins/plugin-registry/src/components/PluginItem.tsx, packages/plugins/plugin-registry/src/components/RegistryContainer.tsx, packages/plugins/plugin-registry/src/translations.ts, packages/plugins/plugin-space/src/capabilities/app-graph-builder.ts, packages/plugins/plugin-space/src/util.tsx
- **fix: copy object link**
- **fix: space is not initialized error**
- **feat: link to plugin settings from registry**
- **fix: plank sizing by key**
- **fix: closing active item on load**
- **refactor: larger plank controls**
=> fix: a bunch of small fixes

packages/core/echo/echo-schema/src/json/json-schema.test.ts, packages/core/echo/echo-schema/src/json/json-schema.ts, packages/sdk/schema/src/projection.test.ts, packages/sdk/schema/src/projection.ts
=> chore(views): Single select storage format

packages/plugins/experimental/plugin-calls/src/types/types.ts
=> fix(plugin-calls): Fix typecheck

packages/sdk/shell/src/panels/IdentityPanel/IdentityPanel.tsx
=> fix(sdk): Update display name with greater certainty

packages/apps/composer-app/src/plugins/welcome/components/Welcome/Welcome.tsx, packages/plugins/experimental/plugin-automation/src/capabilities/app-graph-builder.ts, packages/plugins/plugin-client/src/types.ts, packages/plugins/plugin-deck/src/capabilities/url-handler.ts, packages/plugins/plugin-pwa/src/PwaPlugin.tsx, packages/sdk/app-framework/src/plugin-intent/intent-dispatcher.ts
- revert assistant disposition
- hide passkeys if not supported
- correct join intent schema
- reduce history duplication
- log async dispatch errors
- contribute pwa plugin translations
=> fix: onboarding + others

packages/plugins/plugin-navtree/src/components/L0Menu.tsx, packages/ui/react-ui-stack/src/components/StackContext.tsx
This PR:
- resolves #8741.
https://github.com/user-attachments/assets/42bcc680-dc2f-446f-86ab-3620672ee2c1
=> fix(plugin-navtree): Restore rearrange spaces

packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/sdk/config/package.json, packages/ui/react-ui-attention/src/components/SelectionProvider.tsx, packages/ui/react-ui-kanban/src/components/Kanban.tsx, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx
Fix yet another bug caused by calling hooks with array literals (new reference every render).
=> fix(table): resolve storybook crash

packages/apps/composer-app/src/help.ts
This PR:
- fixes #8793.
https://github.com/user-attachments/assets/471f9979-46d3-4c84-ae78-edafaa282f85
=> fix(composer-app): Joyride

packages/plugins/plugin-client/src/components/IdentityDialog.tsx, packages/plugins/plugin-client/src/components/JoinDialog.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/ComplementarySidebar.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/Sidebar.tsx, packages/plugins/plugin-deck/src/translations.ts, packages/plugins/plugin-space/src/components/JoinDialog.tsx, packages/ui/react-ui/src/components/Main/Main.stories.tsx, packages/ui/react-ui/src/components/Main/Main.tsx
=> fix: Add missing dialog titles

packages/plugins/experimental/plugin-transcription/src/components/Transcript/Transcript.stories.tsx, packages/plugins/experimental/plugin-transcription/src/components/Transcript/Transcript.tsx, packages/ui/lit-grid/src/dx-grid.pcss
This PR fixes Transcript intrinsic size virtualization, since the most recent code was mostly unmaintainable AI-generated code.
=> fix: Transcript virtualization

packages/devtools/devtools/src/components/MasterDetailTable.tsx, packages/devtools/devtools/src/panels/client/LoggingPanel/LoggingPanel.tsx, packages/devtools/devtools/src/panels/echo/ObjectsPanel/ObjectsPanel.tsx
- **Fix log panel selection issue**
- **Better layout for object table**
- **Switch master-detail table to side-side layout**
=> chore: Devtools layout enhancements

packages/plugins/experimental/plugin-transcription/src/components/Transcript/Transcript.stories.tsx, packages/plugins/experimental/plugin-transcription/src/components/Transcript/Transcript.tsx, packages/plugins/experimental/plugin-transcription/src/components/transcription.stories.tsx, packages/plugins/experimental/plugin-transcription/src/transcriber/summarize.ts, packages/plugins/experimental/plugin-transcription/src/transcription-manager.ts, packages/plugins/experimental/plugin-transcription/src/translations.ts, packages/plugins/experimental/plugin-transcription/src/types/schema.ts, packages/plugins/plugin-meeting/src/state/call-manager.ts, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/react-ui-theme/src/styles/layers/hues.css, packages/ui/react-ui-theme/src/styles/layers/index.css
This PR:
- resolves #8864
https://github.com/user-attachments/assets/4440ca4f-5636-46f0-9688-24b9900c7a5f
=> feat: Transcript improvements

packages/plugins/experimental/plugin-assistant/src/components/Thread/Thread.tsx, packages/plugins/experimental/plugin-assistant/src/components/Thread/ThreadMessage.tsx, packages/ui/react-ui-theme/src/config/tailwind.ts
https://github.com/user-attachments/assets/6d1e4f31-1353-42c4-87a8-648d29cfad21
=> fix: Assistant UI Issues

packages/plugins/experimental/plugin-outliner/src/OutlinerPlugin.tsx, packages/plugins/experimental/plugin-outliner/src/capabilities/intent-resolver.ts, packages/plugins/experimental/plugin-outliner/src/components/Journal/Journal.tsx, packages/plugins/experimental/plugin-outliner/src/components/NodeEditor/NodeEditor.tsx, packages/plugins/experimental/plugin-outliner/src/components/Outliner/Outliner.stories.tsx, packages/plugins/experimental/plugin-outliner/src/components/Outliner/Outliner.tsx, packages/plugins/experimental/plugin-outliner/src/components/OutlinerContainer.tsx, packages/plugins/experimental/plugin-outliner/src/translations.ts, packages/plugins/experimental/plugin-outliner/src/types/action.ts, packages/plugins/experimental/plugin-outliner/src/types/index.ts, packages/plugins/experimental/plugin-outliner/src/types/task.ts, packages/plugins/experimental/plugin-outliner/src/types/tree.test.ts, packages/plugins/experimental/plugin-outliner/src/types/tree.ts, packages/plugins/plugin-table/src/capabilities/react-surface.tsx
- Outline node menu.
- Outline refs.
- Menu item to convert outline item to task.
<br>
=> feat: Outliner tasks

packages/apps/composer-app/src/components/ResetDialog.tsx, packages/apps/composer-app/src/main.tsx, packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx, packages/plugins/plugin-status-bar/src/components/FeedbackForm.tsx, packages/plugins/plugin-status-bar/src/components/StatusBarPanel.tsx, packages/plugins/plugin-status-bar/src/components/index.ts, packages/ui/react-ui-form/src/components/Form/index.ts, packages/ui/react-ui-form/src/hooks/useForm.ts
=> feat: add feedback form to error boundary

packages/core/functions/src/types/trace.ts, packages/devtools/devtools/src/panels/edge/InvocationTracePanel/InvocationTracePanel.tsx, packages/plugins/experimental/plugin-script/src/components/LogsPanel/LogsPanel.tsx
Split `InvocationTraceEvent` into `InvocationTraceStartEvent` and `InvocationTraceEndEvent` so the we can detect active invocations.
=> feat: change schema to detect active invocations

packages/plugins/plugin-debug/src/components/SpaceGenerator/SchemaTable.tsx, packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/ui/react-ui-table/src/components/Table/ColumnActionsMenu.tsx, packages/ui/react-ui-table/src/components/Table/DynamicTable.tsx, packages/ui/react-ui-table/src/components/Table/RowActionsMenu.tsx, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.stories.tsx, packages/ui/react-ui-table/src/hooks/useTableModel.ts, packages/ui/react-ui-table/src/model/table-model.ts, packages/ui/react-ui-table/src/model/table-presentation.ts
=> feat: Support read-only tables

packages/plugins/plugin-token-manager/src/TokenManagerPlugin.ts, packages/plugins/plugin-token-manager/src/components/NewTokenSelector.tsx, packages/plugins/plugin-token-manager/src/components/TokensContainer.tsx, packages/plugins/plugin-token-manager/src/translations.ts
=> refactor: unify token creation menu

packages/plugins/experimental/plugin-outliner/src/components/Journal/Journal.tsx, packages/plugins/experimental/plugin-outliner/src/components/NodeEditor/NodeEditor.tsx, packages/plugins/experimental/plugin-outliner/src/types/types.ts
=> fix: outliner navigation and journal date.

packages/core/echo/echo-schema/src/ast/annotations.ts, packages/plugins/experimental/plugin-outliner/package.json, packages/plugins/experimental/plugin-outliner/src/components/JournalContainer.tsx, packages/plugins/experimental/plugin-outliner/src/components/NodeEditor/NodeEditor.tsx, packages/plugins/experimental/plugin-outliner/src/components/Outliner/Outliner.stories.tsx, packages/plugins/experimental/plugin-outliner/src/components/Outliner/Outliner.tsx, packages/plugins/experimental/plugin-outliner/src/components/OutlinerContainer.tsx, packages/plugins/experimental/plugin-outliner/src/components/index.ts, packages/plugins/experimental/plugin-outliner/src/hooks/index.ts, packages/plugins/experimental/plugin-outliner/src/hooks/useOutlinerHandlers.ts, packages/plugins/experimental/plugin-outliner/src/types/task.ts, packages/plugins/experimental/plugin-outliner/tsconfig.json, packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx, packages/plugins/plugin-markdown/src/components/Toolbar.stories.tsx, packages/plugins/plugin-thread/src/components/MessageContainer.tsx, packages/ui/react-ui-editor/src/InputMode.stories.tsx, packages/ui/react-ui-editor/src/TextEditor.stories.tsx, packages/ui/react-ui-editor/src/extensions/factories.ts, pnpm-lock.yaml
https://github.com/user-attachments/assets/47e8c542-4ca8-475b-a3c0-d4be8b23937b
=> feat: outliner task link

packages/plugins/plugin-meeting/src/components/Lobby/Lobby.stories.tsx, packages/plugins/plugin-meeting/src/components/Media/VideoObject.stories.tsx, packages/plugins/plugin-meeting/src/components/ResponsiveGrid/ResponsiveContainer.stories.tsx, packages/plugins/plugin-meeting/src/components/ResponsiveGrid/ResponsiveGrid.stories.tsx, packages/plugins/plugin-meeting/src/components/ResponsiveGrid/ResponsiveGrid.tsx, packages/plugins/plugin-meeting/src/peers.stories.tsx
Need to refresh layout when item is pinned/unpinned.
=> fix: Fix dynamic video splitter 

packages/plugins/plugin-script/src/ScriptPlugin.tsx, packages/plugins/plugin-script/src/capabilities/index.ts, packages/plugins/plugin-table/src/TablePlugin.tsx, packages/plugins/plugin-table/src/capabilities/app-graph-builder.ts, packages/plugins/plugin-table/src/capabilities/index.ts, packages/plugins/plugin-table/src/capabilities/react-surface.tsx, packages/plugins/plugin-table/src/translations.ts
=> feat: table companion plank

packages/common/random/src/faker.ts, packages/core/echo/echo-schema/src/formats/types.ts, packages/sdk/schema/src/construction.ts, packages/sdk/schema/src/format.ts, packages/sdk/schema/src/projection.test.ts, packages/sdk/schema/src/projection.ts, packages/sdk/schema/src/util.ts, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.tsx, packages/ui/react-ui-table/src/model/table-presentation.ts
=> feat(schema): Add MultiSelect format

packages/sdk/schema/src/testing/types.ts, packages/ui/react-ui-editor/src/TextEditor.stories.tsx, packages/ui/react-ui-editor/src/defaults.ts, packages/ui/react-ui-editor/src/extensions/command/command.ts, packages/ui/react-ui-editor/src/index.ts, packages/ui/react-ui-list/src/components/Accordion/Accordion.stories.tsx, packages/ui/react-ui-list/src/components/Accordion/Accordion.tsx, packages/ui/react-ui-list/src/components/Accordion/AccordionItem.tsx, packages/ui/react-ui-list/src/components/Accordion/AccordionRoot.tsx, packages/ui/react-ui-list/src/components/Accordion/index.ts, packages/ui/react-ui-list/src/components/List/List.stories.tsx, packages/ui/react-ui-list/src/components/List/List.tsx, packages/ui/react-ui-list/src/components/List/ListItem.tsx, packages/ui/react-ui-list/src/components/List/ListRoot.tsx
Quick first cut of a headless scrolling accordion based loosely on the List component.
https://github.com/user-attachments/assets/47b1bee0-bd9f-4ded-997b-8d58c1480eb3
=> feat: react-ui-list accordion first iteration

packages/ui/react-ui-editor/src/TextEditor.stories.tsx, packages/ui/react-ui-editor/src/extensions/command/command.ts, packages/ui/react-ui-editor/src/extensions/command/hint.ts, packages/ui/react-ui-editor/src/extensions/command/menu.ts, packages/ui/react-ui-editor/src/extensions/command/preview.ts, packages/ui/react-ui-editor/src/extensions/command/state.ts
https://github.com/user-attachments/assets/70e380aa-4816-4d43-9af6-ed6bc7742541
=> feat: command editor and preview block

packages/plugins/plugin-assistant/src/capabilities/app-graph-builder.ts, packages/plugins/plugin-assistant/src/capabilities/react-surface.tsx, packages/plugins/plugin-assistant/src/components/PromptSettings.tsx, packages/plugins/plugin-assistant/src/components/TemplateContainer.tsx, packages/plugins/plugin-assistant/src/components/index.ts, packages/plugins/plugin-assistant/src/translations.ts
=> refactor: cleanup prompt editor

packages/plugins/plugin-automation/package.json, packages/plugins/plugin-automation/project.json, packages/plugins/plugin-automation/src/AutomationPlugin.tsx, packages/plugins/plugin-automation/src/capabilities/index.ts, packages/plugins/plugin-automation/src/capabilities/intent-resolver.ts, packages/plugins/plugin-automation/src/components/AutomationPanel/AutomationPanel.tsx, packages/plugins/plugin-automation/src/types.ts, packages/plugins/plugin-inbox/package.json, packages/plugins/plugin-inbox/src/capabilities/react-surface.tsx, packages/plugins/plugin-inbox/src/components/Mailbox/MailboxObjectSettings.tsx, packages/plugins/plugin-inbox/src/components/Mailbox/index.ts, packages/plugins/plugin-inbox/src/components/index.ts, packages/plugins/plugin-inbox/src/translations.ts, packages/plugins/plugin-inbox/tsconfig.json, packages/plugins/plugin-script/src/meta.ts, packages/plugins/plugin-space/src/types/types.ts, pnpm-lock.yaml, tsconfig.paths.json
- **Stub trigger templating**
- **Only show sync / subscription buttons when appropriate.**
- **increment**
=> feat(automation): Trigger templates

packages/plugins/plugin-meeting/src/components/CallContainer.tsx, packages/plugins/plugin-meeting/src/components/CallSidebar.tsx
=> fix: relinquish system av when leaving call

packages/plugins/plugin-meeting/package.json, packages/plugins/plugin-meeting/src/components/MeetingContainer.tsx, packages/plugins/plugin-meeting/src/translations.ts, packages/plugins/plugin-meeting/tsconfig.json, pnpm-lock.yaml
=> feat: ensure display name is set before joining a call

packages/plugins/plugin-meeting/src/state/call-manager.ts, packages/plugins/plugin-meeting/src/state/call-swarm-synchronizer.ts, packages/plugins/plugin-script/src/templates/data-generator.ts
- **Update function template**
- **fix participant counter inside call**
=> fix(plugin-meeting): Fix participant counter; chore: Update data-generator script template

packages/plugins/plugin-automation/src/AutomationPlugin.tsx, packages/plugins/plugin-automation/src/capabilities/react-surface.tsx, packages/plugins/plugin-automation/src/components/AutomationPanel/AutomationPanel.stories.tsx, packages/plugins/plugin-automation/src/components/FunctionsPanel/FunctionsPanel.tsx, packages/plugins/plugin-automation/src/components/FunctionsPanel/index.ts, packages/plugins/plugin-automation/src/components/index.ts, packages/plugins/plugin-automation/src/translations.ts, packages/plugins/plugin-space/src/SpacePlugin.tsx, packages/plugins/plugin-space/src/capabilities/react-surface.tsx, packages/plugins/plugin-space/src/components/SchemaPanel.tsx, packages/plugins/plugin-space/src/components/index.ts, packages/plugins/plugin-space/src/translations.ts
https://github.com/user-attachments/assets/5ca50bce-1224-490d-9868-0154029f2564
Pretty bare bones, but this provides a good base for extension with new functionality for schema / function management.
=> feat(space-settings): Schemas and Functions

packages/plugins/plugin-markdown/package.json, packages/plugins/plugin-markdown/src/components/Suggestions.stories.tsx, packages/plugins/plugin-theme/src/react-context.tsx
Error was caused by side-effect within `useMemo`, fixed by changing to `useEffect` & `useState`. Any alternative setup is what I did in the mailbox story which is to just add the object to the space and then query for it in the story knowing it will be the only object there https://github.com/dxos/dxos/blob/main/packages/plugins/plugin-inbox/src/components/Mailbox/Mailbox.stories.tsx#L90
=> test: fix storybook error

packages/core/protocols/src/proto/dxos/edge/calls.proto, packages/plugins/plugin-meeting/src/components/CallContainer.tsx, packages/plugins/plugin-meeting/src/components/MeetingStatus.tsx, packages/plugins/plugin-transcription/src/capabilities/app-graph-builder.ts
- **Fix race condition**
- **Add context**
- **Add activities**
- **Change calls payload structure**
=> fix: Fix race condition in transcription state updates

packages/plugins/plugin-automation/src/components/AutomationContainer.tsx, packages/plugins/plugin-automation/src/components/FunctionsContainer.tsx, packages/plugins/plugin-client/src/components/DevicesContainer.tsx, packages/plugins/plugin-client/src/components/ProfileContainer.tsx, packages/plugins/plugin-client/src/components/RecoveryCredentialsContainer.tsx, packages/plugins/plugin-space/src/components/MembersContainer.tsx, packages/plugins/plugin-space/src/components/SchemaContainer.tsx, packages/plugins/plugin-space/src/components/SpaceSettings/SpaceSettingsContainer.tsx, packages/plugins/plugin-token-manager/src/components/TokensContainer.tsx, packages/ui/lit-ui/src/dx-avatar/dx-avatar.pcss, packages/ui/react-ui-form/src/components/ControlSection/ControlSection.tsx, packages/ui/react-ui-theme/src/config/tokens/index.ts, packages/ui/react-ui-theme/src/config/tokens/lengths.ts
This PR:
- resolves #9061 
- fixes a bundling issue
- makes controls pages more consistent
https://github.com/user-attachments/assets/effcf171-b9b6-4554-8bd8-8eb3cf01c41c
=> fix: Avatars, other fixes

packages/common/typings/src/index.d.ts, packages/common/typings/src/peermetrics-webrtc-stats.d.ts, packages/plugins/plugin-meeting/package.json, packages/plugins/plugin-meeting/src/components/MeetingStatus.tsx, packages/plugins/plugin-meeting/src/state/media-manager.ts, packages/plugins/plugin-meeting/src/translations.ts, packages/plugins/plugin-meeting/src/util/calls-service.ts, packages/plugins/plugin-meeting/tsconfig.json, pnpm-lock.yaml
- **Clean up state correctly**
- **Calls service changes**
- **Add more status**
- **Add typing**
=> fix: Fix meeting rejoining bug

packages/plugins/plugin-markdown/package.json, packages/plugins/plugin-markdown/src/components/Suggestions.stories.tsx, packages/plugins/plugin-markdown/tsconfig.json, pnpm-lock.yaml
This PR fixes the Suggestions story
https://github.com/user-attachments/assets/8b7b81a6-4ed3-43d3-8c3b-f971a1d8bc02
=> fix: Suggestions story

packages/plugins/plugin-inbox/src/capabilities/react-surface.tsx, packages/plugins/plugin-inbox/src/components/Message/Message.tsx, packages/plugins/plugin-inbox/src/components/Related.tsx, packages/plugins/plugin-preview/package.json, packages/plugins/plugin-preview/src/PreviewPlugin.tsx, packages/plugins/plugin-preview/src/components/ContactCard.tsx, packages/plugins/plugin-preview/src/components/OrganizationCard.tsx, packages/plugins/plugin-preview/tsconfig.json, packages/ui/react-ui-dnd/src/components/ResizeHandle.tsx, pnpm-lock.yaml
This PR:
- resolves #9123
- resolves #9124
- resolves #9125
https://github.com/user-attachments/assets/178c8786-3b65-4932-8beb-ab957e8d69b9
=> fix: Polish items, link to Org table

packages/plugins/plugin-inbox/package.json, packages/plugins/plugin-inbox/src/capabilities/react-surface.tsx, packages/plugins/plugin-inbox/src/components/Mailbox/Mailbox.stories.tsx, packages/plugins/plugin-inbox/src/components/Message/Message.tsx, packages/plugins/plugin-inbox/src/components/Message/MessageContainer.tsx, packages/plugins/plugin-inbox/src/components/Message/MessageHeader.tsx, packages/plugins/plugin-inbox/src/components/Related.tsx, packages/plugins/plugin-inbox/tsconfig.json, packages/plugins/plugin-preview/package.json, packages/plugins/plugin-preview/src/PreviewPlugin.tsx, packages/plugins/plugin-preview/src/components/OrganizationCard.tsx, pnpm-lock.yaml
This PR:
- increments the design of MessageHeader
- closes the global Popover when a link is clicked
https://github.com/user-attachments/assets/8acddfcb-2832-46f5-8c66-8bf9ea10ea61
https://github.com/user-attachments/assets/3be04c4b-abce-4bcc-86ef-f36362d6e871
=> fix: Additional Popover polish

packages/core/protocols/src/proto/dxos/edge/messenger.proto
- **Add connection state in Messenger proto**
- **Change protocol**
=> feat: Add connection state per peer to EDGE swarm protocol

packages/core/functions/src/handler.ts, packages/core/functions/src/types.ts, packages/plugins/plugin-automation/src/components/TriggerEditor/FunctionInputEditor.tsx, packages/plugins/plugin-automation/src/components/TriggerEditor/TriggerEditor.tsx, packages/plugins/plugin-script/src/templates/chess.ts, packages/plugins/plugin-script/src/templates/data-generator.ts, packages/plugins/plugin-script/src/templates/discord.ts, packages/plugins/plugin-script/src/templates/forex-effect.ts, packages/plugins/plugin-script/src/templates/forex.ts, packages/plugins/plugin-script/src/templates/gmail.ts
- fix merge issues with switch to Schema import
- revert Schema import for function templates which still depend on edge runtime to be updated
- finish updating trigger editor to handle the new trigger schema
=> fix: trigger editor

packages/plugins/plugin-deck/src/components/Plank/PlankHeading.tsx, packages/plugins/plugin-navtree/package.json, packages/plugins/plugin-navtree/src/components/NavTree/NavTree.tsx, packages/plugins/plugin-navtree/src/components/Sidebar/L0Menu.tsx, packages/plugins/plugin-navtree/src/components/Sidebar/L1Panel.tsx, packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx, packages/ui/react-ui-editor/src/styles/theme.ts, packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx, packages/ui/react-ui-menu/src/components/ToolbarMenu.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-theme/src/config/tokens/sememes-codemirror.ts, packages/ui/react-ui-theme/src/config/tokens/sememes-sheet.ts, packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts, pnpm-lock.yaml
This PR:
- resolves #9204
- fixes `CellEditor` alignment drift
- fixes a tabster bug
=> fix: Adjust surface colors

packages/core/echo/echo-schema/src/formats/types.ts, packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/sdk/schema/src/construction.ts, packages/sdk/schema/src/projection.test.ts, packages/sdk/schema/src/projection.ts, packages/sdk/schema/src/view.ts, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/lit-grid/src/types.ts, packages/ui/react-ui-form/src/components/Form/ArrayField.tsx, packages/ui/react-ui-form/src/hooks/useForm.ts, packages/ui/react-ui-grid/src/Grid/Grid.stories.tsx, packages/ui/react-ui-grid/src/Grid/Grid.tsx, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/FormCellEditor.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.stories.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.tsx, packages/ui/react-ui-table/src/model/table-presentation.ts, packages/ui/react-ui-table/src/util/index.ts, packages/ui/react-ui-table/src/util/schema.ts, packages/ui/react-ui-table/src/util/table.ts, packages/ui/react-ui/src/components/Popover/Popover.tsx
https://github.com/user-attachments/assets/dd42fcd2-d32a-49b1-bc63-a13a183e8b37
=> feat(tables): Array cell editing

.idea/codeStyles/Project.xml, packages/plugins/plugin-deck/src/capabilities/settings.ts, packages/plugins/plugin-deck/src/components/Plank/Plank.tsx, packages/plugins/plugin-deck/src/types.ts, packages/plugins/plugin-meeting/src/components/Call/Call.tsx, packages/plugins/plugin-meeting/src/components/CallContainer.tsx, packages/plugins/plugin-meeting/src/components/MeetingContainer.tsx, packages/plugins/plugin-meeting/src/components/Participant/ParticipantGrid.tsx, packages/plugins/plugin-meeting/src/components/ResponsiveGrid/ResponsiveGrid.stories.tsx, packages/plugins/plugin-meeting/src/components/ResponsiveGrid/ResponsiveGrid.tsx, packages/plugins/plugin-meeting/src/components/ResponsiveGrid/ResponsiveGridItem.tsx, packages/plugins/plugin-preview/src/PreviewPlugin.tsx
=> feat: hide members gallery when in fullscreen mode

packages/common/util/src/position.ts, packages/plugins/plugin-assistant/src/components/Toolbox/Toolbox.stories.tsx, packages/plugins/plugin-client/src/components/DevicesContainer.stories.tsx, packages/plugins/plugin-client/src/components/RecoveryCredentialsContainer.stories.tsx, packages/plugins/plugin-client/src/components/ResetDialog.stories.tsx, packages/plugins/plugin-deck/src/components/Plank/Plank.stories.tsx, packages/plugins/plugin-deck/src/components/Plank/Plank.tsx, packages/plugins/plugin-inbox/src/components/Mailbox/Mailbox.stories.tsx, packages/plugins/plugin-markdown/src/components/MarkdownPreview/MarkdownPreview.stories.tsx, packages/plugins/plugin-meeting/src/components/ResponsiveGrid/ResponsiveGrid.stories.tsx, packages/plugins/plugin-navtree/src/components/NavTree/NavTree.stories.tsx, packages/plugins/plugin-thread/src/components/Comments.stories.tsx, packages/ui/react-ui/src/components/Dialogs/Dialog.tsx
=> test: Plank story

packages/plugins/plugin-meeting/src/components/Call/Call.tsx, packages/plugins/plugin-meeting/src/components/CallContainer.tsx, packages/plugins/plugin-meeting/src/components/Lobby/Lobby.tsx, packages/plugins/plugin-meeting/src/components/Participant/ParticipantGrid.tsx, packages/plugins/plugin-meeting/src/components/Toolbar/Toolbar.tsx, packages/plugins/plugin-meeting/src/state/call-swarm-synchronizer.ts
=> fix(plugin-meeting): Fix UX bugs

packages/core/assistant/src/research/research.test.ts, packages/core/assistant/src/research/research.ts, packages/core/echo/echo-db/src/echo-handler/create.ts, packages/core/echo/echo-db/src/echo-handler/relations.ts, packages/core/echo/echo-schema/src/object/relation.ts, packages/plugins/plugin-assistant/src/stories/Query.stories.tsx, packages/plugins/plugin-assistant/src/stories/Research.stories.tsx, packages/plugins/plugin-assistant/src/stories/test-data.ts, packages/plugins/plugin-assistant/src/stories/testing.ts, packages/plugins/plugin-explorer/src/components/Graph/D3ForceGraph.tsx, packages/sdk/schema/src/common/index.ts, packages/sdk/schema/src/common/relations.ts, packages/sdk/schema/src/model/space-graph.ts, packages/ui/react-ui-graph/src/graph/graph-force-projector.ts, packages/ui/react-ui-graph/src/graph/graph-renderer.ts, packages/ui/react-ui-graph/src/graph/types.ts, packages/ui/react-ui-graph/src/hooks/useZoom.ts, packages/ui/react-ui-graph/styles/graph.css
=> feat: research graph

packages/sdk/observability/src/sentry/browser.ts, packages/sdk/observability/src/sentry/sentry-log-processor.ts
Fixes broken verbose breadcrumbs and noisy Unauthorized logging (HTTP Error with status code: 401 events).
=> fix: sentry

.vscode/settings.json, packages/core/echo/echo-db/src/proxy-db/echo-schema-registry.test.ts, packages/core/echo/echo-db/src/proxy-db/echo-schema-registry.ts, packages/core/echo/echo-pipeline/src/filter/filter-match.ts, packages/experimental/plexus/package.json, pnpm-lock.yaml, vitest.all.config.ts, vitest.workspace.ts
=> fix: Schema query

packages/plugins/plugin-kanban/src/components/KanbanViewEditor.tsx, packages/ui/react-ui-form/src/components/ViewEditor/ViewEditor.stories.tsx, packages/ui/react-ui-form/src/components/ViewEditor/ViewEditor.tsx, packages/ui/react-ui-form/src/translations.ts
=> fix(ViewEditor): Indicate readonly

packages/plugins/plugin-space/src/components/SpacePluginSettings.tsx, packages/plugins/plugin-space/src/translations.ts, packages/ui/react-ui-form/src/components/ControlSection/ControlSection.tsx, packages/ui/react-ui-theme/src/config/tokens/lengths.ts
=> fix: Space settings UI

packages/ui/lit-grid/src/dx-grid.lit-stories.ts, packages/ui/lit-ui/package.json, packages/ui/lit-ui/src/dx-avatar/dx-avatar.lit-stories.ts, packages/ui/lit-ui/src/dx-avatar/dx-avatar.ts, packages/ui/lit-ui/tsconfig.json, pnpm-lock.yaml, tools/lit-stories/.storybook/main.ts, tools/lit-stories/.storybook/preview.ts, tools/lit-stories/package.json, tools/lit-stories/project.json, tools/lit-stories/tsconfig.json
This PR:
- fixes `lit-stories` so they work again
- fixes the `dx-avatar` story
=> fix: Lit stories

packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/ui/lit-grid/src/dx-grid.pcss, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/CellValidationMessage.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.tsx, packages/ui/react-ui-table/src/hooks/index.ts, packages/ui/react-ui-table/src/hooks/useAddRow.ts, packages/ui/react-ui-table/src/model/table-model.ts, packages/ui/react-ui-table/src/model/table-presentation.ts, packages/ui/react-ui-table/src/util/table-buttons.ts
- Resolves https://github.com/dxos/dxos/issues/9034
https://github.com/user-attachments/assets/f5473368-0a72-418f-bb22-bff9d6429cfc
=> feat(tables): Transient new row for rows with required fields

packages/core/artifact-testing/src/experimental/experimental.test.ts, packages/core/assistant/src/blueprint/blueprint-binding.ts, packages/core/assistant/src/blueprint/blueprint.ts, packages/core/assistant/src/blueprint/index.ts, packages/core/assistant/src/extraction/extraction-llm-function/extraction-llm-function.ts, packages/core/assistant/src/index.ts, packages/core/assistant/src/research/research.ts, packages/core/assistant/src/session/session.test.ts, packages/core/assistant/src/session/session.ts, packages/core/conductor/src/nodes/gpt/node.ts, packages/core/conductor/src/sequence/machine.ts, packages/core/functions/src/testing/services.ts, packages/plugins/plugin-assistant/src/hooks/processor.ts, packages/plugins/plugin-transcription/src/segments-normalization/normalization.ts
=> feat: Blueprints (chat/artifact modules)

packages/ui/lit-grid/src/dx-grid.pcss, packages/ui/lit-ui/src/dx-tag-picker/dx-tag-picker.pcss, packages/ui/react-ui-editor/src/extensions/factories.ts, packages/ui/react-ui-grid/src/CellEditor/CellEditor.stories.tsx, packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx, packages/ui/react-ui-grid/src/CellEditor/GridCellEditor.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.tsx, packages/ui/react-ui-table/src/model/table-presentation.ts, packages/ui/react-ui-tag-picker/src/components/extension.ts, packages/ui/react-ui-theme/src/styles/layers/tag.css
This PR fixes spacing between `dx-grid` and `CellEditor`.
https://github.com/user-attachments/assets/14745f6e-d796-42dd-a50a-f3b14191d199
=> fix: Table tags content spacing

REPOSITORY_GUIDE.md, packages/apps/composer-app/vite.config.ts, packages/apps/testbench-app/vite.config.ts, packages/apps/todomvc/vite.config.ts, packages/sdk/examples/vite.config.ts, pnpm-lock.yaml
This PR does what it says on the tin.
=> fix: `*.pem` paths for moonrepo

packages/plugins/plugin-chess/src/components/ChessContainer.stories.tsx, packages/plugins/plugin-markdown/src/capabilities/react-surface.tsx, packages/plugins/plugin-markdown/src/components/MarkdownPreview/MarkdownPreview.stories.tsx, packages/plugins/plugin-markdown/src/components/MarkdownPreview/MarkdownPreview.tsx, packages/plugins/plugin-preview/src/testing/util.tsx, packages/plugins/plugin-table/src/capabilities/react-surface.tsx, packages/plugins/plugin-table/src/components/TablePreview.stories.tsx, packages/plugins/plugin-table/src/components/TablePreview.tsx, packages/plugins/plugin-table/src/components/index.ts, packages/ui/react-ui-board/src/components/Board/BoardCell.tsx, packages/ui/react-ui-stack/package.json, packages/ui/react-ui-stack/src/testing/CardContainer.tsx, packages/ui/react-ui-stack/src/testing/index.ts, packages/ui/react-ui-table/moon.yml, packages/ui/react-ui-table/package.json, packages/ui/react-ui-table/src/components/Table/Table.stories.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/testing/index.ts, packages/ui/react-ui-table/src/testing/useTestTableModel.ts, pnpm-lock.yaml
This PR:
- continues a resolution of [DX-239](https://linear.app/dxos/issue/DX-239/card-surfaces)
- implements `TablePreview` and Table cards
- creates `CardContainer` in a new `testing` entrypoint for `react-ui-stack` to simplify card story rigging
https://github.com/user-attachments/assets/91666f1c-e1a1-4da1-b225-b38e07ed1c2b
=> feat: Table cards

packages/ui/react-ui-stack/package.json, packages/ui/react-ui-theme/package.json
This PR fixes packaging in an attempt to fix e2e.
=> fix: Packaging.

packages/plugins/plugin-debug/src/components/SpaceGenerator/ObjectGenerator.tsx, packages/plugins/plugin-debug/src/components/SpaceGenerator/SpaceGenerator.tsx, packages/plugins/plugin-debug/src/components/SpaceGenerator/presets.ts
https://github.com/user-attachments/assets/4da49ef9-6b19-4bbf-b962-daa32f96af3d
Resolves DX-261
=> fix: support views in the generator

packages/core/echo/echo-schema/src/ast/annotation-helper.ts, packages/core/echo/echo-schema/src/object/accessors.ts, packages/plugins/plugin-markdown/src/components/MarkdownContainer.tsx, packages/plugins/plugin-space/src/util.tsx, packages/sdk/schema/src/common/person.ts, packages/sdk/schema/src/view/view.ts
=> fix: label annotations

packages/apps/composer-app/src/playwright/basic.spec.ts, packages/apps/composer-app/src/playwright/collaboration.spec.ts, packages/apps/composer-app/src/playwright/collections.spec.ts, packages/apps/composer-app/src/playwright/constants.ts, packages/apps/composer-app/src/playwright/stack.spec.ts, packages/core/echo/echo-schema/src/object/accessors.ts, packages/core/echo/echo/src/Obj.ts, packages/plugins/plugin-navtree/src/components/NavTreeContainer.tsx, packages/plugins/plugin-navtree/src/components/NavTreeItem/NavTreeItemColumns.tsx, packages/plugins/plugin-navtree/src/components/types.ts, packages/plugins/plugin-navtree/src/util.ts, packages/plugins/plugin-space/src/components/PopoverRenameObject.tsx, packages/plugins/plugin-space/src/util.tsx
also includes fixes to e2e tests to account for additional initial object
Resolves DX-314
=> fix: action + label reactivity in navtree

packages/core/echo/echo-schema/src/ast/annotations.ts, packages/plugins/plugin-debug/src/components/SpaceGenerator/SpaceGenerator.tsx, packages/sdk/schema/src/common/organization.ts, packages/sdk/schema/src/common/person.ts, packages/sdk/schema/src/common/task.ts, packages/sdk/schema/src/testing/generator.ts
=> feat: add task generator to debug plugin

packages/devtools/devtools/src/panels/echo/SpaceListPanel/SpaceListPanel.tsx, packages/plugins/plugin-space/src/capabilities/app-graph-builder.ts, packages/plugins/plugin-space/src/capabilities/react-surface.tsx, packages/plugins/plugin-space/src/capabilities/spaces-ready.ts, packages/plugins/plugin-space/src/components/RecordMain.tsx, packages/plugins/plugin-space/src/components/index.ts, packages/plugins/plugin-space/src/util.tsx, packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/plugins/plugin-table/src/translations.ts, packages/ui/react-ui-table/src/components/Table/RowActionsMenu.tsx, packages/ui/react-ui-table/src/model/table-model.ts
https://github.com/user-attachments/assets/2941e431-496b-408d-9ea2-1d7e8b793d70
Resolves DX-315
=> feat: 1-up view of a record

package.json, packages/common/effect/src/errors.ts, packages/common/effect/src/interrupt.test.ts, packages/plugins/plugin-assistant/src/components/Chat/Chat.tsx, packages/plugins/plugin-assistant/src/hooks/chat-processor.ts
=> feat: Cancel AI generation

packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/hooks/useAddRow.ts, packages/ui/react-ui-table/src/model/table-model.ts, packages/ui/react-ui-table/src/testing/useTestTableModel.ts
This PR:
- resolves DX-371
https://github.com/user-attachments/assets/c04511e4-027a-485b-a62d-a7b5b136f100
=> fix: Handle both draft and finished row insertion

packages/devtools/cli-next/src/commands/edge/functions/deploy/deploy.ts, packages/devtools/cli-next/src/commands/hub/index.ts, packages/devtools/cli-next/src/commands/hub/user/list/list.ts, packages/devtools/cli-next/src/commands/index.ts, packages/devtools/cli-next/src/commands/options.ts, packages/devtools/cli-next/src/commands/spaces/query/query.ts
also make options consistently kebab case
=> refactor: nested cli configs

packages/ui/react-ui-board/src/components/Board/Board.tsx, packages/ui/react-ui-stack/src/components/Stack/Stack.tsx
This PR:
- resolves DX-396
https://github.com/user-attachments/assets/569c3535-c0b9-4d6e-adc8-43393868fb19
=> fix: Contain Stack overscroll

packages/ui/react-ui-kanban/src/types/model.ts, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.tsx
This PR:
- resolves DX-372
- resolves DX-395
https://github.com/user-attachments/assets/cf7ea1a9-4bd9-4cc1-a30b-dcfbfb8fc1bd
https://github.com/user-attachments/assets/3715ec67-e131-4d83-bd63-5fef023cc61a
=> fix: Table & Kanban interactions

packages/core/echo/echo-db/src/automerge/repo-proxy.test.ts, packages/core/echo/echo-db/src/core-db/core-database.test.ts, packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts, packages/core/echo/echo-db/src/proxy-db/database.test.ts, packages/core/echo/echo-db/src/proxy-db/load-object.test.ts, packages/core/echo/echo-db/src/query/query.test.ts, packages/core/echo/echo-db/src/serializer.test.ts, packages/core/echo/echo-db/src/testing/index.ts, packages/core/echo/echo-db/src/testing/integration.test.ts, packages/core/echo/echo-db/src/testing/utils.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.test.ts, packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/automerge/leveldb-storage-adapter.ts, packages/core/echo/indexing/src/indexer.ts
=> fix: Fix AutomergeHost._afterSave race condition

packages/ui/react-ui-form/src/components/ViewEditor/ViewEditor.tsx, packages/ui/react-ui-form/src/translations.ts, packages/ui/react-ui-list/src/components/List/ListItem.tsx
https://github.com/user-attachments/assets/48257564-b32e-4a2d-80b1-3de00d626480
=> fix: Distinguish between mutability of view vs schema in `ViewEditor`

packages/ui/react-ui-grid/src/Grid/Grid.tsx, packages/ui/react-ui-table/src/components/Table/Table.tsx
https://github.com/user-attachments/assets/56fab5d1-c0ca-4667-bfdd-0d7878bec0c9
=> feat: Table cell copy & paste

packages/apps/composer-app/src-tauri/README.md, packages/apps/composer-app/src-tauri/tauri.conf.json, packages/plugins/plugin-native/package.json, packages/plugins/plugin-native/src/NativePlugin.tsx, packages/plugins/plugin-native/src/capabilities/index.ts, packages/plugins/plugin-native/src/capabilities/ollama.ts, packages/plugins/plugin-native/src/capabilities/window.ts, pnpm-lock.yaml
@wittjosiah please add basic instructions to the READEME re how to dev/run the tauri app.
=> feat: Memo window size for tauri app.

packages/plugins/plugin-table/src/types/types.ts
part of dx-421, I think this should resolve the first three items
=> fix: typename not required when creating a table

.junie/guidelines.md, packages/plugins/plugin-table/src/components/TableContainer.tsx, packages/ui/lit-grid/src/dx-grid.pcss, packages/ui/react-ui-table/package.json, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/FormCellEditor.tsx, packages/ui/react-ui-table/src/components/TableCellEditor/TableCellEditor.tsx, packages/ui/react-ui-table/src/model/table-presentation.ts, packages/ui/react-ui-table/tsconfig.json, pnpm-lock.yaml
This PR:
- resolves DX-422
- resolves DX-398
https://github.com/user-attachments/assets/a0babf80-e664-4515-9fcc-efc02fc288cb
=> feat: Table add row increment

packages/plugins/plugin-preview/src/capabilities/react-surface.tsx, packages/ui/lit-grid/src/dx-grid.ts, packages/ui/react-ui-form/src/components/Form/Form.tsx, packages/ui/react-ui-form/src/components/Form/FormContent.tsx, packages/ui/react-ui-kanban/src/components/Kanban.tsx, packages/ui/react-ui-kanban/src/model.ts
This PR resolves DX-428.
https://github.com/user-attachments/assets/ba84db54-e2f9-471c-8937-3eeac3c46365
=> feat: Apply `ProjectionModel` in `Form` where supported

.junie/guidelines.md, packages/sdk/schema/src/view/field.ts, packages/sdk/schema/src/view/projection-model.test.ts, packages/sdk/schema/src/view/projection-model.ts, packages/sdk/schema/src/view/view.ts, packages/ui/react-ui-form/src/components/Form/FormContent.tsx, packages/ui/react-ui-form/src/components/ViewEditor/ViewEditor.test.tsx, packages/ui/react-ui-form/src/components/ViewEditor/ViewEditor.tsx, packages/ui/react-ui-kanban/src/model.ts
This PR resolves DX-426
https://github.com/user-attachments/assets/5fce0518-141b-4bdf-83db-b65c8bff06ac
=> fix: `ViewEditor` hide/show field design, `Projection` & `ProjectionModel` hide/show ontology

packages/plugins/plugin-thread/src/calls-service.stories.tsx, packages/plugins/plugin-thread/src/calls/media-manager.ts, packages/plugins/plugin-thread/src/calls/util/calls-service.ts, packages/plugins/plugin-thread/src/calls/util/stub-media-streams.ts, packages/plugins/plugin-thread/src/components/Participant/Participant.tsx, packages/plugins/plugin-thread/src/hooks/index.ts, packages/plugins/plugin-thread/src/hooks/useBlackCanvasStreamTrack.tsx
- **Add black canvas stream story**
- **Fix waitForTransceiverToSendData**
=> fix: Make calls service wait for transceiver to start data exchange

packages/ui/lit-grid/src/dx-grid-axis-resize-handle.pcss, packages/ui/react-ui-form/src/util/field.ts, packages/ui/react-ui-table/src/components/Table/Table.tsx, packages/ui/react-ui-table/src/model/table-presentation.ts, packages/ui/react-ui-table/src/util/table-buttons.ts
https://github.com/user-attachments/assets/1315f43d-2e43-443b-945e-f1709743576d
=> fix: Table formatting fix & header cell design increment

packages/devtools/cli-next/src/bin.ts, packages/devtools/cli-next/src/commands/dx.ts, packages/devtools/cli-next/src/commands/repl.ts, packages/devtools/cli-next/src/commands/smoke.test.ts
https://github.com/user-attachments/assets/8d0cf515-2755-4821-8d8d-a0d85551d798
=> feat: add repl

packages/apps/composer-app/src-tauri/src/lib.rs, packages/plugins/plugin-native/src/capabilities/updater.ts
=> fix: ai chat failing

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts, packages/core/echo/echo-pipeline/src/db-host/data-service.ts, packages/core/echo/echo-pipeline/src/db-host/echo-host.ts, packages/core/protocols/src/proto/dxos/echo/service.proto, packages/devtools/devtools/src/components/performance/panels/EdgePanel.tsx, packages/devtools/devtools/src/components/performance/panels/SyncStatus/Space.tsx, packages/devtools/devtools/src/components/performance/panels/SyncStatus/SyncStatus.stories.tsx, packages/devtools/devtools/src/components/performance/panels/SyncStatus/SyncStatus.tsx, packages/plugins/plugin-thread/src/components/CallDebugPanel.tsx, packages/sdk/client/src/echo/util.ts
- **Fix CallDebugPanel**
- **refactor: Refactor EDGE sync panel**
=> refactor: Refactor EDGE sync panel

packages/apps/composer-app/moon.yml, packages/plugins/plugin-assistant/src/stories/Chat.stories.tsx, packages/plugins/plugin-inbox/src/functions/gmail-sync.ts, packages/plugins/plugin-inbox/src/functions/summarize.ts, packages/plugins/plugin-sketch/moon.yml
=> chore: missing sketch assets

.env.1password
=> chore: update keys

packages/plugins/plugin-assistant/package.json, packages/plugins/plugin-assistant/src/components/ChatPrompt/ChatOptions.tsx, packages/ui/react-ui-searchlist/package.json, packages/ui/react-ui-searchlist/src/components/Listbox.stories.tsx, packages/ui/react-ui-searchlist/src/components/Listbox.tsx, packages/ui/react-ui-searchlist/src/components/index.ts, pnpm-lock.yaml
This PR creates the `Listbox` component, which can be promoted to be an exemplar of `react-ui`’s `List`, but which starts in `react-ui-searchlist` here due to functional relation.
=> feat: Listbox

packages/plugins/plugin-inbox/src/components/Mailbox/MailboxContainer.tsx, packages/plugins/plugin-inbox/src/components/Mailbox/model/mailbox-model.ts, packages/plugins/plugin-inbox/src/components/util.ts
This PR:
- resolves DX-540
- adds prototype of text filtering on Mailbox messages
https://github.com/user-attachments/assets/fc5c32e4-e1a9-43ee-8334-d3d341edb4c9
=> feat: Arbitrary text filters in Mailbox
