dxos/dxos

package.json
patches/process@0.11.10.patch
pnpm-lock.yaml

Presently, when injecting env vars into a vite app (e.g., https://github.com/dxos/dxos/blob/main/packages/apps/tasks-app/vite.config.ts#L25) the result is that process.env is an empty object. This is because after the transition to `@dxos/node-std` the `process` shim is overwriting these. This patches the `process` browser shim to allow vite to `define` env vars inside process by shimming into an existing `process` global if it exists.

fix: vite injected env vars missing

---

packages/apps/composer-app/src/Routes.tsx
packages/apps/tasks-app/src/Routes.tsx

`useRoutes` is a hook and causes React to generate a warning when DX_VAULT is false because the number of hooks in the `Routes` component changes when an identity is created.

fix: react hook warning in monolithic apps

---

packages/apps/patterns/react-ui/src/layouts/PanelSidebar/PanelSidebar.tsx
packages/experimental/kai/src/app/pages/AppBar.tsx

Tailwind doesn't support string interpolation in utility classes — we can either export a full string literal or use inline styles, if a property like this should be shared.

fix: Sidebar layout & motion

---

packages/apps/patterns/react-ui/src/layouts/PanelSidebar/PanelSidebar.tsx
packages/experimental/kai/src/app/AppBar.tsx
packages/experimental/kai/src/app/Frames.tsx
packages/experimental/kai/src/app/Sidebar.tsx

This PR lets `kai`’s `AppBar` remain on top and displace the top edge of the sidebar.
https://user-images.githubusercontent.com/855039/212783998-812cdd3d-0cdc-495e-9fb5-e0ce56241e4c.mp4

fix: Topbar & Sidebar coordination in `kai`

---

.circleci/config.yml
packages/experimental/kai/dx.yml

Kai build has been failing when publishing https://app.circleci.com/pipelines/github/dxos/dxos/5375/workflows/9163c957-70c5-4fc7-894d-39d977adf8d7/jobs/8057?invite=true#step-106-339

ci: update kai build command

---

packages/apps/patterns/react-ui/src/layouts/PanelSidebar/PanelSidebar.tsx
packages/experimental/kai/src/app/AppBar.tsx
packages/experimental/kai/src/app/Frames.tsx

This PR fixes `AppBar` and `FrameSelector` heights in `kai` and allows the OS’s `PanelSidebar`’s main content area to be styled for layout purposes.

fix: Stabilize layout in `kai`

---

packages/common/react-components/src/config/tailwind.ts
packages/experimental/kai/README.md
packages/experimental/kai/src/app/App.tsx
packages/experimental/kai/src/app/Sidebar.tsx
packages/experimental/kai/src/bots/research-bot.test.ts
packages/experimental/kai/src/components/Table.tsx
packages/experimental/kai/src/containers/TaskList.tsx
packages/experimental/kai/src/containers/frames/TableFrame.tsx
packages/experimental/kai/style.css
packages/experimental/kai/tailwind.js

fix: cosmetic improvements in kai

---

docs/src/components/RenderReactDemo.vue
docs/src/components/Showcase.vue

Renders "loading" in the showcase preview box if the code takes more than 300ms to load.

docs: add loader for showcase preview

---

packages/experimental/hypercard/project.json

These executors don't work without appropriate files and are causing failures because some get run in CI.

chore(hypercard): disable unimplemented executors

---

packages/common/react-components/src/components/List/List.tsx

I'll continue chatting with the Radix team to see if I might have missed something in `Collection`’s implementation in List.

fix: Remove `Collection` from List so it doesn’t log `SlotClone` errors

---

.github/workflows/release-please.yml

The way this job is currently setup, `production` and `main` diverge because of merge commits. This causes the job to fail when doing a hotfix after there have been a number of releases. This change stops using merge commits and only ever fast-forwards `main` and `production` from the release branches; this ensures that they maintain the same history. `main` continues to fast-forward on every commit, ensuring that updates to the release are ported back to `main`, while `production` is only fast-forwarded once the release is created. By using fast-forward only, `production` is essentially just a time-delayed version of `main`. One caveat to this flow is that if there is ever a conflict the CI jobs will fail and need to be resolved manually, however this was also the case before as well.

ci: update release please git mechanics

---

packages/common/react-components/src/components/Input/Input.tsx
packages/experimental/kai/src/frames/Note/NoteTile.tsx

Don’t set defaults in any component’s controlled state props, e.g. `value` `defaultValue` or `onChange`. Instead, set these defaults downstream where the component is used.

fix: Input value

---

.github/workflows/release-please.yml

Git was unable to fast-forward release onto `main`. This uses a merge commit when going back into main instead. Theory is that this will be okay because production wouldn't diverge as it would end up in it's history later (on the next release).

ci: tweak release please main merge

---

packages/apps/patterns/react-composer/package.json
packages/apps/patterns/react-composer/src/components/Composer/Composer.tsx
pnpm-lock.yaml

This PR styles known Node and Mark extensions in `react-composer` using Tailwind.
Resolves #2636.
Special attention was given to list item marker alignment to support numbered outlines that align neatly.

fix(react-composer): Styles

---

packages/apps/composer-app/project.json
packages/apps/composer-app/vite.config.ts
packages/apps/halo-app/src/vault/main.ts
packages/apps/halo-app/vite.config.ts
packages/sdk/client/src/packlets/client/iframe-service-proxy.ts

- `/vault.html` is what the halo service worker precaches and `/vault.html?shell=false` misses the cache
- the fix here is to use `/vault.html#disableshell` instead because it does not cause a cache miss
- it's still unclear to me why the cache miss causes `/vault.html?shell=false` to return the `/index.html` document rather than hitting the server for the document (this is reproducible on localhost, it's not due to kube behaviour)

fix: halo vault pwa cache

---

packages/apps/composer-app/src/pages/DocumentPage.tsx
packages/apps/patterns/react-composer/src/components/Markdown/Markdown.tsx

The Markdown composer now occupies the full width of Composer app’s `DocumentPage`. `react-composer` also applies soft wrapping by default.

feat(composer-app): Layout adjustments

---

packages/ui/aurora-types/package.json
packages/ui/aurora/src/components/Button/Button.tsx

Align `aurora-types` packaging with others.
```
"main": "dist/lib/node/index.cjs",
"browser": {
"./dist/lib/node/index.cjs": "./dist/lib/browser/index.mjs"
},
```

fix(aurora-types): Packaging.

---

packages/core/echo/echo-schema/src/typed-object.test.ts
packages/core/echo/echo-schema/src/typed-object.ts

closes https://github.com/dxos/dxos/issues/4339

fix: Object.keys on Expandos

---

tools/stories/project.json

This PR fixes an issue where running/building storybooks would not cause `nx` to check if packages with stories or their dependencies needed fresh builds.

fix(stories): List task dependencies for each of the Storybook profiles

---

packages/apps/plugins/plugin-files/src/components/LocalFileMainPermissions.tsx
packages/apps/plugins/plugin-github/src/components/EmbeddedMain/GfmPreview.tsx
packages/apps/plugins/plugin-github/src/components/GithubEchoResolverProviders/ResolverTree.tsx
packages/apps/plugins/plugin-layout/src/components/ContentEmpty.tsx
packages/apps/plugins/plugin-layout/src/components/ContentFallback.tsx
packages/apps/plugins/plugin-layout/src/components/Fallback.tsx
packages/apps/plugins/plugin-registry/src/components/PluginList.tsx
packages/apps/plugins/plugin-script/package.json
packages/apps/plugins/plugin-script/src/components/ScriptEditor/ScriptEditor.tsx
packages/apps/plugins/plugin-space/src/components/FolderMain.tsx
packages/apps/plugins/plugin-space/src/components/MissingObject.tsx
packages/apps/plugins/plugin-space/src/components/SpaceMain.tsx
packages/apps/plugins/plugin-space/src/components/SpacePresence.tsx
packages/sdk/react-shell/src/components/CompoundButton/CompoundButton.tsx
packages/sdk/react-shell/src/components/InvitationList/InvitationListItem.tsx
packages/sdk/react-shell/src/components/Panel/StepHeading.tsx
packages/sdk/react-shell/src/panels/JoinPanel/steps/InvitationAccepted.tsx
packages/sdk/react-shell/src/panels/SpacePanel/steps/SpaceManager.tsx
packages/sdk/react-shell/src/steps/InvitationManager.tsx
packages/ui/react-appkit/src/components/CompoundButton/CompoundButton.tsx
packages/ui/react-appkit/src/components/Heading/Heading.tsx
packages/ui/react-ui-editor/src/components/TextEditor/themes/default.ts
packages/ui/react-ui-navtree/src/components/navtree-fragments.ts
packages/ui/react-ui-theme/package.json
packages/ui/react-ui-theme/src/config/tailwind.ts
packages/ui/react-ui-theme/src/styles/components/dialog.ts
packages/ui/react-ui-theme/src/theme.css
packages/ui/react-ui-theme/src/util/mx.ts
packages/ui/react-ui/src/playground/Typography.stories.tsx
pnpm-lock.yaml

This PR:
- Changes the monospace font to JetBrains Mono
- Adds a typography story to `react-ui`.
- Removes the `display` font family and its utility classnames, removes Space Grotesk from dependencies
- Adjusts FontSource dependencies and imports to target the right assets
- Fixes font synthesis and utility layer rules to improve weight + italic/oblique support
- Fixes a missing monospace `fontFamily` property for CodeMirror

refactor: Finish changing fonts, tidy-up typography

---

packages/apps/composer-app/src/playwright/app-manager.ts
packages/ui/react-ui-navtree/src/components/NavTreeItem.tsx
packages/ui/react-ui-navtree/src/components/NavTreeItemAction.stories.tsx
packages/ui/react-ui-navtree/src/components/NavTreeItemAction.tsx

Resolves #4858.
This PR moves non-toolbar actions into a `ContextMenu` for which `NavTreeItemHeading` is the trigger, replacing the `DropdownMenu` with the `DotsThreeVertical` trigger.
https://github.com/dxos/dxos/assets/855039/847bd492-0f4e-4acf-9de9-fd0962425734
https://github.com/dxos/dxos/assets/855039/190c2c50-2257-4acc-937d-4c6bf5d0ce56

feat(react-ui-navtree): Add context menu to `NavTreeItem`s

---

packages/apps/plugins/plugin-navtree/src/components/CommandsDialog.tsx
packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
packages/apps/plugins/plugin-space/src/components/PopoverRemoveObject.tsx
packages/apps/plugins/plugin-space/src/components/index.ts
packages/apps/plugins/plugin-space/src/util.tsx
packages/apps/plugins/plugin-theme/src/translations/en-US/os.ts

The keyboard shortcut of command-delete to delete an item has no confirmation or recovery. Very easy to accidentally delete an item and have no way of getting it back. command-delete is also the shortcut for "delete this line to the beginning of the line" in macOS, so I use it often.
https://github.com/dxos/dxos/assets/27258/1cd35766-8b26-487a-974b-ffb7974cb718

feat(composer): Cmd-shift-delete to delete objects

---

.circleci/scripts/publish.sh

If remote source is set then client will start in deprecated iframe mode.

ci: stop setting remote source in publish script

---

packages/ui/react-ui-navtree/src/components/NavTreeItemAction.tsx

This PR fixes a typo which reversed conditions in a ternary expression, causing the context menu not to render when it needed to.

fix(react-ui-navtree): Fix ternary expression typo

---

packages/apps/plugins/plugin-github/src/GithubPlugin.tsx
packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/apps/plugins/plugin-markdown/src/util.tsx
packages/apps/plugins/plugin-presenter/src/PresenterPlugin.tsx
packages/apps/plugins/plugin-presenter/src/components/MarkdownSlideMain.tsx

The type check for Markdown content changed, breaking Documents in presenter plugin. I added an alternative type check, but I'm sure it can be improved.
fixes https://github.com/dxos/dxos/issues/5194

fix(plugin-presenter): render documents

---

packages/ui/react-ui-editor/src/themes/default.ts

Widget buffers are a thing CodeMirror inserts into the editable DOM to prevent a bunch of browser-contenteditable misbehaviors when the cursor is next to uneditable content, such as invisible cursors, weird cursor motion, and IME input weirdly interacting with the widgets. They should not be set to `display: none`.
Issue https://github.com/dxos/dxos/issues/5184

fix(react-ui-editor): Don't hide widget buffers

---

packages/apps/plugins/plugin-help/src/HelpPlugin.tsx
packages/apps/plugins/plugin-help/src/components/Shortcuts/Key.tsx
packages/apps/plugins/plugin-help/src/components/Shortcuts/ShortcutsDialog.tsx
packages/apps/plugins/plugin-help/src/components/Shortcuts/ShortcutsHints.tsx
packages/apps/plugins/plugin-help/src/components/Shortcuts/ShortcutsList.tsx
packages/apps/plugins/plugin-help/src/components/Shortcuts/ShortcutsSection.tsx
packages/apps/plugins/plugin-help/src/components/Shortcuts/index.ts
packages/apps/plugins/plugin-help/src/components/Shortcuts/styles.ts
packages/apps/plugins/plugin-layout/src/components/ContentEmpty.tsx
packages/apps/plugins/plugin-layout/src/components/MainLayout.tsx
packages/apps/plugins/plugin-space/src/components/SpaceMain.tsx

Resolves #5143. Resolves #5247.
This PR removes the keyboard shortcuts `hints` role from `MainLayout` and adds a `keyshortcuts` role to FRE pages where `HelpPlugin` renders the same `ShortcutsList` it renders in its dialog.

feat(plugin-help): Display shortcuts list on FRE pages

---

packages/ui/react-ui-editor/src/components/TextEditor/comments.stories.tsx
packages/ui/react-ui-editor/src/extensions/comments.ts

Issue https://github.com/dxos/dxos/issues/5040
This implements the feature where cutting and pasting comments will move them in the text. Requires consumers to provide an onMove callback Wires up the comments story to use this, but does not do this for the threads plugin yet.

feat: Move comments when cut and pasted

---

packages/apps/plugins/plugin-navtree/src/components/NavBarStart.tsx
packages/apps/plugins/plugin-space/src/util.tsx

Resolves #5141. Resolves #5240.
This PR hides the parent space in the `NavBarStart` in `sm` breakpoints, and also removes the icon for Personal Space.

fix: Polish NavBar and NavTree content

---

packages/apps/plugins/plugin-client/src/ClientPlugin.tsx

This PR removes code from the client plugin which prompted for automatic migration from vault identity. This proved to not be particularly stable and not valuable enough at this point in time to spend the time stabilizing. It's being removed in favour of including steps for doing a manual migration in the docs.
Relates to #5315

chore(plugin-client): remove automatic vault migration code

---

.circleci/config.yml

Ramdisk counts against CircleCI memory limit. CircleCI documentation suggests that disk IO contention may slow down builds, which page cache doesn't help with apparently.

fix: disable CircleCI ramdisk

---

packages/apps/composer-app/src/main.tsx

This PR fixes a misconfiguration in Composer where it starts in monolithic mode by default rather than worker mode.

fix(composer-app): configure to use worker by default

---

packages/core/echo/echo-schema/src/automerge/automerge-object.ts
packages/core/echo/echo-schema/src/object/subscription.test.ts
packages/core/echo/echo-schema/src/object/typed-object.ts

Echo object update notification fixes #4882
* Automerge object update notification was broken because `objectIsUpdated` was getting undefined when accessing `_id`, added the key to the "invalid" key set.
* Automerge wasn't tested with subscriptions, updated the test file. Also added two new tests for nested object and array mutation updates.
* TypedObject nested object update was triggering notification multiple times, fixed with an update depth counter.

fix: nested echo objects update notifications

---

packages/sdk/client/src/services/worker-client-services.ts

This will disambiguate logs coming from same domain worker vs vault worker.

fix(client): change worker services log bridge prefix

---

packages/sdk/react-client/src/testing/ClientRepeater.tsx

Child components were being rendered to early because clients were being set as soon as clients were initialized even if identity and spaces are being created. This works fine if child components handle the cases where those aren't available, but they shouldn't have to do that since this is a utility for testing intermediate components.

fix(react-client): ClientRepeater should not render component until setup is complete

---

packages/ui/react-ui-theme/package.json
packages/ui/react-ui-theme/src/config/colors.ts
pnpm-lock.yaml

This PR changes the procedural color dependency of `react-ui-theme` to use a package we control. Resolves #5487.

chore(react-ui-theme): Use fork of `colors`

---

packages/ui/react-ui-theme/package.json
pnpm-lock.yaml

This PR follows-up on #5525, which used a fork of `colors` but that fork did not provide CJS which is needed for the `nx` dev server. Upgrading fixes the issue.

chore(react-ui-theme): Upgrade colors to fix a CJS issue

---

packages/apps/plugins/plugin-layout/src/LayoutPlugin.tsx

Addendum to fix for #5159
Ensure that `context` surface is always provided a component when the layout is rendered.

fix(plugin-layout): complementary sidebar empty when nothing active

---

packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx

This fix ensures that if a comment is cut from a document that the title of the thread isn't blanked out.

fix(plugin-thread): don't update thread title if comment is deleted

---

packages/sdk/client/src/services/client-services-factory.tsx

This PR ensures that if `SharedWorker` is not available that the client falls back to monolithic mode. This should only affect Android devices, worker mode appears functional now on iOS 🎉

fix(client): only use worker client services if shared worker is available

---

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx

This PR makes some minor adjustments to `EditorMain`:
- uses `ring-inset` so a `div role=none` can be removed
- uses `grid-rows-subgrid` to stretch `.cm-editor` to the block size of the root if it’s smaller
- removes overscroll rules that were causing issues keeping up with the cursor
https://github.com/dxos/dxos/assets/855039/7f11619b-78b6-4856-b72b-b09e90463f52

fix(plugin-markdown): `EditorMain` grid layout

---

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx
packages/ui/react-ui-editor/src/components/TextEditor/hooks.stories.tsx
packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.stories.tsx
packages/ui/react-ui-editor/src/index.ts
packages/ui/react-ui-editor/src/styles/layout.ts

Resolves #5620.
https://github.com/dxos/dxos/assets/855039/a644792c-2e9d-42a3-ab48-23813b7a05ea
https://github.com/dxos/dxos/assets/855039/ca634c96-781d-450f-9427-b2fadcb78ad0
https://github.com/dxos/dxos/assets/855039/2efc99da-a871-4036-84aa-d8cb3ac2080f

fix(react-ui-editor): Export layout fragments, remove unneeded styles

---

packages/apps/plugins/plugin-layout/src/LayoutPlugin.tsx
packages/apps/plugins/plugin-layout/src/components/LayoutSettings.tsx
packages/apps/plugins/plugin-layout/src/helpers.ts
packages/apps/plugins/plugin-layout/src/translations.ts
packages/apps/plugins/plugin-layout/src/types.ts

This PR hides the native app redirect behind a setting. It didn't seem consequential to land that change given that we haven't shipped the app yet, but if you've built the app locally it's hard to avoid. Until the app is stable and we have ways of avoiding this in dev, etc. it should be disabled by default.

feat(plugin-layout): add setting for native app redirect

---

packages/apps/plugins/plugin-layout/src/components/ContextPanel.tsx
packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx
packages/apps/plugins/plugin-thread/src/components/Chat.stories.tsx
packages/apps/plugins/plugin-thread/src/components/ChatContainer.tsx
packages/apps/plugins/plugin-thread/src/components/CommentContainer.tsx
packages/apps/plugins/plugin-thread/src/components/Comments.stories.tsx
packages/apps/plugins/plugin-thread/src/components/CommentsContainer.tsx
packages/apps/plugins/plugin-thread/src/components/ThreadMain.tsx
packages/apps/plugins/plugin-thread/src/components/index.ts
packages/apps/plugins/plugin-thread/src/components/types.ts
packages/ui/react-ui-thread/src/Thread/Thread.tsx

Resolves #5608.
This PR devolves `ThreadContainer` into `ChatContainer` and `CommentContainer` (likewise renaming `ThreadsContainer` to `CommentsContainer`) since the design diverges.
The new `ChatContainer` gets the expected layout: messages scroll backwards from a compose box pinned to the bottom.
Getting scroll to reverse is still a nuanced affair, so please let me know if you encounter issues.
https://github.com/dxos/dxos/assets/855039/38c6ceb9-ad1a-4370-9653-9aed3c7a7e42
https://github.com/dxos/dxos/assets/855039/26688a30-3cfe-443e-947e-8e73765aa533
https://github.com/dxos/dxos/assets/855039/67481b46-d069-482e-b7b7-963e3b823a19

fix(plugin-thread): Chat layout

---

packages/apps/plugins/plugin-space/src/types.ts
packages/apps/plugins/plugin-space/src/util.tsx

Has already been superceded by save/load.

chore: finish removing import/export

---

packages/apps/plugins/plugin-thread/src/components/CommentContainer.tsx
packages/apps/plugins/plugin-thread/src/components/CommentsContainer.tsx

This PR adjusts the target position of CommentContainer’s call to `scrollIntoView`.
Resolves [#5401](https://github.com/dxos/dxos/issues/5401).
https://github.com/dxos/dxos/assets/855039/0c674100-8394-49b8-9510-7140a19e236b

fix(plugin-thread): Refine scrollIntoView

---

packages/apps/composer-app/index.html
packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx

Resolves #5659.
This PR moves `EditorMain`’s spacing to `cm-scroller` from its parent `cm-editor`.
This PR also sets `overflow-visible` on `cm-scroller`
- this was preventing presence names from fully displaying even when there was space
- other child elements may have similar needs and are unable to portal out of the editor
- `overflow-hidden` should have no other effects since `cm-scroller` does not need to fill its parent’s height
- clicking in the overscroll still focuses the contenteditable in testing, including in iOS
This PR also adds `interactive-widget=resizes-content` to the viewport meta, which should improve the experience for users of devices with a virtual keyboard that support it (not iOS unfortunately). [More info …

fix(plugin-markdown): Move spacing to `cm-scroller`, make its overflow visible.

---

packages/apps/plugins/plugin-client/src/ClientPlugin.tsx

resolves https://github.com/dxos/dxos/issues/5568
Device invitation would leave composer tree blank because [early return](https://github.com/dxos/dxos/blob/98795677db55a5999563be026ca22ee20568a679/packages/apps/plugins/plugin-space/src/SpacePlugin.tsx#L337)
`client.spaces.isReady.get()` was returning `false`
It all happened because [this line was never reached](https://github.com/dxos/dxos/blob/98795677db55a5999563be026ca22ee20568a679/packages/apps/plugins/plugin-client/src/ClientPlugin.tsx#L99)

fix: Fix device invitation

---

.circleci/config.yml
packages/apps/composer-app/src/playwright/app-manager.ts
packages/apps/composer-app/src/playwright/collaboration.spec.ts
packages/apps/plugins/plugin-space/src/components/SpaceMain/SpaceMain.tsx
packages/apps/plugins/plugin-space/src/components/SpaceMain/SpaceMembersSection.tsx
packages/apps/plugins/plugin-space/src/util.tsx
tools/ridoculous/project.json

This Pull Request resolves the current e2e test failures on main.
- test changes
- instead of waiting for a document after an invitation, wait for the space to be ready
- tell if the space is ready by whether the name input is enabled
- once space and document has synced, open the document
- include "add to space" on the space page
- hide invitations section until space is ready

test(composer-app): update collab e2e tests to handle new space page

---

packages/apps/composer-app/src/playwright/app-manager.ts
packages/apps/composer-app/src/playwright/collaboration.spec.ts
packages/apps/plugins/plugin-space/src/util.tsx
packages/apps/plugins/plugin-thread/src/components/ChatContainer.tsx
packages/apps/plugins/plugin-thread/src/components/CommentContainer.tsx
packages/apps/plugins/plugin-thread/src/components/MessageContainer.tsx
packages/ui/react-ui-thread/src/Message/Message.tsx

This Pull Request fixes an issue where if multiple comment threads are on screen at the same time the focus always jumps back to the first one.
- thread message editors needed their extensions memoized too

fix(plugin-thread): multiple comments working again

---

packages/apps/plugins/plugin-native/src/NativePlugin.tsx

Resolves an issue where the app wasn't starting up on iOS because the set menu call never resolved.

fix(plugin-native): app starts up on iOS

---

packages/core/echo/echo-schema/src/automerge/automerge-db.ts
packages/core/echo/echo-schema/src/hypergraph.ts

* hypergraph wasn't subscribing to automerge update events, only to legacy echo db events
* lookupLink wasn't registering resolution callback for local references, only cross-space references

fix(echo): no callback invoked on separate-automerge doc resolution

---

packages/apps/plugins/plugin-debug/src/components/DebugSettings.tsx
packages/apps/plugins/plugin-debug/src/translations.ts
packages/core/echo/echo-schema/src/automerge/automerge-context.ts
packages/core/echo/echo-schema/src/automerge/automerge-db.test.ts
packages/core/echo/echo-schema/src/automerge/automerge-db.ts
packages/core/echo/echo-schema/src/testing/testing.ts
packages/core/protocols/src/proto/dxos/config.proto
packages/sdk/client/src/client/client.ts
packages/sdk/client/src/echo/space-list.ts

Adds a toggle in debug plugin that enables automerge space fragmentation. 
When enabled and reloaded new text objects will be created in separate automerge documents.

feat: debug plugin AM space fragmentation toggle

---

packages/apps/plugins/plugin-debug/src/DebugPlugin.tsx

A browser visiting DevTools as provided by `plugin-debug` if reloaded will go to the devtools entrypoint as they shared the same name.

fix: debug-plugin devtools clash with entrypoint

---

.idea/dxos.iml
packages/ui/react-ui-mosaic/src/mosaic/DragOverlay.tsx

Resolves #5082.
This PR adjusts DragOverlay to avoid trying to resolve an overlay for a foreign drop area when the operation is rejected anyway.

fix(react-ui-mosaic): Use active DragOverlay when operation is rejected

---

packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.tsx
packages/ui/react-ui-editor/src/index.ts
packages/ui/react-ui-editor/src/translations.ts

Resolves #5750.
This PR adds tooltips to the `Toolbar` of `react-ui-editor`.
This PR also exports translations from that package and uses them in `plugin-markdown`.
https://github.com/dxos/dxos/assets/855039/5679f058-868f-426f-af2f-ba0ebfb08a72

fix(react-ui-editor): Add tooltips to toolbar

---

packages/apps/composer-app/src/components/ResetDialog.tsx
packages/sdk/client/src/index.ts

This pull request is fixing the config for the reset dialog window to use the same storage as the Client

fix: Fix reset dialog

---

packages/core/echo/echo-schema/src/automerge/automerge-db.test.ts
packages/core/echo/echo-schema/src/automerge/automerge-db.ts
packages/core/echo/echo-schema/src/automerge/automerge-doc-loader.test.ts
packages/core/echo/echo-schema/src/automerge/automerge-doc-loader.ts
packages/core/echo/echo-schema/src/legacy-database.ts

Partially addresses https://github.com/dxos/dxos/issues/5557
Stop loading all automerge documents eagerly on startup, instead:
* Try to load a document when an object is referenced but not present.
* When a link appears in space root, start loading the linked document if the object linked to it was previously requested.

feat(echo): enabled text object lazy loading

---

packages/apps/composer-app/index.html
packages/apps/plugins/plugin-layout/src/components/MainLayout.tsx
packages/apps/plugins/plugin-navtree/src/components/NavTreeFooter.tsx
packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx
packages/apps/plugins/plugin-thread/src/components/ChatContainer.tsx
packages/apps/plugins/plugin-thread/src/components/CommentsContainer.tsx
packages/ui/react-ui-navtree/src/components/NavTreeItemAction.tsx
packages/ui/react-ui-theme/src/styles/components/main.ts

Resolves #5794. Resolves #5795. Resolves #5801. Resolves #5242.
This PR makes various improvements for mobile devices:
- Changes theme color to respond to preferred palette, using same color as applied to `html`
- Adds extra spacing to the notch and to NavTreePlugin’s footer for the navigational sidebar
- Harmonizes both sidebar icons.
- Fixes a z-index issue.
- Only opens c11y sidebar implicitly if viewport min-width is 768px.
https://github.com/dxos/dxos/assets/855039/b5c4cba7-d4e1-44ba-8cdf-8e334f1c05ac
https://github.com/dxos/dxos/assets/855039/c5caaa32-693f-4595-b668-c7d498ed53b4

fix: Layout for iOS devices

---

.circleci/config.yml

bundle errors on e2e jobs like https://app.circleci.com/pipelines/github/dxos/dxos/20822/workflows/57450701-8e4d-4607-8401-f23744f179bf/jobs/43804 presumably failing due to OOM

chore: adjust bundling parallelism for e2e tests

---

packages/apps/plugins/plugin-navtree/src/components/HaloButton.tsx
packages/apps/plugins/plugin-navtree/src/components/NotchStart.tsx
packages/apps/plugins/plugin-space/src/components/SpacePresence.tsx
packages/core/protocols/src/proto/dxos/halo/credentials.proto
packages/sdk/client-services/src/packlets/spaces/spaces-service.ts
packages/sdk/shell/src/components/IdentityList/IdentityListItem.tsx
packages/sdk/shell/src/panels/IdentityPanel/IdentityPanel.tsx
packages/sdk/shell/src/panels/IdentityPanel/steps/ProfileForm.tsx
packages/sdk/shell/src/panels/JoinPanel/steps/IdentityAdded.tsx

Followup to #5811 which fixes a couple small issues:
- always pass through whole profile from the space service
- don't hardcode emoji/hue in profile proto

fix(client-services): always pass through whole profile

---

docs/dx.yml

forgot to update `dx.yml` in docs to point to `content` instead of `docs`

fix: docs deploy config

---

packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts

Reverts one line from #5820 which was causing heading control characters no to be rendered in the editor when starting a new line.

fix(react-ui-editor): fix markdown headings

---

packages/apps/plugins/plugin-github/src/components/GithubEchoResolverProviders/DocumentTreeItem.tsx
packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/apps/plugins/plugin-markdown/src/meta.tsx
packages/ui/react-ui-deck/src/components/PlankHeading/PlankHeading.stories.tsx
packages/ui/react-ui-deck/src/components/PlankHeading/PlankHeading.tsx

Resolves #5885.
This PR adds a small, partly opaque horizontal bar to `PlankHeading.Button` to indicate it has a menu.
This PR also changes all Document icons to use `TextAa`.
We also explored ways this signifier could be added to the tree:

feat: Menu annotation

---

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts
packages/core/echo/indexing/src/index-metadata-store.test.ts
packages/core/echo/indexing/src/index-metadata-store.ts
packages/core/echo/indexing/src/indexer.test.ts

* Remove unnecessary `cancelWithContext` that gets lots of listeners assigned (on every update we add a listener. No point in cancelling on context dispose as we're not performing operations that can hang indefinitely. And IO will anyway complete once it's started.
* Refactored `markDirty` into a batch API. Easier to change the internal implementation when we need to optimize io + more convenient usages on call sites.

fix(echo): removed unnecessary cancelWithContext

---

packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts
packages/ui/react-ui-theme/src/styles/components/button.ts
packages/ui/react-ui-theme/src/styles/components/input.ts
packages/ui/react-ui-theme/src/styles/layers/button.css
packages/ui/react-ui-theme/src/styles/layers/checkbox.css
packages/ui/react-ui-theme/src/styles/layers/focus-ring.css
packages/ui/react-ui-theme/src/styles/layers/index.css
packages/ui/react-ui-theme/src/util/semanticColors.ts

Resolves #5828.
This PR refactors checkbox styles into a utility classname which CM can more easily apply: `ch-checkbox`.
This PR extends the styles defined for checkboxes to apply to `<input type=checkbox/>` elements as well as Radix’s `<button role=checkbox />` elements.
https://github.com/dxos/dxos/assets/855039/81636535-467d-4561-9eb1-3e7944cf3c40

fix: Checkbox styles

---

packages/apps/composer-app/src/playwright/comments.spec.ts
packages/apps/plugins/plugin-chain/src/components/PromptTemplate/PromptTemplate.tsx
packages/apps/plugins/plugin-kanban/src/components/KanbanCard.tsx
packages/apps/plugins/plugin-markdown/src/components/DocumentSection.tsx
packages/apps/plugins/plugin-outliner/src/components/Outliner/Outliner.tsx
packages/apps/plugins/plugin-thread/src/components/MessageContainer.tsx
packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.stories.tsx
packages/ui/react-ui-editor/src/hooks/useTextEditor.stories.tsx
packages/ui/react-ui-searchlist/src/components/SearchList.tsx

Fixes e2e tests by removing superfluous `role='textbox'` attributes that got added during recent editor refactor.

chore: cleanup textbox role

---

packages/common/log/src/options.ts
packages/common/log/src/platform/browser/index.ts

e.g. so you can `localStorage.dxlog='{ "filter": "messaging:debug,info"}'` in the browser console.

fix: allow localStorage.dxlog to override config

---

REPOSITORY_GUIDE.md
packages/common/log/src/options.ts
packages/common/log/src/platform/browser/index.ts
packages/sdk/client/src/services/worker-client-services.ts
packages/sdk/client/src/worker/onconnect.ts

Rework of https://github.com/dxos/dxos/pull/5931
e.g. so you can `localStorage.dxlog='{ "filter": "messaging:debug,info"}'` in the browser console.

feat: allow localStorage.dxlog to override config

---

packages/apps/plugins/plugin-space/src/components/SpacePresence.tsx
packages/sdk/examples/project.json
packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.tsx

- testid erroneously removed from toolbar to create comments
- online members accidentally filtered out of space presence
- disabling (intentionally?) broken tests for examples app

chore: fix e2e tests

---

packages/apps/plugins/plugin-space/src/components/SpacePresence.tsx

If you assign default values when destructuring props, any reference type will get a new instance every render which may result in re-rendering bugs or unexpected behaviour.
Used the following regex to search for instances in the codebase -- thanks ChatGPT.
```regex
const\s+\{(?:\s|\n)*[^\}]*=[\s]*(?:\[\]|\{\})(?:\s|\n)*[^\}]*\}(?:\s|\n)*=\s*props;
```
I wonder if there's a way to turn the above into an `ESLint` rule?
This example caused an infinite re-rendering bug on empty tables.

chore: simplify destructuring reference types from `props` with `useDefaultValue`

---

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx
packages/ui/primitives/react-hooks/src/index.ts
packages/ui/primitives/react-hooks/src/useTransitions.ts
packages/ui/react-ui-table/src/components/Table/Table.tsx
packages/ui/react-ui-table/src/hooks/useTransitions.ts

This PR fixes an infinite re-render issue on column resize.
Initially, when the resize handler was activated, it updated the parent state, which in turn caused the child table component to re-render. Upon this re-render, the resize condition was still true, triggering the resize handler again. 🔁
Introduce `useDidTransition` and `useOnTransition` hooks to fire the `columnResized` handler. If we approve of these hooks, we should move them into `packages/ui/primitives/react-hooks` with our other hooks before this merges.
- `useOnTransition` is useful because it only fires once per valid transition even when the component re-renders with the same data. Currently it achieves this through `const dirty = useRef(false) ...` but I would prefer to use `rxjs` or another stream abstraction.

fix(table): Infinite re-render on column resize

---

packages/ui/react-ui-editor/src/extensions/automerge/automerge.ts

Listeners were not removed from handle because different objects were passed to add&remove.

fix(composer): fixed listener leak

---

packages/core/echo/echo-signals/project.json
packages/core/echo/echo-signals/src/untracked.test.ts

- Found a bug in the preact when nested `untracked` causes `effect` to run
- Added a unit test that repros it
- Reported it to preact team https://github.com/preactjs/signals/issues/536
- We need to wait for them to release next version, and it will be fixed

test: Add test that repro infinite cycle in preact

---

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx

I'm actually not sure why this fixes the durability / edit issues in table. But it does.
Everything works without these force-update lines now too since we're now tracking deps properly.
`¯\_(ツ)_/¯`

fix(tables): adding rows, deletions and cell edits should be durable

---

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx

Looks like it was actually the way we were specifying deps for the column memoization. Suspect there was a race-condition and the component was rebuilding the columns and reinitialising the table before the update callbacks had a chance to be invoked. This one makes more sense @wittjosiah.

fix(tables): table edits should be durable

---

packages/apps/plugins/plugin-presenter/src/components/Markdown/Container.stories.tsx
packages/apps/plugins/plugin-presenter/src/components/Markdown/Container.tsx
packages/apps/plugins/plugin-presenter/src/components/Markdown/Slide.tsx
packages/apps/plugins/plugin-presenter/src/components/Markdown/theme.ts
packages/apps/plugins/plugin-presenter/src/components/Presenter/Layout.tsx

Resolves #6059.
This PR corrects the color tokens used by PluginPresenter. This PR also injects a dark theme for `ReactMarkdown`.
https://github.com/dxos/dxos/assets/855039/a90fa999-ec30-47a8-8d6a-5286c2af1639

fix(plugin-presenter): Presenter theme

---

packages/core/echo/echo-schema/src/effect/json-schema.test.ts
packages/core/echo/echo-schema/src/effect/json-schema.ts

A prerequisite for dynamic runtime schemas PR. 
Encoding effect into json schema with `refinement`s for annotation serialization.
Decoding json into effect schema.

feat(echo): json-effect schema codec

---

packages/ui/react-ui-table/src/components/Cell/Cell.tsx
packages/ui/react-ui-table/src/components/Table/Table.tsx
packages/ui/react-ui-table/src/components/Table/TableBody.tsx
packages/ui/react-ui-table/src/components/Table/TableContext.tsx
packages/ui/react-ui-table/src/components/Table/TableFooter.tsx
packages/ui/react-ui-table/src/components/Table/TableHead.tsx
packages/ui/react-ui-table/src/components/Table/props.ts
packages/ui/react-ui-table/src/helpers.tsx

This PR refactors our table component's state management from `@radix-ui/react-context` to standard React context. 
There is a significant reduction in lag post making table edits after this change.
The memoization benefits of `@radix-ui/react-context` were found to be less effective for the dynamic and large datasets managed by the table component.
Ideally, we'd use an indexed store mechanism or something like `use-context-selector` to improve performance even more and minimize re-rendering across the tree. Context is a bad fit for this kind of state.

fix(tables): don't use memoizing context in table

---

REPOSITORY_GUIDE.md

Replace `docs/docs/...` links in the repo guide with `docs/content/...`
Fixes broken branch diagram too

fix: broken docs links in REPOSITORY_GUIDE.md

---

packages/core/echo/echo-schema/src/automerge/automerge-object-core.ts
packages/core/echo/echo-schema/src/effect/dynamic/dynamic-schema.test.ts
packages/core/echo/echo-schema/src/effect/dynamic/dynamic-schema.ts
packages/core/echo/echo-schema/src/effect/echo-handler.ts
packages/core/echo/echo-schema/src/effect/schema-validator.test.ts
packages/core/echo/echo-schema/src/effect/schema-validator.ts

DynamicSchema fixes cherry-picked from [`plugin-table` migration branch](https://github.com/dxos/dxos/pull/6135).
Fixes the case of creating a typed-handler or echo-typed-handler with `DynamicEchoSchema` in initialProps.

fix(echo): fixed object creation with dynamicSchema

---

packages/sdk/shell/src/components/EmojiPicker.tsx
packages/sdk/shell/src/panels/IdentityPanel/steps/ProfileForm.tsx
packages/ui/react-ui-theme/src/styles/components/dialog.ts

Resolves #5983. Resolves #6091.
This PR:
- Only updates the profile with truthy values, preventing an empty string `displayName`
- Opens the emoji picker on top of the trigger by default, only opens alongside the trigger at `md` or greater.
https://github.com/dxos/dxos/assets/855039/7ec99cc0-6732-4055-b822-42e670510b47

fix(shell): Shell UI QOL adjustments

---

packages/apps/plugins/plugin-outliner/src/OutlinerPlugin.tsx
packages/apps/plugins/plugin-outliner/src/types.ts

Outliner is broken because type schemas are not registered in echo.

fix(echo): register missing outliner types

---

packages/apps/plugins/plugin-outliner/src/components/Outliner/Outliner.tsx
packages/apps/plugins/plugin-outliner/src/components/Outliner/types.tsx
packages/core/echo/echo-schema/src/effect/schema-validator.test.ts
packages/core/echo/echo-schema/src/effect/schema-validator.ts

Fix for outliner plugin, where a type is declared using suspend:
```ts
export class TreeItemType extends E.EchoObjectSchema({ typename: 'braneframe.Tree.Item', version: '0.1.0' })({
text: E.ref(TextV0Type),
items: S.suspend((): S.Schema<E.Ref<TreeItemType>[]> => S.mutable(S.array(E.ref(TreeItemType)))),
done: S.optional(S.boolean),
}) {}
```

fix(echo): schema-validator handles suspend types

---

packages/core/echo/echo-schema/src/effect/dynamic/schema-registry.ts
packages/core/echo/echo-schema/src/type-collection.ts

Compatibility type for legacy schema. Temporary solution to avoid spamming console with warnings.

fix(echo): fixed dynamic schema warnings

---

packages/apps/plugins/plugin-debug/src/components/DebugSettings.tsx

We do not need to write the whole config to storage. It disallows to change config defaults because storage values override new defaults

fix: Fix Storage config

---

packages/sdk/shell/src/composites/Shell/Shell.tsx
packages/sdk/shell/src/panels/IdentityPanel/steps/SignOutChooser.tsx
packages/sdk/shell/src/panels/JoinPanel/JoinPanel.tsx
packages/sdk/shell/src/panels/JoinPanel/JoinPanelProps.ts
packages/sdk/shell/src/panels/JoinPanel/steps/ResetIdentity.tsx
packages/ui/react-ui-theme/src/styles/layers/button.css
packages/ui/react-ui/src/components/Buttons/Button.stories.tsx
packages/ui/react-ui/src/components/Buttons/Button.tsx

Resolves #6156.
This PR adds a ‘Cancel’ button to the ResetIdentity step of JoinPanel which is bound in the shell to set the layout back to the IdentityPanel.
https://github.com/dxos/dxos/assets/855039/4ad0d4d2-8c01-4036-8545-195ef84a2b97
This PR also adds `'destructive'` as a variant of Button and uses this variant where red buttons were observed.

fix(shell): User can cancel reset

---

packages/sdk/shell/src/steps/ConfirmReset.tsx
packages/sdk/shell/src/testing/shell-manager.ts

This PR restores e2e tests which rely on changes to the reset flow introduced by #6171.

fix: Restore shell-manager

---

packages/apps/plugins/plugin-markdown/package.json
packages/apps/plugins/plugin-markdown/src/components/DocumentSection.tsx
packages/apps/plugins/plugin-markdown/tsconfig.json
packages/apps/plugins/plugin-stack/src/components/StackMain.tsx
packages/ui/react-ui-deck/src/components/Deck/Deck.tsx
packages/ui/react-ui-deck/src/fragments/index.ts
packages/ui/react-ui-deck/src/fragments/resize-handle.ts
packages/ui/react-ui-deck/src/index.ts
packages/ui/react-ui-deck/src/translations.ts
packages/ui/react-ui-stack/src/components/Deck.stories.tsx
packages/ui/react-ui-stack/src/components/Section.tsx
packages/ui/react-ui-stack/src/components/Stack.tsx
packages/ui/react-ui-stack/src/components/index.ts
packages/ui/react-ui-theme/src/util/semanticColors.ts
pnpm-lock.yaml

Resolves #6189.
This PR facilitates for Stack sections:
- resizing along the block axis (not integrated, but available in the UI)
- adjusting the rail content when a toolbar is present
https://github.com/dxos/dxos/assets/855039/9715afff-4a64-478d-be9c-24ebc5636237
https://github.com/dxos/dxos/assets/855039/53e5713b-2cc3-461c-be2a-6c71aa6dc123
https://github.com/dxos/dxos/assets/855039/a11233b4-26ae-47f1-960e-cff8bb3b67c4

feat(react-ui-stack): Stack section chrome increment

---

packages/apps/plugins/plugin-chain/src/ChainPlugin.tsx
packages/apps/plugins/plugin-chess/src/ChessPlugin.tsx
packages/apps/plugins/plugin-explorer/src/ExplorerPlugin.tsx
packages/apps/plugins/plugin-grid/src/GridPlugin.tsx
packages/apps/plugins/plugin-inbox/src/InboxPlugin.tsx
packages/apps/plugins/plugin-kanban/src/KanbanPlugin.tsx
packages/apps/plugins/plugin-map/src/MapPlugin.tsx
packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/apps/plugins/plugin-outliner/src/OutlinerPlugin.tsx
packages/apps/plugins/plugin-script/src/ScriptPlugin.tsx
packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx
packages/apps/plugins/plugin-stack/src/StackPlugin.tsx
packages/apps/plugins/plugin-table/src/TablePlugin.tsx
packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx

Cleanup old query subscriptions before resubscribing. Attempt to narrow down some of the current performance issues on dev.

fix: cleanup plugin query subscriptions

---

packages/ui/react-ui-navtree/package.json
packages/ui/react-ui-navtree/src/components/NavTreeItem.tsx
packages/ui/react-ui-navtree/src/components/NavTreeItemAction.tsx
pnpm-lock.yaml

Resolves #5816.
This PR uses a `contextmenu` specifically to open a tree item’s action menu (if rendered). Note that this does not facilitate long-tap, however the three-dots menu trigger will always be visible on mobile.
https://github.com/dxos/dxos/assets/855039/0616f551-da38-4aaa-837d-f00a34de3427

feat(react-ui-navtree): Right-click on tree item heading opens actions menu

---

packages/sdk/shell/package.json
packages/sdk/shell/tsconfig.json
pnpm-lock.yaml

todomvc app bundling mysteriously started failing with the following error:
> failed to resolve import "@dxos/protocols" from "/home/circleci/project/packages/sdk/shell/dist/bundle/shell.mjs"
this seems to resolve it

chore(shell): add missing dep

---

packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx
packages/core/echo/echo-schema/src/automerge/index.ts
packages/core/echo/echo-schema/src/text.ts
packages/experimental/labs-functions/src/functions/chat/context.ts
packages/ui/react-ui-editor/src/extensions/automerge/cursor.ts

Stop hardcoding the 'content' path in all of the text helpers and reconcile with editor cursor converter.
Part of #4745

refactor(echo-schema): make text helpers generic

---

packages/apps/plugins/plugin-markdown/src/components/DocumentMain.tsx
packages/ui/react-ui-editor/src/components/TextEditor/TextEditor.tsx

Fixes the following issue:
https://github.com/dxos/dxos/assets/4529818/76d5099d-4c72-45de-a24f-dcb8d00f9450
The key fix was removing `doc` from the effect dependencies. Given the automerge transition doc ends up just being a plain string which is updated reactively and depending on that causes the editor to remount on every keystroke.

fix(react-ui-editor): don't recreate editor when initial text value changes

---

packages/apps/plugins/plugin-debug/src/components/DebugSpace.tsx
packages/apps/plugins/plugin-space/src/components/SpaceMain/SpaceMembersSection.tsx
packages/core/echo/echo-pipeline/src/metadata/metadata-store.ts
packages/core/protocols/src/proto/dxos/client/services.proto
packages/devtools/cli/src/commands/app/open.ts
packages/devtools/cli/src/commands/space/share.ts
packages/gravity/kube-testing/src/spec/echo.ts
packages/sdk/client-protocol/src/invitations/encoder.ts
packages/sdk/client-services/src/packlets/invitations/invitations-handler.ts
packages/sdk/client-services/src/packlets/invitations/invitations-service.ts
packages/sdk/react-client/src/invitations/useInvitationStatus.ts
packages/sdk/shell/src/components/InvitationList/InvitationListItem.tsx
packages/sdk/shell/src/panels/IdentityPanel/useAgentHandlers.ts
packages/sdk/shell/src/panels/SpacePanel/steps/SpaceManager.tsx
packages/sdk/shell/src/steps/InvitationManager.tsx

A small refactoring: make multiuse into a separate flag instead of invitation type.
Both offline and interactive invitations can be multiuse.
Tested on a local composer build.
re #6301

refactor(halo): make multiuse into a separate flag instead of invitation type

---

packages/ui/react-ui-stack/src/components/Stack.tsx

This PR fixes an e2e regression caused by not spreading props onto Stack’s root.  This restores e2e testing for `react-ui-stack` and the `stack.spec` of `composer-app`.

fix(react-ui-stack): Spread props onto Stack root

---

packages/core/protocols/src/proto/dxos/client/services.proto
packages/sdk/client-services/src/packlets/invitations/index.ts
packages/sdk/client-services/src/packlets/invitations/invitations-handler.ts
packages/sdk/client-services/src/packlets/invitations/invitations-manager.ts
packages/sdk/client-services/src/packlets/invitations/invitations-service.ts
packages/sdk/client-services/src/packlets/services/service-context.ts
packages/sdk/client-services/src/packlets/services/service-host.ts
packages/sdk/client/src/tests/invitations.test.ts

Services use Managers to manage data (Service -> Manager). 
All spaces are created through DataSpaceManager. On space creation, DataSpaceManager will attach a listener of spaceState to handle delegated invitations.
DataSpaceManager shouldn't have access to InvitationService (Service <- Manager). 
Create a class that'll be used by both DataSpaceManager and InvitationService, and that'll manage invitations preventing duplicates.
* Created `InvitationsManager` and pulled the majority of code from `InvitationsService` there.
* Fixed duplicated subscriptions on `existingInvitation` return (added early return for existing invitations).
* Fixed missing subscription for invitations created in `loadPersistentInvitations` (for `_createInvitations` updates) and `.filter(async (invitation)` always …

refactor(halo): extracted invitation management into serviceContext from serviceHost

---

packages/core/echo/echo-schema/src/automerge/automerge-db.ts
packages/core/echo/echo-schema/src/echo-handler/echo-handler.test.ts

This functionality is needed to fix some of the bad behaviour around deleting threads where they end up visible in the navtree.

fix(echo): Restore objects when they are re-added to the database

---

packages/apps/composer-app/.eslintrc.js
packages/apps/composer-app/demos/grid.ts
packages/apps/composer-app/package.json
packages/apps/composer-app/tsconfig.json
pnpm-lock.yaml

robotjs is old and does not have the adequate prebuild binary for native code for most linux systems.

fix: remove robotjs

---

packages/apps/plugins/plugin-settings/package.json
packages/apps/plugins/plugin-settings/src/components/SettingsDialog.tsx
packages/apps/plugins/plugin-settings/tsconfig.json
pnpm-lock.yaml

The composer plugin template does not have all plugins available so the settings dialog crashes.
This PR attempts to mitigate those issues.
Relates to #6398

chore: cleanup settings dialog for template usage

---

packages/common/feed-store/package.json
packages/common/random-access-storage/package.json
packages/common/random-access-storage/project.json
pnpm-lock.yaml

Reverts #6248
The fix here is specifically aligning the version of idb that `@dxos/random-access-storage` was bundling with one compatible with `random-access-idb`.

fix: bundle random-access-idb

---

packages/common/random-access-storage/src/browser/storage.ts
packages/common/random-access-storage/src/common/storage.ts

This Pull Request updates the default storage to IDB. OPFS storage will be removed in a future release. IDB was found to be more performant and maintaining both was holding back other optimizations.

fix(random-access-storage)!: change default storage to always be idb

---

packages/apps/templates/bare-template/src/src/App.tsx.t.ts
packages/apps/templates/hello-template/src/src/App.tsx.t.ts
packages/apps/templates/hello-template/src/src/Counter.tsx.t.ts

Fixes an issue with the hello template where it's creating a new object every time because it takes too long for the query to load the objects that are there.
The fix here is to not run the create code in an effect but only immediately after the identity is created. This way it is run once and only once and the same object is always returned by the counter query.

chore: fix hello template

---

packages/apps/plugins/plugin-debug/src/components/SchemaList.tsx
packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.stories.tsx
packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx
packages/apps/plugins/plugin-table/src/components/TableMain.tsx
packages/apps/plugins/plugin-table/src/components/TableSection.tsx
packages/apps/plugins/plugin-table/src/components/TableSlide.tsx
packages/apps/testbench-app/src/components/ItemTable.tsx
packages/devtools/devtools/src/components/MasterDetailTable.tsx
packages/devtools/devtools/src/panels/client/TracingPanel/LogTable.tsx
packages/devtools/devtools/src/panels/client/TracingPanel/LogView.tsx
packages/devtools/devtools/src/panels/client/TracingPanel/TracingPanel.tsx
packages/devtools/devtools/src/panels/echo/SpaceInfoPanel/FeedTable.tsx
packages/devtools/devtools/src/panels/echo/SpaceInfoPanel/PipelineTable.tsx
packages/devtools/devtools/src/panels/echo/SpaceInfoPanel/SpaceInfoPanel.tsx
packages/devtools/devtools/src/panels/echo/SpaceListPanel/SpaceListPanel.tsx
packages/devtools/devtools/src/panels/mesh/SignalPanel/SignalStatusTable.tsx
packages/devtools/devtools/src/panels/mesh/SwarmPanel/ConnectionInfoView.tsx
packages/devtools/devtools/src/panels/mesh/SwarmPanel/SwarmPanel.tsx
packages/ui/react-ui-stack/src/testing/TableContent.tsx
packages/ui/react-ui-table/package.json
packages/ui/react-ui-table/src/components/Table/Table.stories.tsx
packages/ui/react-ui-table/src/components/Table/Table.tsx
packages/ui/react-ui-table/src/components/Table/TableBody.tsx
packages/ui/react-ui-table/src/components/Table/TableRootContext.ts
packages/ui/react-ui-table/src/components/Table/TableRootContext.tsx
packages/ui/react-ui-table/src/components/Table/index.ts
packages/ui/react-ui-table/src/components/Table/props.ts
packages/ui/react-ui-table/src/hooks/usePinLastRow.ts
packages/ui/react-ui-table/src/schema/SchemaToTable.stories.tsx
pnpm-lock.yaml

This PR introduces `Table.Root` as well as `Table.Viewport` for managing a ref to the scrolling context.
This PR also enforces virtualised usage of tables and implements dynamic measurement to resolve an issue we've been seeing in Testbench app.
This PR updates all usages of Table, and should resolve a slew of warnings we've been getting from the devtools tables.

fix(tables): Enforce virtualisation

---

packages/devtools/devtools/src/containers/DataSpaceSelector.tsx
packages/devtools/devtools/src/panels/echo/SpaceListPanel/SpaceListPanel.tsx

Don't attempt to access the space's name if it is closed to prevent the panels from crashing.

fix(devtools): handle spaces being closed

---

packages/ui/react-ui-table/src/components/ColumnMenu/ColumnMenu.tsx
packages/ui/react-ui-table/src/components/Table/Table.tsx
packages/ui/react-ui-table/src/components/Table/props.ts
packages/ui/react-ui-table/src/hooks/useColumnSorting.ts

- Resolves #6506
I thought this would be a quick change, but I ended up having to bring sorting into controlled state, since there's no way to get a reactive handle to the current sort in `@tanstack/table`.

fix(tables): Sorting another column should clear current column sorting

---

packages/core/echo/echo-db/src/serializer.test.ts
packages/core/echo/echo-db/src/serializer.ts

`loadObjectById` returns undefined for deleted objects, need to filter them during export.

fix(echo): fixed space export with deleted objects

---

packages/core/echo/echo-db/src/serializer.ts

Large spaces flood the worker with requests and need a larger timeout to get all objects.

chore(echo-db): increase export object fetch timeout

---

packages/core/echo/echo-db/src/serializer.test.ts
packages/core/echo/echo-db/src/serializer.ts

Increasing timeout wasn't enough for space with too many objects. Try triggering loading on different objects incrementally.

fix(echo): try loading objects in chunks when exporting data

---

packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx
packages/apps/plugins/plugin-kanban/src/components/KanbanCard.tsx
packages/apps/plugins/plugin-markdown/src/components/DocumentCard.tsx
packages/apps/plugins/plugin-markdown/src/components/DocumentSection.tsx
packages/apps/plugins/plugin-script/src/components/ScriptEditor/ScriptEditor.tsx
packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
packages/apps/plugins/plugin-space/src/components/SpaceMain/SpaceMain.tsx
packages/ui/react-ui-editor/src/hooks/useTextEditor.ts
packages/ui/react-ui-stack/src/testing/EditorContent.tsx

Resolves #6563.
This PR fixes `DocumentSection` focus.
https://github.com/dxos/dxos/assets/855039/da2f44d8-2f87-4a60-9a76-5a2b0d87f2d0
This PR also:
- refactors `useTextEditor` to also return oft copypasted affordances for focus as `focusAttributes`
- uses `focusAttributes` for several stories and features
- some were skipped (e.g. OutlinerPlugin’s) since focus appears to be managed or irrelevant
- reverses the toolbar and the editor so that the editor is the first focusable item in a DocumentSection

fix: DocumentSection focus

---

packages/apps/plugins/plugin-navtree/src/components/NavTreeFooter.tsx

This PR fixes an issue where Deck controls would render even when Deck is not the active layout plugin.

fix(plugin-navtree): Fix missing Deck condition

---

packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx

Use an empty object with an ID that will be stable across renders to restore focus.
- Fixes: #6468

fix(tables): Durable cell focus when adding row

---

packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/ui/react-ui-stack/src/components/Deck.stories.tsx
packages/ui/react-ui-stack/src/components/Section.tsx
packages/ui/react-ui-stack/src/components/Stack.stories.tsx

Resolves #6561.
Implements an interface necessary to achieve #6592.
https://github.com/dxos/dxos/assets/855039/31ea88a3-b600-4ece-804c-02cc805442c3

fix: Plugins can provide a getter for object labels

---

packages/common/async/src/mutex.ts
packages/common/util/src/circular-buffer.ts
packages/core/halo/credentials/src/credentials/credential-generator.ts
packages/core/mesh/network-manager/src/swarm/connection.ts
packages/core/mesh/network-manager/src/swarm/peer.ts
packages/core/mesh/network-manager/src/swarm/swarm.ts
packages/core/mesh/network-manager/src/topology/topology.ts
packages/core/mesh/network-manager/src/wire-protocol.ts
packages/core/mesh/rpc/src/rpc.ts
packages/core/mesh/teleport/src/control-extension.ts
packages/core/mesh/teleport/src/rpc-extension.ts
packages/core/mesh/teleport/src/teleport.ts
packages/sdk/client-services/src/packlets/invitations/device-invitation-protocol.ts
packages/sdk/client-services/src/packlets/invitations/invitation-guest-extenstion.ts
packages/sdk/client-services/src/packlets/invitations/invitation-host-extension.ts
packages/sdk/client-services/src/packlets/invitations/invitation-protocol.ts
packages/sdk/client-services/src/packlets/invitations/invitation-topology.ts
packages/sdk/client-services/src/packlets/invitations/invitations-handler.test.ts
packages/sdk/client-services/src/packlets/invitations/invitations-handler.ts
packages/sdk/client-services/src/packlets/invitations/invitations-manager.ts
packages/sdk/client-services/src/packlets/invitations/space-invitation-protocol.ts
packages/sdk/client-services/src/packlets/invitations/utils.ts
packages/sdk/client-services/src/packlets/services/service-context.ts
packages/sdk/client-services/src/packlets/testing/invitation-utils.ts
packages/sdk/client-services/src/packlets/testing/test-builder.ts
packages/sdk/client/src/testing/test-builder.ts
packages/sdk/client/src/tests/client-services.test.ts
packages/sdk/client/src/tests/invitations.test.ts

* Cancel delegated invitation in HALO chain when an invitation is cancelled.
* Fixed connection initiation with a peer which left a swarm while we were sleeping.
* Expose `allPeers` to topology as part of `SwarmState` (needed for invitation topology to cleanup peer ids).
* Allow overriding control heartbeat interval on `Teleport` creation for faster failure detection in tests.
* Fixed rpc closed while opening early return.
* Close control connection as soon as `RpcClosedError` is received to speed up connection termination.
* Split InvitationExtension into separate host&guest files.
* Enforce flow state invariants in host invitation flow.
* Use mutex to serialize invitation flow for many-guests and/or many-hosts scenarios.
* Created `InvitationTopology` to try properly connecting hosts …

feat(halo): delegated invitations

---

packages/core/echo/echo-db/src/query/filter.test.ts
packages/core/echo/echo-db/src/query/filter.ts
packages/sdk/client-services/src/packlets/invitations/invitations-handler.test.ts

A hack was added for optimization of app-graph where `Filter.not(Filter.schema())` is used to avoid loading all text objects.
This broke the behavior of filtering out deleted folders.
`Fitler.not` should respect filter options where deleted handling is specified.

fix(echo): fix folder removal

---

packages/sdk/shell/src/panels/JoinPanel/JoinPanel.tsx

Resolves #6582.
This PR fixes the reset flow, caused by a typo.
https://github.com/dxos/dxos/assets/855039/8be6af2a-852c-446c-a84a-4eb0c2dfb9d9

fix(shell): Fix typo which broke reset flow

---

packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/apps/plugins/plugin-table/src/TablePlugin.tsx
packages/ui/react-ui-stack/src/components/Section.tsx
packages/ui/react-ui/src/components/ThemeProvider/TranslationsProvider.tsx
packages/ui/react-ui/src/components/ThemeProvider/index.ts

This PR fixes cases where a Stack section’s `transformedItem.label` may be defined but uncallable.

fix(react-ui-stack): Label getter call

---

packages/ui/react-ui-navtree/src/components/NavTreeItem.tsx

Resolves #4634.
This PR conditionally applies `hoverableControls` only to NavTree items which are deeper than at the root.
https://github.com/dxos/dxos/assets/855039/f3627a2d-1d4d-4486-9f03-ea11310671b1

fix(react-ui-navtree): Only apply `hoverableControls` for navtree items not at root.

---

packages/apps/plugins/plugin-settings/src/SettingsPlugin.tsx
packages/apps/plugins/plugin-settings/src/components/SettingsDialog.tsx

Pretty simple fix since we were able to leverage the work done for #6145
- Resolves #6488
https://github.com/dxos/dxos/assets/12402727/6c501fc4-60b6-4237-8383-0e9d8454aff7

fix(composer): Anchor settings dialog to prevent content jumps

---

packages/apps/plugins/plugin-markdown/src/components/DocumentSection.tsx
packages/ui/react-ui-stack/src/components/Section.tsx
packages/ui/react-ui-stack/src/translations.ts

Resolves #6567.
This PR hosts navitate-to for stack sections that are expanded, otherwise the expand action is hoisted.
This PR also fixes a bug related to document toolbars scoped to the wrong group.
https://github.com/dxos/dxos/assets/855039/63136b85-c557-4339-9689-696c6cfff554

feat(react-ui-stack): Hoist navigate-to action

---

packages/core/echo/echo-db/src/client/index-query-source-provider.ts
packages/core/echo/echo-db/src/hypergraph.ts
packages/core/echo/echo-db/src/query/query-service.ts
packages/sdk/react-client/src/echo/useQuery.ts

Some queries seem to get stuck in active state randomly - suspecting it's an artifact of how diagnostics are collected rather then a real leak

fix: Dispose queries correctly

---

packages/apps/plugins/plugin-table/package.json
packages/apps/plugins/plugin-table/src/TablePlugin.tsx
packages/apps/plugins/plugin-table/src/components/SettingsDialog/SettingsDialog.tsx
packages/apps/plugins/plugin-table/src/components/TableSection.tsx
packages/apps/plugins/plugin-table/src/components/TableSettings/TableSettings.tsx
packages/apps/plugins/plugin-table/src/translations.ts
packages/apps/plugins/plugin-table/src/types.ts
packages/apps/plugins/plugin-table/tsconfig.json
packages/ui/react-ui-stack/src/components/style-fragments.ts
packages/ui/react-ui-theme/src/styles/layers/positioning.css
pnpm-lock.yaml

- Resolves #6653
- Resolves #6321
- Resolves #6654
- Resolves #6604
Changes:
- Restore focus.
- Fix stack max-width (stack section template column calculation).
- Switch to sticky-header in stack sections.
- Implement a max height for table stack sections (open to suggestions for what this value should be).
- Support adding new table to bottom of stack.
- Don't show 'Cancel' on create table form.
https://github.com/dxos/dxos/assets/12402727/cd97fea0-647b-46d4-9484-50bd360ef1ef
src="https://github.com/dxos/dxos/assets/12402727/9adc0219-1379-4aad-bd17-2ad12eabb657">

fix(table): Improve table in stacks

---

packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx
packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx
packages/apps/plugins/plugin-sketch/src/components/Sketch.tsx
packages/apps/plugins/plugin-sketch/src/components/SketchMain.tsx

Resolves #6691.
This PR adds Deck support to SketchPlugin.
https://github.com/dxos/dxos/assets/855039/64b1a44f-25b9-47b7-bffc-9c95544d9526
This PR fixes a couple bugs:
- `PlankLoading` was provided rendered instead of as an FC
- `SketchComponent` crashes if `zoom` is evaluated as `0`, now throws an error instead of crashing

feat(plugin-sketch): Sketch planks

---

packages/devtools/devtools/src/components/performance/StatsPanel.tsx

Make the refresh button a toggle to enable periodic stats gathering rather than one off.

feat(devtools): autorefresh on stats panel

---

packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx

Resolves #6571.
https://github.com/dxos/dxos/assets/855039/a4311949-cad9-43bb-9f22-17c625c88e8f
This PR adds a subscription to ThreadsPlugin’s `ready` which opens threads in the complementary sidebar if any are found related to the attended items.

feat(plugin-threads): Open comments in c11y sidebar when attention changes

---

packages/apps/composer-app/src/components/ResetDialog.tsx
packages/apps/composer-app/src/playwright/app-manager.ts
packages/apps/composer-app/src/playwright/basic.spec.ts

- Resolves #5726
- also fixes test where debug is enabled by default outside of production

test(composer-app): add error boundary reset test

---

packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts
packages/core/echo/echo-db/src/echo-handler/echo-handler.ts
packages/core/echo/echo-db/src/echo-handler/proxy.blueprint-test.ts
packages/core/echo/echo-schema/src/getter.ts
packages/core/echo/echo-schema/src/handler/logging-handler.ts
packages/core/echo/echo-schema/src/handler/typed-handler.ts
packages/core/echo/echo-schema/src/handler/untyped-handler.ts
packages/core/echo/echo-schema/src/proxy/types.ts

We always store a type reference together with an object, but schema might not have been registered or replicated yet. It should be possible to get the reference in this case.

fix(echo): allow accessing type reference if schema wasn't registered

---

packages/core/echo/echo-db/src/automerge/automerge-db.test.ts
packages/core/echo/echo-db/src/automerge/automerge-db.ts

`_isOpen` is initialized immediately after a call to `open()`, not when docHandle is loaded.
Calling `getSpaceRootDocHandle` before the handle was loaded throws an exception.
re #6790

fix(echo): fixed invariant violation on race with open

---

packages/common/phoenix/src/phoenix.test.ts
packages/common/phoenix/src/phoenix.ts
packages/common/phoenix/src/testing-utils.ts

The test was spawning a process that used `log` framework, which was not bundled correctly, but checks were passing because log file contained the command itself. If the test took a little bit longer, process had enough time to reach a failing point.
Changed check to match only executed `console.log`, dropped `log` framework, and used `console.log` directly inside tests

test: Fix Phoenix test

---

packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx
packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx
packages/apps/plugins/plugin-deck/src/translations.ts
packages/ui/react-ui-deck/src/components/Deck/Deck.tsx
packages/ui/react-ui-deck/src/components/PlankHeading/PlankHeading.tsx
packages/ui/react-ui-deck/src/fragments/resize-handle.ts
packages/ui/react-ui-deck/src/index.ts

This PR:
- Resolves #6771
- Resolves #6772
- Resolves #6780 
- Implements a more subdued design for the resize handle which is persistently visible but does not fill the full height of the Deck unless hovered or focused
- Always renders a Plank heading, using “Loading…” for planks that have not yet timed out.
https://github.com/dxos/dxos/assets/855039/0dd67b7e-f81f-49ac-95c0-4d6b3968257a

fix: Plank improvements & fixes

---

package.json

Was causing cloudflare pages builds to fail

chore: make pnpm engine less strict

---

packages/apps/plugins/plugin-presenter/package.json
packages/apps/plugins/plugin-presenter/tsconfig.json

Causing
> ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL  Cannot resolve workspace protocol of dependency "@braneframe/plugin-layout" because this dependency is not installed. Try running "pnpm install".
on publish

chore(plugin-presenter): remove erroneous peer dependency

---

packages/apps/composer-app/src/playwright/basic.spec.ts
packages/apps/composer-app/src/playwright/collaboration.spec.ts
packages/apps/composer-app/src/playwright/halo.spec.ts
packages/apps/composer-app/src/playwright/playwright.config.ts

Playwright tests still seem to be failing due to timeouts a bunch of the time in CI. Looking at the traces they seem to be caused primarily by the app taking 10-15s to even load before the test starts in earnest. This seems problematic, but for now just try increasing the timeout to reduce the failures.

test(composer-app): increase default timeout for playwright tests

---

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx

This PR:
- resolves #6875.
https://github.com/dxos/dxos/assets/855039/66a2b4b4-2d3b-4a40-a0a5-476771b6f354

fix(plugin-markdown): Auto-focus the document when it receives attention in Deck

---

lychee.toml

I would have rather excluded everything in .gitignore, but didn't see a convenient way to do this.

docs: exclude node_modules from lychee

---

packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx
packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx
packages/apps/plugins/plugin-stack/src/components/StackMain.tsx
packages/ui/react-ui-stack/src/components/Section.tsx

This PR:
- resolves #6885
- adjusts stack sections to use border instead of outline, aligning appearance with documents
https://github.com/dxos/dxos/assets/855039/2b9615f7-0f9e-4db0-a337-31a745824f44

fix: Scroll plank into view when navigating from a Stack section

---

packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx
packages/ui/react-ui-deck/src/components/PlankHeading/PlankHeading.tsx
packages/ui/react-ui-deck/src/translations.ts

This PR adjusts Deck to support minifying planks rather than closing them, as a variation on the close button.
https://github.com/dxos/dxos/assets/855039/83bdcb3c-216a-4c29-9ba2-b47a4f943fa6

fix(react-ui-deck): Support minification of sidebars as a variation of close

---

packages/core/functions/src/runtime/dev-server.test.ts
packages/core/functions/src/runtime/scheduler.test.ts
packages/core/functions/src/testing/setup.ts
packages/experimental/agent-functions/src/tests/functions/gpt.test.ts

Use random ports to fix tests failing cause of address already in use.

tests(functions): random ports to fix address already in use

---

packages/apps/composer-app/vite.config.ts

This should fix two things:
1) Wasm compile errors (e.g.: `CompileError: WebAssembly.instantiate(): expected magic word...`)
2) Composer not loading when offline if pwa is installed
I think this resolves #6019

fix(composer-app): include wasm files in service worker cache

---

packages/apps/plugins/plugin-debug/src/components/DebugSettings.tsx
packages/apps/plugins/plugin-ipfs/src/IpfsPlugin.tsx
packages/apps/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx
packages/apps/plugins/plugin-stack/src/components/StackMain.tsx
packages/sdk/app-framework/package.json
packages/sdk/app-framework/src/plugins/common/file.ts
packages/sdk/app-framework/tsconfig.json
packages/ui/react-ui-editor/src/components/Toolbar/Toolbar.tsx
pnpm-lock.yaml

This PR aims to complete the first two TODOs from #6717

feat: Pass space ref to file.upload provider

---

packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx
packages/apps/plugins/plugin-navtree/src/components/NavBarStart.tsx
packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
packages/apps/plugins/plugin-space/src/components/MenuFooter.tsx
packages/apps/plugins/plugin-space/src/components/index.ts
packages/apps/plugins/plugin-space/src/translations.ts
packages/ui/react-ui-deck/src/components/PlankHeading/PlankHeading.tsx
packages/ui/react-ui-theme/src/styles/components/menu.ts
packages/ui/react-ui-theme/src/styles/components/tooltip.ts

This PR:
- adds a details section to the plank heading menu
- resolves #6773
- fixes a color token issue where separators were not visible in modal surfaces
For spaces with long names:

feat: Plank heading menu detail section

---

packages/common/tracing/src/remote/tracing.ts

endTs is null rather than undefined, just check for falsy instead

chore(tracing): check for endTs falsy

---

packages/apps/composer-app/src/config.ts
packages/apps/composer-app/src/main.tsx
packages/apps/composer-app/src/shared-worker.ts
packages/apps/composer-app/tsconfig.json
packages/apps/testbench-app/src/main.tsx
packages/apps/testbench-app/src/shared-worker.ts
packages/common/tracing/src/api.ts
packages/common/tracing/src/remote/tracing.ts
packages/core/echo/echo-db/src/query/query-state.ts
packages/sdk/client/package.json
packages/sdk/client/project.json
packages/sdk/client/src/services/worker-client-services.ts
packages/sdk/observability/src/sentry/sentry-log-processor.ts

- hooks up sentry in shared worker
- stops re-emitted logs in app from being forwarded to sentry

chore(composer-app): hook up shared worker to sentry

---

packages/apps/composer-app/src/shared-worker.ts

top level imports in shared worker cause onconnect not to fire once app is bundled

chore(composer-app): address worker startup issue

---

packages/apps/plugins/plugin-debug/src/components/SchemaList.tsx
packages/apps/plugins/plugin-explorer/src/components/Graph/graph-model.ts
packages/apps/plugins/plugin-function/src/components/TriggerEditor.tsx
packages/apps/plugins/plugin-gpt/src/analyzer.ts
packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
packages/apps/plugins/plugin-table/src/components/ObjectTable/ObjectTable.tsx
packages/apps/plugins/plugin-table/src/components/TableSettings/TableSettings.stories.tsx
packages/core/echo/echo-db/src/database.ts
packages/core/echo/echo-db/src/dynamic-schema-registry.test.ts
packages/core/echo/echo-db/src/dynamic-schema-registry.ts
packages/core/echo/echo-db/src/dynamic-schema.test.ts
packages/core/echo/echo-db/src/echo-handler/echo-handler.ts
packages/core/echo/echo-db/src/query/filter.test.ts
packages/core/echo/echo-generator/src/generator.ts
packages/core/echo/echo-schema/src/dynamic/index.ts
packages/core/echo/echo-schema/src/dynamic/static-schema.ts
packages/core/echo/echo-schema/src/getter.ts
packages/devtools/cli/src/commands/space/schema/list.ts
packages/devtools/cli/src/commands/space/share.ts
packages/experimental/agent-functions/src/functions/github/handler.ts
packages/experimental/agent-functions/src/functions/gpt/context.ts
packages/experimental/agent-functions/src/functions/gpt/processor.ts

Schema-related API changes:
* `db.schemaRegistry` -> `db.schema`
* `schemaRegistry.getAll()` -> `schemaRegistry.listDynamic()`
* Introduced `StaticSchema` type for immutable schema (both runtime and stored)
* Introduced `db.schema.list()` method for retrieving all static schemas
CLI-related changes:
* `dx space schema list` shows space picker if no space provided and lists all schemas.
* `dx space schema list --typename prop` lists schemas with "prop" in typename (case-insensitive).
* `dx space schema list --extended` prints schema json representation.

feat(cli): list schema

---

packages/apps/types/src/serializer/clone.ts
packages/apps/types/src/serializer/serializers/default.ts
packages/apps/types/src/serializer/serializers/document.ts
packages/apps/types/src/serializer/serializers/index.ts
packages/apps/types/src/serializer/serializers/sketch.ts

During the clone operation only the sketch is serialized and the data isn't included.
Clone needs to not preserve ids right now so that you can copy things back and forth
between spaces and not have it fail because of id collision. Not preserving ids
makes references complicated because you need to update all the references.
The document serializer works because it collapses the references into a flat thing
(markdown) and then rebuilds the object structure afterwards. This does the same thing
but using json for sketch objects.
Resolves #6749

fix: sketch serializer

---

packages/core/echo/echo-pipeline/src/automerge/echo-network-adapter.ts
packages/core/echo/echo-pipeline/src/automerge/echo-replicator.ts
packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator.ts
packages/sdk/client/src/testing/utils.ts
packages/sdk/client/src/tests/spaces.test.ts

Fixes the following scenario:
1. Peers A and B share space 1.
2. A creates a document in space 2. Automerge sharePolicy check forbids to replicate the document.
3. A invites B to space 2, we want the document to be replicated now.
Fixed with a hack where I emit peer-disconnected immediately followed by peer-candidate to refresh doc synchronizer share policies.

fix(echo): handle peer automerge auth scope changes

---

docs/content/api/@dxos/client/README.md
packages/apps/testbench-app/src/webrtc/client/peer.ts

It seems https://docs.dxos.org/guide/quick-start is a 404

Fix link to Quick Start

---

packages/apps/templates/hello-template/src/src/App.tsx.t.ts

space list ready just means the default space credential is loaded and doesn't mean the default space is ready, which needs to be awaited separately

chore: update hello template

---

packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator.ts

Fixes the following race condition.
1. `this._context?.onConnectionClosed(connection);` removes connection from network adapter.
2. `await connection.disable();` creates a microtask.
3. Above this block gets executed because we haven't yet updated `_connectionsPerPeer`.
```ts
if (this._connectionsPerPeer.has(connection.peerId)) {
this._context.onConnectionAuthScopeChanged(connection);
}
```
4. `onConnectionAuthScopeChanged` crashes because there's no entry for this connection.

fix(mesh): fixed race condition

---

packages/apps/plugins/plugin-sketch/scripts/copy_assets.sh

cloudflare pages does not have rsync available

chore: remove rsync from copy_assets.sh

---

packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx
packages/ui/react-ui-theme/src/util/withLogical.ts

This PR:
- resolves #7085.
- fixes utility classname merging for some logical values
https://github.com/dxos/dxos/assets/855039/0379ba2e-b485-47fc-800f-a9003a662558

fix(plugin-sketch): Sketch section size

---

packages/apps/composer-app/project.json
packages/apps/plugins/plugin-sketch/project.json

copy had caused composer's serve target to depend on dependencies build, slowing down rebuilds

chore: run assets copy in prebuild

---

packages/apps/plugins/plugin-space/src/components/PopoverRenameObject.tsx

Updates the rename popover to always use name field by default to align with schema updates.

chore: align rename object with schema changes

---

packages/apps/composer-app/project.json
packages/core/mesh/rpc/src/rpc.ts

`_outgoingRequests` of `RpcPeer` wasn't cleared on the closing side when a stream was closed. 
It was cleared only when a connection was closed or another another party initiated the close.
fixes #7153

fix: fixed stream memory leak

---

packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
packages/apps/plugins/plugin-space/src/types.ts
packages/apps/plugins/plugin-space/src/util.tsx

Adds state to prevent sdk migrations from being run again while they are in progress.

chore: track sdk migrating state

---

packages/sdk/client/src/services/shell-manager.ts

This PR:
- resolves #7143
- fixes keyboard access to shell more broadly, by focusing the first focusable element in the shell when it opens
https://github.com/dxos/dxos/assets/855039/46eade83-d449-403b-af9a-1128daa1e5dd

fix(sdk): Focus within iframe when shell opens

---

packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx

fix(plugin-markdown): Document fills plank when toolbar is disabled

---

tools/intellij-plugin/README.md
tools/intellij-plugin/build.gradle
tools/intellij-plugin/src/main/kotlin/org/dxos/navigation/RealImplementationLocator.kt
tools/intellij-plugin/src/main/kotlin/org/dxos/navigation/ResourceImplMarkerProvider.kt
tools/intellij-plugin/src/main/resources/META-INF/plugin.xml

Adds a marker to the left of `open()` and `close()` calls of `Resource` subclasses.
On click jumps to corresponding implementations (`_open()` and `_close()`) instead of the base method.

feat(tools): jump to _open/_close shortcut for jetbrains IDEs

---

packages/core/echo/echo-db/src/host/echo-host.ts
tools/intellij-plugin/README.md
tools/intellij-plugin/build.gradle
tools/intellij-plugin/src/main/kotlin/org/dxos/navigation/ImplementationMarker.kt
tools/intellij-plugin/src/main/kotlin/org/dxos/navigation/RealImplementationLocator.kt
tools/intellij-plugin/src/main/kotlin/org/dxos/navigation/ServiceMethodImplMarkerProvider.kt
tools/intellij-plugin/src/main/kotlin/org/dxos/project/ImplementationRegistryService.kt
tools/intellij-plugin/src/main/kotlin/org/dxos/psi/PsiTypeResolver.kt
tools/intellij-plugin/src/main/resources/META-INF/plugin.xml

Adds a marker to the left of service calls, if the service was registered in `service-host.ts` file. 
On click navigates to the implementation.
Not ideal, but parsing the known file is a cheap and easy way for locating implementations.

feat(tools): jump to ServiceImpl for services registered in service-host.ts file

---

docs/content/guide/echo/react/README.md
docs/content/guide/echo/react/queries.md
docs/content/guide/echo/typescript/queries.md

The query docs still referenced protobufs and because they still referenced a missing protobuf file the rest of the snippets failed to update as well.

docs: fix query docs

---

packages/apps/plugins/plugin-deck/src/DeckPlugin.tsx
packages/apps/plugins/plugin-layout/src/LayoutPlugin.tsx
packages/apps/plugins/plugin-markdown/src/extensions.tsx
packages/apps/plugins/plugin-search/src/components/SearchDialog.tsx
packages/sdk/app-framework/src/plugins/common/navigation.ts

- Resolves #7011
As a follow up I'd like to simplify the active id manipulation that `SearchDialog` and `NavTreeContainer` by leveraging the new NavigationAction `ADD_TO_ACTIVE`.
Open to better names for the action, however, I'm not too fussed since they're ephemeral.
Clicking on an internal link multiple times in deck will only scroll and focus the linked object the first time. 
- More discussion here: #7197

fix(authoring): Internal links work with deck

---

packages/ui/react-ui-editor/src/extensions/comments.ts

- Resolves https://github.com/dxos/dxos/issues/7133

fix(comments): Do not warn for comments with empty ranges. 

---

packages/sdk/observability/package.json
packages/sdk/observability/tsconfig.json
pnpm-lock.yaml

Seems like there's no reason for observability to depend on react-client.

chore: replace dependency to fix publish

---

packages/apps/composer-app/scripts/bundle.sh
packages/apps/testbench-app/README.md
packages/apps/testbench-app/scripts/bundle.sh
packages/apps/testbench-app/socket.ini

Add socket config and bundle script to the testbench application.

chore(native): Add socket config and bundle script to `testbench-app`

---

packages/apps/composer-app/vite.config.ts

Source maps are uploaded, but not associated with releases properly.

chore: try bundling sourcemaps with releases

---

packages/core/echo/echo-pipeline/src/automerge/echo-network-adapter.test.ts
packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator.ts

I suppose this might be related to service-host tests becoming flaky recently.

fix(echo): peers not disconnected when replicator is removed

---

packages/sdk/client-services/src/packlets/services/service-context.test.ts

I verified that `joined space is synchronized on device invitations` was influencing `queryCredentials` test result. `await openAndClose(services);` instead of `await openAndClose(services.echoHost);` seems to be fixing shutdown.

chore: fix open & close in tests

---

packages/apps/plugins/plugin-markdown/package.json
packages/apps/plugins/plugin-markdown/src/components/EditorMain.tsx
packages/apps/plugins/plugin-markdown/tsconfig.json
packages/apps/plugins/plugin-thread/package.json
packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx
packages/apps/plugins/plugin-thread/tsconfig.json
packages/sdk/app-framework/src/plugins/common/navigation.ts
pnpm-lock.yaml

After the refactor to the attention plugin, attention should have been removed from the `NavigationPlugin` provides. There were still some places where we were getting attended from the navigation plugin instead of the new attention plugin. This resulted in the attended array being `undefined` in a few places.
- Replace navigation plugin references with attention plugin for attended data
- Fix undefined attended array issues in affected components
- Ensure consistency in attention data source across the application

fix(attention): Issues after attention plugin refactor

---

packages/apps/plugins/plugin-client/src/ClientPlugin.tsx
packages/apps/plugins/plugin-registry/package.json
packages/apps/plugins/plugin-registry/src/components/PluginSettings.tsx
packages/apps/plugins/plugin-registry/tsconfig.json
packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
packages/sdk/client-services/src/packlets/invitations/invitations-handler.ts
packages/sdk/client/src/services/shell.ts
pnpm-lock.yaml

- add metrics to the invitation handler
- add more data from shell results to share events to be able to differentiate between success and failure
- add events for plugin toggling

chore: invitation metrics

---

packages/apps/composer-app/src/main.tsx
packages/apps/composer-app/vite.config.ts

Sourcemaps actually were successfully uploaded yesterday, they just weren't associated with the actual release.
[That's how release name is formed for SDK init.](https://github.com/dxos/dxos/blob/main/packages/sdk/observability/src/helpers/browser-observability.ts#L83)

chore: correctly form sentry release name during sourcemap upload

---

packages/apps/plugins/plugin-deck/src/hooks/useNodeFromSlug.ts
packages/sdk/app-graph/src/graph.ts

- match nodes with slug by id to avoid slug/node mismatches when updating the deck
- trigger resolve node via waitForNode to ensure nodes are loaded when reloading the page

chore: graph fixes

---

packages/apps/plugins/plugin-deck/src/hooks/useNode.ts

The `useNode` hook wasn't properly updating when the id changed if a node was already loaded. 
This was due to the condition `if (nodeState || !id)` which prevented the effect from running if there was an existing nodeState, regardless of whether it matched the new id.

fix(graph): `useNode` latched first resolved node

---

packages/core/halo/credentials/src/presentations/verifier.test.ts
packages/core/halo/credentials/src/presentations/verifier.ts

1. ServiceAccess for an identity is issued and saved in halo.
2. When a device is added AuthorizedDevice is saved in halo.
3. When a device wants to use the service it takes the ServiceAccess credential and signs a presentation providing AuthorizedDevice as a proof that it can sign ServiceAccess presentations.
Service provider can also check proof creationDate and ask to renew a presentation.

feat(halo): verifyPresentation handles ServiceAccess exercise by a device

---

packages/core/echo/echo-db/src/client/echo-client.ts
packages/core/echo/echo-db/src/client/index-query-source-provider.ts

After space root migrations index might still contain references to removed objects. Don't wait for their load in async queries - only load objects where `(id, documentUrl)` is present in the current `spaceRoot.links` map.

fix(echo): async queries don't wait missing object load

---

packages/apps/composer-app/src/help.ts
packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx
packages/apps/plugins/plugin-deck/src/hooks/useNode.ts
packages/apps/plugins/plugin-navtree/src/NavTreePlugin.tsx
packages/sdk/app-graph/src/graph-builder.test.ts
packages/sdk/app-graph/src/graph-builder.ts
packages/sdk/app-graph/src/graph.ts
packages/sdk/app-graph/src/stories/EchoGraph.stories.tsx
packages/ui/react-ui-navtree/src/components/NavTreeItem.tsx
packages/ui/react-ui-navtree/src/helpers.ts

- make graph expansion explicit
- don't expand the graph by default
- make graph expansion async
- swap setTimeout for requestAnimationFrame in a few couple effects

refactor: graph optimizations to avoid long render tasks

---

packages/apps/composer-app/src/main.tsx
packages/apps/composer-app/src/plugins/welcome/WelcomePlugin.tsx
packages/apps/plugins/plugin-space/src/SpacePlugin.tsx

When redeeming a magic link sometimes the original tab is still open.
The first run code should only run in the tab where the identity is created and not in every tab once the identity is created.

chore: ensure first run is only triggered once

---

packages/apps/composer-app/src/main.tsx
packages/apps/composer-app/src/playwright/app-manager.ts
packages/apps/plugins/plugin-debug/src/DebugPlugin.tsx

e2e tests depend on the hooks exposed there

chore: re-create composer global

---

packages/apps/plugins/plugin-deck/src/components/DeckLayout.tsx
packages/apps/plugins/plugin-layout/src/components/MainLayout.tsx
packages/apps/plugins/plugin-thread/src/ThreadPlugin.tsx
packages/ui/react-ui-attention/src/components/AttentionProvider.tsx
packages/ui/react-ui-stack/src/components/Section.tsx

Documents with comments were crashing the app, particularly when refreshing with the 'complementary' part present in the URL. This was caused by a violation of React's Rules of Hooks in the Thread Plugin.
Analytics hooks were being called within a case statement in the Thread Plugin, violating React's rule that hooks must be called at the top level of a component.
- The error manifested far downstream, making initial debugging challenging.
- This highlights the importance of adhering strictly to React's Rules of Hooks.
Consider adding the ESLint Rules of Hooks plugin to catch similar issues earlier in the development process.

fix(threads): React hooks rule violation

---

packages/apps/plugins/plugin-deck/src/hooks/useNode.ts
packages/apps/plugins/plugin-space/src/SpacePlugin.tsx
packages/sdk/app-graph/src/graph-builder.ts

Resolvers which didn't return right away were being unsubscribed from so if the object wasn't already loaded it would fail to be added to the graph.
This updates resolvers to be treated more the way connectors are where there is only one subscription per id.
It prevents them from clobbering each other by breaking out of the loop after the first resolver returns a value.
This PR also updates the SpacePlugin object resolver to subscribe to more signals and ensure that it emits later even if the object isn't ready right away.

fix: unable to load object in plank

---

packages/ui/react-ui-stack/package.json
packages/ui/react-ui-stack/project.json

Previously the exports were general so even though the build was an esm build "for browser" it was being used everywhere

chore: fix react-ui-stack exports

---

packages/core/echo/echo-db/src/core-db/core-database.ts
packages/core/echo/echo-db/src/hypergraph.test.ts
packages/core/functions/src/trigger/trigger-registry.test.ts

Based on [this thread](https://discord.com/channels/837138313172353095/1270491117779026034).
Profiled big (10k) document bathes in testbench, most of the cpu-time is spent in query filter matching. 
Without the change I gave up on waiting with profiler disabled. With the change it still froze the UI but after ~15s items were there. The majority of time is spent in automerge code now.

fix(echo): throttle query updates on document change

---

packages/core/mesh/network-manager/src/signal/ice.ts
packages/core/mesh/network-manager/src/transport/simplepeer-transport.ts

Signal delivery attempt during ice server fetching was crashing and closing the connection.
```
TypeError: Cannot read properties of undefined (reading 'destroy')
at SimplePeerTransport.close (packages/core/mesh/network-manager/dist/lib/browser/chunk-ZAP7RLHV.mjs:3152:16)
at SimplePeerTransportService.close (packages/core/mesh/network-manager/dist/lib/browser/chunk-ZAP7RLHV.mjs:3334:51)
at ServiceHandler.call (packages/common/codec-protobuf/dist/lib/browser/index.mjs:739:28)
at async RpcPeer._callHandler (packages/core/mesh/rpc/dist/lib/browser/index.mjs:627:24)
at async RpcPeer._receive (packages/core/mesh/rpc/dist/lib/browser/index.mjs:303:26)
at async packages/core/mesh/rpc/dist/lib/browser/index.mjs:95:9
at RPC dxos.mesh.bridge.BridgeService.Close 
at RpcPeer.call …
```

fix(mesh): fixed signal delivery race condition

---

packages/ui/react-ui/package.json
pnpm-lock.yaml

This PR:
- upgrades `@radix-ui/react-tooltip`
- appears to resolve #7417.
https://github.com/user-attachments/assets/8020608e-28f2-4594-be7b-74561306d7e5

chore(react-ui): Upgrade `@radix-ui/react-tooltip`

---

packages/apps/plugins/plugin-navtree/src/components/NavTreeContainer.tsx

This PR restores a rule that implements correct overflow.

fix(plugin-navtree): Overflow

---

packages/apps/plugins/plugin-sketch/src/util/base-adapter.ts

Was happening consistently when I was trying to connect block centers with an arrow.
You can see in database update log there's a batch with the same elements in added and deleted lists.
`decode(map[id])` in `updateModel` was returning undefined resulting into a crash inside `TLStore`.

fix(composer): fix tldraw crash when bindings are not found

---

packages/apps/plugins/plugin-sketch/src/SketchPlugin.tsx
packages/apps/plugins/plugin-sketch/src/components/SketchComponent/Sketch.tsx
packages/apps/plugins/plugin-sketch/src/components/SketchComponent/SketchComponent.stories.tsx
packages/apps/plugins/plugin-sketch/src/components/SketchComponent/index.ts
packages/apps/plugins/plugin-sketch/src/components/SketchMain.tsx
packages/apps/plugins/plugin-sketch/src/components/SketchSettings.tsx
packages/apps/plugins/plugin-sketch/src/types.ts

This PR:
- resolves #7459
- removes the obsolete setting which reveals/hides controls on pointer enter/leave
https://github.com/user-attachments/assets/7e0749d8-5940-4a38-bf54-0e3078c535de

fix(plugin-sketch): Show controls on attention

---

packages/apps/composer-app/src/plugins/welcome/components/Welcome/Welcome.tsx
packages/ui/react-ui-theme/src/theme.css

This PR fixes an issue observed in UR where users in a light theme were unable to see text in `WelcomePlugin` since all text was a near-black color on near-black backgrounds.
This now forces dark mode within the `Welcome` component.

fix(plugin-welcome): Apply forced dark mode correctly in `WelcomePlugin`

---

packages/apps/plugins/plugin-registry/src/components/PluginSettings.tsx
packages/apps/plugins/plugin-settings/src/components/SettingsDialog.tsx
packages/sdk/app-framework/src/plugins/PluginHost/PluginContext.tsx
packages/sdk/app-framework/src/plugins/PluginHost/PluginHost.tsx

this prevents plugins which migrate into core from showing up in unexpected places

chore: filter core plugins in settings SettingsDialog

---

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts
packages/core/echo/echo-pipeline/src/automerge/automerge-repo.test.ts
packages/core/echo/echo-pipeline/src/automerge/echo-network-adapter.test.ts
packages/core/echo/echo-pipeline/src/automerge/echo-network-adapter.ts
packages/core/echo/echo-pipeline/src/automerge/echo-replicator.ts
packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator-connection.ts
packages/core/echo/echo-pipeline/src/automerge/mesh-echo-replicator.ts
packages/core/echo/echo-pipeline/src/testing/test-network-adapter.ts
packages/core/mesh/teleport-extension-automerge-replicator/src/automerge-replicator.ts
packages/sdk/client/src/testing/test-builder.ts
packages/sdk/client/src/testing/utils.ts
packages/sdk/client/src/tests/client-services.test.ts
packages/sdk/client/src/tests/halo-persistent.test.ts
packages/sdk/client/src/tests/indexing.test.ts
packages/sdk/client/src/tests/spaces.test.ts

`collection-sync` wasn't working for documents not present locally if they were not loaded in other peer's memory (a document is loaded when it was requested at least once during a session using `query` or `getById`).
The problem was in sharePolicy, since it's spaceKey-based, it wasn't passing on failure to resolve space key from a document.
So `sharePolicy` was never returning true for documents we didn't have making [`.find(documentId)`](https://github.com/dxos/dxos/blob/main/packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts#L468) after collection-sync a no-op.
Other peers still could push documents to us, so replication was working.
Tests were passing because peers were sharing storage. 
Fixed by making a document lookup in peers remote collection state. 
The majority of …

fix(echo): collection-sync for documents not present locally

---

packages/core/echo/echo-db/src/client/index-query-source-provider.ts
packages/core/mesh/network-manager/src/swarm/connection.ts

Don't `log.catch` normal cancellations. Was happening during invitations in running agent and on one-shot invocations like `dx space list`.

fix(cli): don't log.catch normal cancellations

---

docs/content/README.md

docs: fix pill-style link hrefs on docs homepage

---

.idea/compiler.xml

This setting appears to fix TS language server issues observed on a clean build.

chore(.idea): Add compiler setting to fix TS language server issues

---

packages/plugins/plugin-deck/src/DeckPlugin.tsx

- Resolves https://github.com/dxos/dxos/issues/7617
Fullscreen isn't plumbed into the layout system at all currently. Presenter continues to work as expected with this change.
We should implement fullscreen as an enhancement if we desire the functionality. But for now, this will stop people from getting the app stuck in a broken state.

chore(deck): Disable fullscreen action node

---

packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
packages/ui/react-ui-stack/src/components/Stack.tsx

fix(react-ui-stack,react-ui-editor): Remove max-width from stack, apply max-widths to MarkdownEditor toolbar

---

packages/plugins/experimental/plugin-map/src/components/MapDetectLocations.ts

Close #7653. There might be other problems in this module if objects without `id` fields are coming out of `useQuery`, but this will fix the immediate error that occurs within `hasId`.

fix(map): improve hasId check to not use any

---

packages/experimental/plexus/style.css
packages/plugins/experimental/plugin-github/src/components/GithubEchoResolverProviders/SpacePickerTreeItem.tsx
packages/plugins/plugin-navtree/src/components/CommandsTrigger.tsx
packages/plugins/plugin-navtree/src/components/NavTreeFooter.tsx
packages/plugins/plugin-thread/src/components/CommentsContainer.tsx
packages/plugins/plugin-thread/src/components/command-extension.ts
packages/ui/react-ui-editor/src/TextEditor.stories.tsx
packages/ui/react-ui-table/src/components/Cell/CellCombobox.tsx
packages/ui/react-ui-theme/src/styles/components/input.ts
packages/ui/react-ui-theme/src/styles/components/message.ts
packages/ui/react-ui-theme/src/styles/components/select.ts
packages/ui/react-ui/src/components/Breadcrumb/Breadcrumb.stories.tsx

fix: Correct base foreground token is `baseText`

---

packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx

Bidirectional selection was broken when clicking threads in the side-bar when the start range of the comment was 0. 0 is falsy 🙄.

fix(threads): bidirectional linking

---

packages/apps/composer-app/src/plugins/welcome/WelcomePlugin.tsx
packages/common/react-async/src/useAsyncEffect.ts
packages/sdk/shell/src/composites/Shell/Shell.tsx
packages/ui/primitives/react-input/src/PinInput.tsx

- don't create identity during dev if device invitation exists

chore: device invitation cleanup

---

packages/ui/react-ui-editor/src/TextEditor.stories.tsx
packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts

fix: Codemirror task list indentation

---

packages/ui/react-ui-searchlist/src/components/SearchList.tsx
packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts

This PR:
- fixes SearchList colors
- adds a new token `hoverOverlay`
- replaces nonfunctioning classnames with one that uses `hoverOverlay`

fix: SearchList colors

---

packages/plugins/plugin-table/src/components/ObjectTable/hooks/useTableObjects.ts

Trivial change, but making this code idiomatic is helpful since it will appear in a blog post.

refactor: pass undefined as empty query options param

---

package.json
packages/apps/composer-app/vite.config.ts
packages/apps/testbench-app/vite.config.ts
packages/common/keys/src/dxn.ts
packages/core/echo/echo-db/src/core-db/core-database.ts
packages/core/echo/echo-db/src/testing/integration.test.ts
pnpm-lock.yaml
vitest.shared.ts

- Remove `top-level-await-plugin` as it is breaking sourcemaps
- Add `rollup-plugin-sourcemaps` to make vite read sourcemaps of workspace packages
- Preserve class and function names during minification (helps preserve log and context names)
- Only enable tsconfig paths mappings in local dev mode
- Improve error messages in sdk

fix: Source maps for production build

---

packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx
packages/plugins/plugin-sheet/src/components/GridSheet/util.ts

This PR:
- succeeds #7817
- continues resolution of #7615
- binds `DxGrid`’s `AxisResize` events to `SheetModel`’s `columnMeta` and `rowMeta` properties.
Will auto—merge this since the scope is limited and low-risk, but I’d be glad to incorporate any feedback into a follow-up.
https://github.com/user-attachments/assets/e63eeb7a-ccfc-42ce-b2e4-ad7977337bcd

feat(plugin-sheet): Grid axis resize support

---

packages/core/mesh/edge-client/src/edge-client.test.ts
packages/core/mesh/edge-client/src/edge-client.ts
packages/sdk/client-services/src/packlets/spaces/edge-feed-replicator.test.ts
packages/sdk/client-services/src/packlets/spaces/edge-feed-replicator.ts

Fixes the race where edge replicator needs to be opened before edge client is connected for things to work.

fix(edge): immediately start feed replication if edge-client is connected

---

packages/plugins/experimental/plugin-script/src/components/ScriptContainer.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx
packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
packages/plugins/plugin-sheet/src/components/Sheet/Sheet.tsx
packages/plugins/plugin-sheet/src/components/SheetContainer.tsx
packages/plugins/plugin-sketch/src/components/SketchContainer.tsx
packages/plugins/plugin-table/src/components/TableContainer.tsx
packages/plugins/plugin-thread/src/ThreadPlugin.tsx
packages/plugins/plugin-thread/src/components/CommentsContainer.tsx
packages/plugins/plugin-thread/src/components/ThreadComplementary.tsx
packages/ui/react-ui-attention/src/components/AttentionProvider.tsx
packages/ui/react-ui-deck/src/components/PlankHeading/PlankHeading.tsx
packages/ui/react-ui-editor/src/extensions/index.ts

- plank type icons weren't being highlighted properly because they
should be highlighted even if they are an ancestor of the currently
attended item
- consolidate this logic into a single attention hook
- remove unused complementary sidebar heading for comments

chore: ensure type icons use latest attention changes

---

packages/ui/lit-grid/package.json
packages/ui/lit-grid/project.json
packages/ui/lit-grid/tsconfig.json
tsconfig.paths.json

Because `dx-grid` would be substantially more unreadable than it currently is if refactored not to use decorators, it is built with `tsc` like `cli-base` is in order to interoperate with SWC and esbuild.

fix(lit-grid): Build Lit package(s) with tsc

---

packages/plugins/plugin-sheet/src/components/FunctionEditor/FunctionEditor.tsx
packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx
packages/plugins/plugin-sheet/src/components/SheetContainer/SheetContainer.tsx
packages/plugins/plugin-sheet/src/model/formatting-model.ts
packages/ui/lit-grid/src/dx-grid.pcss

This PR:
- adjusts where borders are applied
- fixes the layout of GridSheet alongside FunctionEditor
- applies the surface token to the grid so it responds correctly to attention
- centers cell content by default
- prevents panning within the grid when it doesn’t have attention
- ⚠️ I didn’t yet find a way to prevent deck scrolling _when grid does have attention_
https://github.com/user-attachments/assets/e4a8635f-f2c7-4cff-b92d-9e185a762cd0

fix(plugin-sheet): Polish Grid integration with Composer

---

packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/StatusBar.tsx
packages/plugins/plugin-deck/src/util/overscroll.ts
packages/ui/react-ui-theme/src/config/tailwind.ts
packages/ui/react-ui-theme/src/styles/components/main.ts

This PR fixes several issues (mostly in DeckLayout, but depending on styles made available in Main) that caused judders in the layout when sidebars are opened or closed.
https://github.com/user-attachments/assets/e307d457-7e0f-441b-9164-34d62552de64
https://github.com/user-attachments/assets/37236ae5-94da-4ee9-a645-05bf27b89de3

fix: Main layout smoothness

---

packages/sdk/client-services/src/packlets/identity/identity-manager.ts

Identity becomes ready after device chain is replicated. Wait for it before storing the record.
This ensures we can reconstruct identity on the next app launch.

fix: ensure identity is restorable

---

packages/sdk/client-services/src/packlets/agents/edge-agent-manager.ts
packages/sdk/client-services/src/packlets/identity/identity.ts

Credential processing starts in `space.open`. All listeners must be registered before that.

fix: halo space feeds not getting into the edge replicator

---

packages/plugins/plugin-deck/src/components/DeckLayout/ComplementarySidebar.tsx
packages/plugins/plugin-navtree/src/components/NavTree.tsx
packages/plugins/plugin-sheet/src/defs/util.ts
packages/plugins/plugin-sketch/src/types/diagram.ts
packages/plugins/plugin-table/src/TablePlugin.tsx
packages/ui/react-ui-list/src/components/Tree/TreeItem.tsx

- hook context menu in tree back up
- ensure threads array is initialized in core data types on create
- key the complementary sidebar surface so that it re-renders when
attention changes

chore: minor cleanup

---

packages/plugins/plugin-markdown/src/MarkdownPlugin.tsx
packages/plugins/plugin-markdown/src/components/MarkdownContainer.tsx
packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
packages/plugins/plugin-markdown/src/extensions.tsx
packages/plugins/plugin-sheet/src/extensions/compute.ts
packages/plugins/plugin-sheet/src/extensions/editor/extension.ts
packages/ui/react-ui-editor/project.json
packages/ui/react-ui-editor/src/TextEditor.stories.tsx
packages/ui/react-ui-editor/src/extensions/annotations.ts
packages/ui/react-ui-editor/src/extensions/automerge/automerge.ts
packages/ui/react-ui-editor/src/extensions/automerge/cursor.ts
packages/ui/react-ui-editor/src/extensions/awareness/awareness.ts
packages/ui/react-ui-editor/src/extensions/command/hint.ts
packages/ui/react-ui-editor/src/extensions/command/state.ts
packages/ui/react-ui-editor/src/extensions/comments.ts
packages/ui/react-ui-editor/src/extensions/folding.tsx
packages/ui/react-ui-editor/src/extensions/index.ts
packages/ui/react-ui-editor/src/extensions/markdown/decorate.ts
packages/ui/react-ui-editor/src/extensions/modes.ts
packages/ui/react-ui-editor/src/extensions/selection.ts
packages/ui/react-ui-editor/src/hooks/useTextEditor.ts
packages/ui/react-ui-editor/src/index.ts
packages/ui/react-ui-editor/src/types.ts
packages/ui/react-ui-editor/src/util/cursor.ts
packages/ui/react-ui-editor/src/util/debug.ts
packages/ui/react-ui-editor/src/util/dom.ts
packages/ui/react-ui-editor/src/util/facet.ts
packages/ui/react-ui-editor/src/util/index.ts
packages/ui/react-ui-editor/src/util/react.tsx
tsconfig.paths.json

- createEditorStateStore created by markdown plugin and passed to extensions
- reorganize utils

chore: Clean-up react-ui-editor state management

---

packages/sdk/schema/src/types/types.ts
packages/ui/react-ui-data/src/components/ViewEditor/ViewEditor.tsx
packages/ui/react-ui-list/src/components/List/List.stories.tsx
packages/ui/react-ui-list/src/components/List/ListRoot.tsx

- Resolves https://github.com/dxos/dxos/issues/8104
Fixes rearranging of list items when no `getId` function is provided by implementing a more robust equality check. The issue occurred when comparing drag target data where object references differed despite having the same content.
Previously, the comparison relied on direct reference equality. Now falls back to JSON string comparison when `getId` isn't specified.

fix(react-ui-list): Fix rearranging when `getId` isn't specified

---

packages/devtools/cli/bin/dx.js

Seems like `node --import` flag doesn't use `NODE_PATH` env variable for resolution and just does the node_modules traversal from current to parent. Try registering hooks in process.

chore: try to fix ERR_MODULE_NOT_FOUND

---

packages/core/echo/echo-db/src/proxy-db/mutable-schema.test.ts
packages/core/echo/echo-schema/src/ast/annotations.ts
packages/core/echo/echo-schema/src/handler/ref.ts
packages/core/echo/echo-schema/src/mutable/mutable-schema.ts
packages/core/echo/echo-schema/src/proxy/getter.ts

Relaxes `ref` validation for mutable schema.
Allow matches by typename in addition to strict stored schema id match requirement.

fix: relax dynamic schema validation

---

packages/core/echo/echo-schema/src/proxy/getter.ts

Shouldn't happen, but a precaution in case `getSchema` returns null.

chore: null-pointer precaution

---

packages/apps/composer-app/src/plugins/welcome/WelcomePlugin.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/Plank.tsx

- was missing tab index for planks to allow them to be attended
- welcome was setting solo mode on load and breaking closing of planks

chore: restore functionality for stack next

---

packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
packages/plugins/plugin-table/src/components/TableContainer.tsx
packages/ui/react-ui-stack/src/components/StackItemContent.tsx
packages/ui/react-ui-table/src/components/Table/Table.tsx

This PR:
- fixes an issue where toolbars caused stack sections to have an inline size of `min-content`
- fixes an issue where tables occupied a block size of `min-content` where they shouldn’t

fix: Overflow & layout

---

packages/plugins/plugin-deck/src/components/DeckLayout/ComplementarySidebar.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/Plank.tsx
packages/plugins/plugin-markdown/src/components/MarkdownEditor.tsx
packages/plugins/plugin-navtree/src/components/NavTreeContainer.tsx
packages/plugins/plugin-sheet/src/components/SheetContainer/SheetContainer.tsx
packages/plugins/plugin-sheet/src/components/Toolbar/Toolbar.tsx
packages/plugins/plugin-stack/src/StackPlugin.tsx
packages/ui/react-ui-table/src/components/Table/Table.tsx
packages/ui/react-ui-theme/src/theme.css

This PR makes additional layout & border adjustments so that Stack, Markdown, Table, and Sheet all work in planks, sections, solo, and complementary positions.
The separator border is now included in `--rail-size`.
https://github.com/user-attachments/assets/a6fc41fb-48de-4a64-bf38-f01e86976c05

fix: More pixel pushing

---

packages/ui/lit-grid/src/dx-grid.pcss
packages/ui/lit-grid/src/dx-grid.ts
packages/ui/lit-grid/src/types.ts

This PR introduces touch panning for `dx-grid`
https://github.com/user-attachments/assets/dd93a6d9-4383-4d04-90d0-a6de51639c53

feat(lit-grid): Touch panning

---

packages/plugins/plugin-observability/package.json
packages/plugins/plugin-observability/project.json
packages/plugins/plugin-status-bar/package.json
packages/plugins/plugin-status-bar/project.json
packages/plugins/plugin-table/package.json
packages/ui/react-ui-attention/package.json
packages/ui/react-ui-attention/project.json
packages/ui/react-ui-form/package.json
packages/ui/react-ui-list/package.json
packages/ui/react-ui-mosaic/package.json
packages/ui/react-ui-mosaic/project.json
packages/ui/react-ui-stack/package.json
packages/ui/react-ui-stack/src/components/StackItem.tsx
packages/ui/react-ui-syntax-highlighter/package.json
packages/ui/react-ui-syntax-highlighter/project.json
packages/ui/react-ui-table/package.json
packages/ui/react-ui-table/project.json
packages/ui/react-ui-tabs/package.json
packages/ui/react-ui-tabs/project.json
packages/ui/react-ui-text-tooltip/package.json
packages/ui/react-ui-text-tooltip/project.json
pnpm-lock.yaml
toolbox.json
tools/ridoculous/package.json
tsconfig.paths.json

When ui packages were included in paths vite was optimizing react-ui in
some cases which lead to there being multiple theme contexts. This
likely points to some other issues with the dependency graph, but this
workaround makes everything work (with the caveat that ui packages need
to be rebuilt by watch to update in composer).
Also removes unused dependencies which were causing emotion to be pulled
into the app bundle.

chore: remove ui packages from paths

---

packages/sdk/react-client/package.json
packages/sdk/shell/package.json
pnpm-lock.yaml

dependencies which are not required for the main entrypoints of a
package shouldn't be listed as peers as package managers need to be
overridden if you want to not install them
Resolves #8285

chore: remove problematic peer deps

---

packages/core/echo/echo-db/src/echo-handler/echo-handler.test.ts
packages/core/echo/echo-db/src/echo-handler/echo-handler.ts
packages/core/echo/echo-db/src/proxy-db/mutable-schema.test.ts

The previous fix for echo object field assignment broke automatic object linking when a reactive objects is assigned to echo object.
This PR fixes this and unskips the broken test.
Also fixes unused validation result on array value updates.

fix: reactive objects not being linked on assignment

---

packages/plugins/plugin-markdown/src/hooks/useSelectCurrentThread.tsx
packages/plugins/plugin-sheet/src/integrations/thread-ranges.ts
packages/plugins/plugin-thread/src/components/ThreadComplementary.tsx

These intent handlers were not returning anything so the intent system
thought the intent wasn't handled, this lead to the layout handling it
and focus on the thread input being lost when it shouldn't be.

fix: resolve scroll intents when applied

---

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts
packages/core/echo/echo-pipeline/src/db-host/echo-host.ts
packages/sdk/client-services/src/packlets/services/service-context.ts

Random IDs were just easier to implement.
Doesn't work well with edge automerge-replicator, because it maintains multiple mappings to the same peer.

fix: use deviceKey for automerge peer id is identity is set

---

packages/core/echo/echo-pipeline/package.json
packages/core/echo/echo-pipeline/src/edge/echo-edge-replicator.test.ts
packages/core/echo/echo-pipeline/src/edge/echo-edge-replicator.ts
packages/sdk/client/src/tests/spaces.test.ts
pnpm-lock.yaml

The "accept a document if access control can't be checked, but it's in the remote peer's collection" logic was present in mesh, but not edge replicator. 
This was causing a bug where documents were pushed to wrong space replicator and an infinite sync-spinner would appear in composer.
Copied the logic and added more tests for share policy.

fix: fixed pushing document to wrong edge replicator

---

packages/core/echo/echo-db/src/client/repo-proxy.test.ts
packages/core/echo/echo-db/src/core-db/automerge-doc-loader.test.ts
packages/core/echo/echo-pipeline/src/automerge/space-collection.ts
packages/core/echo/echo-pipeline/src/db-host/data-service.ts
packages/core/echo/echo-pipeline/src/db-host/echo-host.ts
packages/core/echo/echo-pipeline/src/db-host/index.ts
packages/core/echo/echo-pipeline/src/db-host/space-state-manager.ts

Edge is sending heads of all the documents from space including those from previous epochs. 
Include the current space root document id so that edge can use it to send the relevant documents only.

fix: make space root doc id a part of collectionId

---

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts
packages/core/echo/echo-pipeline/src/automerge/collection-synchronizer.ts
packages/core/echo/echo-pipeline/src/db-host/echo-host.ts

`CollectionSynchronizer` gets polluted with collections during epoch credential processing. Added cleanup logic.

fix: do not sync old collections

---

packages/ui/react-ui-theme/package.json
packages/ui/react-ui-theme/src/config/tokens/Tokens.stories.tsx
pnpm-lock.yaml

This PR
- begins a resolution of #8262
- by using the new @ch-ui/tokens which has audit features
- this makes it much easier to identify token sources and determine how to adjust colors going forward

feat(react-ui-theme): Physical color token audit story

---

packages/core/echo/echo-pipeline/src/automerge/automerge-host.ts
packages/core/echo/echo-pipeline/src/automerge/collection-synchronizer.ts
packages/core/echo/echo-pipeline/src/automerge/echo-network-adapter.ts
packages/core/echo/echo-pipeline/src/db-host/echo-host.ts
packages/core/echo/echo-pipeline/src/space/space-manager.ts
packages/experimental/react-metagraph/src/useMetagraph.tsx
packages/sdk/client-services/src/packlets/services/service-context.ts

Fixes two edge cases of sharePolicy check for documents not present locally. Was caught by a consistently failing test in edge.
1. Root document replication right after a space invite. We don't have the document locally to check access.spaceKey, but we can't open the space to start collection-sync, so the space gets stuck in `initializing` state.
2. Another potential edge-case that came to mind while working on a fix. Peer A creates a document and sends a sync to B before collection-sync completes for B to learn which space the new document belongs to. When collection-sync completes B won't start replication with A because `sharePolicy: false` was cached on automerge-repo level.

fix: replication for documents not present locally

---

packages/core/functions/src/types/types.ts
packages/plugins/experimental/plugin-automation/src/components/AutomationPanel/AutomationPanel.tsx
packages/plugins/experimental/plugin-automation/src/translations.ts

* Added `Email` trigger type to allowed schema literals list.
* Updated plugin automation to provide a "copy" action.
* Set `automationTargetId` in trigger meta.

feat: added email trigger type

---

packages/core/echo/echo-pipeline/src/edge/echo-edge-replicator.ts
packages/core/echo/echo-pipeline/src/edge/inflight-request-limiter.ts

inflightRequestBalance was going off because we were incrementing inflight request on messages of any type, but decrementing it only on receiving sync messages.

fix: inflight request counter being incremented not only on sync messages

---

packages/ui/react-ui-editor/src/components/EditorToolbar/EditorToolbar.tsx
packages/ui/react-ui-editor/src/components/EditorToolbar/util.ts

This PR
- fixes an issue where EditorToolbar was not specifying `iconOnly` when it should

fix: Restore `iconOnly` in EditorToolbar.

---

packages/plugins/plugin-deck/src/components/DeckLayout/ContentEmpty.tsx

This PR addresses one concern from #8550.

fix(plugin-deck): Deduplicate sidebar toggle in empty state

---

packages/ui/react-ui-stack/src/components/StackItemSigil.tsx

This PR:
- removes SackItemSigil’s tooltip, since the sigil is often autofocused on mount and the tooltip is not necessary in this case

fix(react-ui-stack): Remove tooltip from StackItemSigil

---

packages/devtools/devtools/src/components/performance/StatsPanel.tsx
packages/plugins/plugin-debug/src/components/DebugStatus.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/ComplementarySidebar.tsx
packages/plugins/plugin-space/src/components/SyncStatus/SyncStatus.tsx
packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx
packages/ui/react-ui-theme/src/config/tokens/lengths.ts

This PR:
- moves a typo-misapplication of the `inert` attribute
- deconflicts the `gridLine` token to fix grid line colors
- restores `!` on cell editor content to fix spacing
- fixes Space sync status popover
- fixes debug panel popover

fix: `inert` typo and other minor fixes

---

packages/plugins/experimental/plugin-kanban/src/components/KanbanViewEditor.tsx
packages/plugins/plugin-table/src/components/ObjectDetailsPanel.tsx
packages/plugins/plugin-table/src/components/TableContainer.tsx
packages/plugins/plugin-table/src/components/TableViewEditor.tsx
packages/sdk/react-client/src/echo/index.ts
packages/sdk/react-client/src/echo/useSchema.ts
packages/ui/react-ui-attention/src/components/SelectionProvider.tsx
packages/ui/react-ui-kanban/src/components/Kanban.stories.tsx
packages/ui/react-ui-table/src/components/Table/Table.stories.tsx

- **`useSelectionActions` was breaking the rules of hooks**
@wittjosiah It turns out that the selection provider breaking the rules of hooks was the reason that the `useSchema` hook was breaking the other day. So I've restored that as well and gotten rid of the duplicated code. I tested it both in the stories and in composer, it's working great.

fix(tables): Storybook crash

---

packages/plugins/experimental/plugin-kanban/package.json
packages/plugins/experimental/plugin-kanban/src/KanbanPlugin.tsx
packages/plugins/experimental/plugin-kanban/src/capabilities/intent-resolver.ts
packages/plugins/experimental/plugin-kanban/src/capabilities/react-surface.tsx
packages/plugins/experimental/plugin-kanban/src/types.ts
packages/plugins/experimental/plugin-kanban/tsconfig.json
packages/ui/react-ui-form/src/components/Form/index.ts
packages/ui/react-ui-kanban/src/components/Kanban.stories.tsx
packages/ui/react-ui-kanban/src/defs/kanban-model.ts
packages/ui/react-ui-kanban/src/testing/initialize-kanban.ts
packages/ui/react-ui-kanban/src/util.ts
pnpm-lock.yaml

Adds type selection and initial pivot column options (from available `single-select` fields) during Kanban creation.
https://github.com/user-attachments/assets/50aa1f74-7ce7-421f-9861-194d3f50ade9

feat(kanban): Create kanban from existing type

---

packages/plugins/experimental/plugin-automation/src/components/Thread/Thread.tsx
packages/ui/react-ui-components/src/ScrollContainer/ScrollContainer.stories.tsx
packages/ui/react-ui-components/src/ScrollContainer/ScrollContainer.tsx

This PR:
- refactors to use `flex-col-reverse` to achieve native scroll anchoring of thread content
- applies the fade only when overflowing _and_ when not within 16 px of the top of the thread
https://github.com/user-attachments/assets/94b6184c-61a1-4ab1-8e61-e98804541ec9

fix: `ScrollContainer` native scrolling

---

packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx

This PR:
- resolves #8777.
- fixes a misalignment between CellEditor and grid cells.

fix(react-ui-grid): Put arrow-left/-right keys behind cmd-/ctrl- modifier

---

packages/plugins/experimental/plugin-automation/src/capabilities/complementary-panel.ts

When subscribe is called with `{ fire: true }` is synchronously calls
the callback which accesses `objects` and subscribes to the query
signal. Placing within `untracked` resolves this.

fix: don't subscribe to query

---

packages/common/plate/src/InteractiveDirectoryTemplate.ts
packages/common/plate/src/api.ts
packages/common/plate/src/index.ts
packages/common/plate/src/main.ts

Removes circular imports in plate which were causing the docs build to
fail.

refactor: remove circular imports

---

packages/devtools/devtools/package.json
packages/devtools/devtools/src/panels/echo/QueuesPanel/QueuesPanel.tsx
packages/devtools/devtools/src/panels/echo/QueuesPanel/index.ts
packages/devtools/devtools/src/panels/echo/index.ts
packages/devtools/devtools/tsconfig.json
packages/plugins/plugin-debug/src/capabilities/app-graph-builder.ts
packages/plugins/plugin-debug/src/capabilities/react-surface.tsx
packages/plugins/plugin-debug/src/translations.ts
packages/plugins/plugin-debug/src/types.ts
pnpm-lock.yaml

follow up work should restore the space selector and display a table of known queues based on those linked from the space properties

feat: basic queue viewer

---

packages/plugins/plugin-registry/src/components/PluginList.tsx
packages/plugins/plugin-registry/src/components/RegistryContainer.tsx

This PR:
- fixes an issue with layout containment and redundant `overflow-y-auto` in `ReistryPlugin`.
https://github.com/user-attachments/assets/b0e24b38-7dc1-4e67-8db5-3e6bd8aaf764

fix(plugin-registry): Overflow issues

---

packages/plugins/plugin-kanban/src/components/KanbanViewEditor.tsx
packages/sdk/schema/package.json
packages/sdk/schema/src/projection.test.ts
packages/sdk/schema/src/projection.ts
packages/sdk/schema/src/view.ts
packages/ui/react-ui-form/src/components/ViewEditor/ViewEditor.tsx
packages/ui/react-ui-form/src/translations.ts
packages/ui/react-ui-kanban/src/components/Kanban.tsx
packages/ui/react-ui-kanban/src/defs/kanban-model.ts
packages/ui/react-ui-list/src/components/List/List.tsx
packages/ui/react-ui-list/src/components/List/ListItem.tsx
pnpm-lock.yaml

- Resolves #8591 
---
- Deletion removes the field from the schema and will *impact* all other views
- Delineate between hiding and deleting
- Show hidden fields (no rearrange?)
- This will allow us to preserve field IDs so that if the user toggles hide/unhide in a kanban, the column won't get nuked

feat(views): Hidden fields

---

packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/ui/react-ui/src/components/Main/Main.tsx

fix(plugin-deck): Add an ErrorBoundary to DeckLayout’s Dialogs

---

packages/plugins/plugin-deck/src/capabilities/intent-resolver.ts
packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/plugins/plugin-deck/src/types.ts
toolbox.json
tsconfig.paths.json

deck state is persisted to localstorage so new fields need to be optional else they can cause crashes when accessing missing state

fix: deck crash

---

packages/plugins/plugin-thread/src/capabilities/intent-resolver.ts

Another instance of using a number as a boolean.
- Resolves #8859

fix: thread message deletion

---

packages/plugins/experimental/plugin-inbox/src/components/Mailbox/MailboxContainer.tsx
packages/plugins/experimental/plugin-inbox/src/translations.ts
packages/plugins/plugin-deck/src/components/DeckLayout/NodePlankHeading.tsx

This PR restores the empty mailbox state and removes the Status which was rendered there in error.

fix(plugin-inbox): Empty mailbox state.

---

packages/apps/testbench-app/src/components/ItemTable.tsx
packages/devtools/devtools/src/components/MasterDetailTable.tsx
packages/devtools/devtools/src/panels/client/TracingPanel/LogTable.tsx
packages/devtools/devtools/src/panels/client/TracingPanel/TracingPanel.tsx
packages/devtools/devtools/src/panels/echo/ObjectsPanel/ObjectsPanel.tsx
packages/devtools/devtools/src/panels/echo/QueuesPanel/QueuesPanel.tsx
packages/devtools/devtools/src/panels/echo/SpaceInfoPanel/FeedTable.tsx
packages/devtools/devtools/src/panels/echo/SpaceInfoPanel/PipelineTable.tsx
packages/devtools/devtools/src/panels/echo/SpaceListPanel/SpaceListPanel.tsx
packages/devtools/devtools/src/panels/edge/InvocationTracePanel/InvocationTracePanel.tsx
packages/devtools/devtools/src/panels/edge/InvocationTracePanel/LogPanel.tsx
packages/devtools/devtools/src/panels/mesh/SignalPanel/SignalStatusTable.tsx
packages/devtools/devtools/src/panels/mesh/SwarmPanel/SwarmPanel.tsx
packages/plugins/plugin-space/src/capabilities/schema-tools.ts
packages/sdk/schema/src/construction.ts
packages/ui/react-ui-table/src/components/Table/DynamicTable.stories.tsx
packages/ui/react-ui-table/src/components/Table/DynamicTable.tsx
packages/ui/react-ui-table/src/components/Table/Table.stories.tsx
packages/ui/react-ui-table/src/components/Table/Table.tsx
packages/ui/react-ui-table/src/util/dynamic-table.ts

Small refactor directionally to normalize props.
- avoid passing mutually exclusive options to components.
- avoid mixing of types (e.g., "name" used for "typename") might break assumptions.
- consistent ordering of properties (e.g., onX handlers at end).
TODO(zaymonfc)
- normalize props with hooks.
- remove divs

chore: Small refactor of dynamic table props

---

packages/ui/lit-ui/project.json
packages/ui/react-ui-table/src/playwright/smoke.spec.ts
tools/stories/config/e2e/main.mts

This PR:
- removes an unintended e2e task in the project.json for `lit-ui`
- adds `react-ui-table` to the set of e2e stories, which was missing

fix: `lit-ui` and `react-ui-table` e2e

---

packages/ui/react-ui-kanban/src/components/Kanban.tsx

This PR:
- fixes #9035.
https://github.com/user-attachments/assets/9289c8ea-2d3e-427b-9797-bd5f4343acbd

fix(plugin-kanban): Restore space in empty Stack

---

packages/plugins/plugin-help/src/components/Shortcuts/ShortcutsDialog.tsx
packages/plugins/plugin-navtree/src/components/L1Panels.tsx
packages/plugins/plugin-navtree/src/components/NavTreeItemAction.tsx
packages/plugins/plugin-navtree/src/components/NavTreeItemColumns.tsx
packages/plugins/plugin-navtree/src/components/types.ts
packages/plugins/plugin-navtree/src/translations.ts
packages/plugins/plugin-registry/src/components/PluginItem.tsx
packages/plugins/plugin-space/src/capabilities/app-graph-builder.ts
packages/plugins/plugin-space/src/components/SpacePresence.tsx
packages/plugins/plugin-space/src/components/SyncStatus/Space.tsx
packages/plugins/plugin-space/src/translations.ts
packages/plugins/plugin-space/src/util.tsx
packages/ui/lit-ui/src/dx-avatar/dx-avatar.pcss
packages/ui/react-ui-attention/src/components/AttentionGlyph.tsx
packages/ui/react-ui-editor/src/extensions/folding.tsx
packages/ui/react-ui-list/src/components/Tree/TreeItemToggle.tsx
packages/ui/react-ui/src/components/Avatars/Avatar.tsx

This PR:
- resolves some of #9038
- resolves #9037
- increases the size of the back button for alternate trees
- increases the size of L1 heading actions
- enforces the `bold` icon variant for all icons of size `3` or less
- uses the `faders` icon for all entity-specific settings items, leaving `gear` exclusively for app-wide settings
https://github.com/user-attachments/assets/75b4e47d-86ab-4cb1-8bfb-51f1a234eed2

fix: L1 and Plank heading polish

---

packages/plugins/plugin-deck/src/components/Plank/PlankHeading.tsx
packages/plugins/plugin-space/src/components/SpacePresence.tsx
packages/ui/lit-ui/src/dx-avatar/dx-avatar.pcss

This PR:
- fixes a small issue with SpacePresence in the Plank heading

fix: SpacePresence layout

---

packages/core/echo/echo-pipeline/src/edge/echo-edge-replicator.test.ts
packages/core/mesh/edge-client/src/edge-ws-connection.ts
packages/core/mesh/edge-client/src/edge-ws-muxer.ts
packages/core/mesh/edge-client/src/testing/test-utils.ts

* Simple protocol for passing large (>1MB) messages over edge websocket connection:
Reserve the first byte for flags.
`0000 0001` means the message contains a part of a larger message and the next byte is a channel id. Messages from different channels might interleave.
`0000 0010` means the message terminates a sequence of larger message chunks. All the accumulated chunks can be concatenated and interpreted as a single Message proto binary. 
* Client only enables segmentation if response protocols don't contain `edge-ws-v0`.
* `WebSocketMuxer` API allows simple integration with edge router.
* `WebSocketMuxer` send ensures that websocket buffered amount doesn't exceed 1MB when sending larger messages. Smaller messages are enqueued immediately.
*  `WebSocketMuxer` send resolves immediately …

feat: edge websocket arbitrary message size support

---

packages/core/mesh/edge-client/src/edge-ws-connection.ts
packages/core/mesh/edge-client/src/edge-ws-muxer.ts

The check was accidentally removed when muxing was added.
Muxing is disabled for now, so the old path gets executed.

fix: bring missing check back

---

packages/plugins/plugin-deck/src/components/DeckLayout/Popover.tsx
packages/plugins/plugin-inbox/src/components/Message/Message.tsx
packages/plugins/plugin-markdown/src/components/MarkdownEditor/MarkdownEditor.tsx
packages/plugins/plugin-markdown/src/components/MarkdownPreview/MarkdownPreview.stories.tsx
packages/plugins/plugin-preview/src/types.ts
packages/plugins/plugin-space/src/components/PopoverRenameSpace.tsx
packages/plugins/plugin-storybook-layout/src/components/Layout.tsx
packages/plugins/plugin-transcription/src/components/Transcript/Transcript.tsx
packages/ui/react-ui-components/src/ScrollContainer/ScrollContainer.tsx
packages/ui/react-ui-stack/src/components/StackItemContent.tsx
packages/ui/react-ui-theme/src/styles/layers/size.css

This PR:
- sets preview popovers to use `popover-consistent-width`, which aims for 20rem but doesn’t exceed the available space.
- removes the `modal` flag on deck popovers
- sets the `hideWhenDetached` flag on deck and storybook popovers so they hide when the anchor becomes occluded
- sets `collisionBoundary` based on the closest `[data-popover-collision-boundary]` element
https://github.com/user-attachments/assets/41aacf3f-cc83-4f51-8833-66b63f5dcad1

fix: Popover size, hide when occluded, more constrained boundaries

---

packages/plugins/plugin-preview/src/Preview.stories.tsx

This PR:
- does what it says on the tin
https://github.com/user-attachments/assets/4f8e02cb-2d66-480d-b70b-c7c03e8a69ca

fix: Restore missing `role` to preview card stories

---

packages/apps/composer-app/index.html

This PR:
- fixes a CSS layer order issues in bundled versions of Composer

fix: CSS `@layer` order race condition

---

tools/lit-stories/config/all/preview-head.html
tools/stories/.storybook/preview-head.html

This PR fixes an `@layer` order definition race condition when bundling storybooks.

fix: Storybook `@layer` bundling

---

packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.stories.tsx
packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx
packages/ui/lit-grid/src/dx-grid.ts
packages/ui/react-ui-grid/src/CellEditor/CellEditor.tsx
packages/ui/react-ui-grid/src/Grid/Grid.tsx
packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts

This PR does what it says on the tin.
https://github.com/user-attachments/assets/00309131-d9ee-4fc5-90fd-18e856f43dc8

fix: Grid e2e and visual fixes, input color token fix

---

packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/plugins/plugin-deck/src/components/Plank/Plank.tsx
packages/plugins/plugin-deck/src/components/Plank/PlankControls.tsx
packages/plugins/plugin-deck/src/components/Plank/PlankHeading.tsx

This PR:
- fixes plank heading controls when multiplank deck is disabled
- applies the `hoverableControls` pattern to all plank heading content except the controls when in fullcreen
https://github.com/user-attachments/assets/d608b149-dbb3-43e2-9788-2bc59ceb9f25

feat(plugin-deck): Persistent fullscreen chrome

---

packages/plugins/plugin-preview/src/components/ContactCard.tsx
packages/plugins/plugin-preview/src/components/OrganizationCard.tsx
packages/ui/lit-theme-editor/.eslintrc.cjs
packages/ui/lit-theme-editor/LICENSE
packages/ui/lit-theme-editor/README.md
packages/ui/lit-theme-editor/package.json
packages/ui/lit-theme-editor/project.json
packages/ui/lit-theme-editor/src/dx-theme-editor/dx-range-spinbutton.ts
packages/ui/lit-theme-editor/src/dx-theme-editor/dx-theme-editor-physical-colors.ts
packages/ui/lit-theme-editor/src/dx-theme-editor/dx-theme-editor-semantic-colors.ts
packages/ui/lit-theme-editor/src/dx-theme-editor/dx-theme-editor.lit-stories.ts
packages/ui/lit-theme-editor/src/dx-theme-editor/dx-theme-editor.pcss
packages/ui/lit-theme-editor/src/dx-theme-editor/dx-theme-editor.ts
packages/ui/lit-theme-editor/src/dx-theme-editor/index.ts
packages/ui/lit-theme-editor/src/dx-theme-editor/util.ts
packages/ui/lit-theme-editor/src/index.ts
packages/ui/lit-theme-editor/tsconfig.json
packages/ui/react-ui-kanban/src/components/Kanban.tsx
packages/ui/react-ui-theme/src/config/tokens/index.ts
packages/ui/react-ui-theme/src/config/tokens/physical-colors.ts
packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts
pnpm-lock.yaml
release-please-config.json
tsconfig.all.json

This PR:
- increments `Kanban`’s color token application
- adds a semantic token `cardSurface`, initially equivalent to `headerSurface`, for patterns which should be raised subtly against `baseSurface`
- begins fleshing-out low-level componentry for adjusting token values in Storybooks and possibly Composer as well
https://github.com/user-attachments/assets/4e534b2d-857c-48a0-b156-c907c3fe4e0f

feat: Kanban increment, theme tooling

---

toolbox.json
tools/executors/toolbox/src/toolbox.ts
tsconfig.paths.json

This PR:
- temporarily fixes an issue caused by including `lit-` packages in toolbox’s configuration

fix: `lit-` SWC exclusion

---

packages/plugins/plugin-deck/src/capabilities/settings.ts
packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/plugins/plugin-deck/src/components/DeckSettings/DeckSettings.tsx
packages/plugins/plugin-deck/src/translations.ts
packages/plugins/plugin-deck/src/types.ts
packages/ui/react-ui-theme/src/styles/layers/focus-ring.css
packages/ui/react-ui/src/components/Tooltip/Tooltip.tsx

This PR:
- adds a setting in DeckPlugin for “hiding focus”
- when focus is “hidden”, focus rings are transparent and tooltip triggers do not react to focus events
- this is meant to address broader concerns about focus mentioned in #9153
https://github.com/user-attachments/assets/646c8b4e-95a8-4e4f-86d1-cd3a9de83eb7

feat: Hide focus

---

packages/plugins/plugin-deck/src/capabilities/settings.ts
packages/plugins/plugin-deck/src/components/DeckLayout/DeckLayout.tsx
packages/plugins/plugin-deck/src/components/DeckSettings/DeckSettings.tsx
packages/plugins/plugin-deck/src/components/Plank/Plank.tsx
packages/plugins/plugin-deck/src/components/Sidebar/SidebarButton.tsx
packages/plugins/plugin-deck/src/translations.ts
packages/plugins/plugin-deck/src/types.ts
packages/plugins/plugin-navtree/src/components/NavTreeItem/NavTreeItemAction.tsx
packages/plugins/plugin-navtree/src/components/Sidebar/L0Menu.tsx
packages/ui/react-ui-menu/src/components/DropdownMenu.tsx
packages/ui/react-ui-menu/src/components/ToolbarMenu.tsx
packages/ui/react-ui-pickers/src/components/EmojiPicker/EmojiPicker.tsx
packages/ui/react-ui-pickers/src/components/PickerButton/PickerButton.tsx
packages/ui/react-ui-stack/src/components/StackItem/StackItemSigil.tsx
packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts
packages/ui/react-ui-theme/src/styles/components/main.ts
packages/ui/react-ui-theme/src/styles/layers/focus-ring.css
packages/ui/react-ui/src/components/Buttons/IconButton.tsx
packages/ui/react-ui/src/components/Main/Main.tsx
packages/ui/react-ui/src/components/Tooltip/Tooltip.tsx

This PR:
- reverts #9263
- fixes Main and Plank focus rings
- applies `neutral` to focus rings
- disables opening tooltips on focus
https://github.com/user-attachments/assets/00c73edd-35af-478e-8a43-ff44facc98cf

fix: Focus, tooltips

---

packages/ui/react-ui-kanban/src/components/Kanban.tsx
packages/ui/react-ui-stack/src/components/Stack/Stack.tsx

This PR:
- makes the entire Kanban column the drop element
https://github.com/user-attachments/assets/7e4d579c-5ddf-4b53-b602-acd8e46c1de0

feat(react-ui-kanban): Better column drop element

---

packages/plugins/plugin-deck/src/components/Plank/PlankHeading.tsx
packages/plugins/plugin-deck/src/components/Sidebar/ComplementarySidebar.tsx
packages/plugins/plugin-navtree/src/components/Sidebar/L0Menu.tsx
packages/plugins/plugin-navtree/src/components/Sidebar/L1Panel.tsx
packages/plugins/plugin-sheet/src/components/FunctionEditor/FunctionEditor.tsx
packages/plugins/plugin-space/src/components/PopoverRenameObject.tsx
packages/plugins/plugin-space/src/components/PopoverRenameSpace.tsx
packages/ui/react-ui-editor/src/defaults.ts
packages/ui/react-ui-theme/src/config/tailwind.ts
packages/ui/react-ui-theme/src/config/tokens/sememes-system.ts
packages/ui/react-ui-theme/src/styles/components/input.ts
packages/ui/react-ui-theme/src/styles/components/menu.ts
packages/ui/react-ui-theme/src/styles/components/popover.ts
packages/ui/react-ui-theme/src/styles/layers/checkbox.css
packages/ui/react-ui-theme/src/styles/layers/focus-ring.css
packages/ui/react-ui-theme/src/styles/layers/main.css
packages/ui/react-ui/src/testing/decorators/withSurfaceVariantsLayout.tsx

This PR:
- adjusts the neutral theme cadence to align with shadcn’s
- increases border radii, adds some padding where needed
- restores `subduedSeparator` as a distinct token
- restores `accentFocusIndicator` and applies to elements with `.dx-focus-ring*[data-variant='primary']`

feat: Theme increment

---

packages/plugins/plugin-deck/src/components/Plank/PlankHeading.tsx
packages/plugins/plugin-navtree/src/NavTreePlugin.tsx
packages/plugins/plugin-navtree/src/components/NavTreeItem/NavTreeItemColumns.tsx
packages/plugins/plugin-space/src/util.tsx

- control which actions are shown where by disposition
- comment out non-functioning shortcuts
- fix expose of solo item on load

fix: navtree actions cleanup

---

packages/common/effect/src/jsonPath.ts
packages/ui/react-ui-form/src/components/FieldEditor/FieldEditor.stories.tsx
packages/ui/react-ui-form/src/components/FieldEditor/FieldEditor.test.tsx
packages/ui/react-ui-form/src/components/testing.tsx

- Resolves #9355
- Fixes `FieldEditor` stories

fix: Field editor `property` should validate correctly

---

packages/plugins/plugin-inbox/src/components/Mailbox/MailboxContainer.tsx
packages/ui/react-ui-stack/src/components/StackItem/StackItemContent.tsx

This PR:
- fixes Mailbox’s layout
- adds a `layoutManaged` flag to `StackItem.Content` in case the consumer will provide its own grid layout (as in this case)

fix: Mailbox layout

---

.github/workflows/check-buildjet.yml
.github/workflows/check.yml
.github/workflows/validate-pr-title.yaml

- don't run ci on all pushes to reduce the number of runs
- include merge_group trigger to allow for merge queue

ci: tweak triggers

---

packages/plugins/plugin-markdown/src/components/MarkdownPreview/MarkdownPreview.tsx
packages/plugins/plugin-preview/src/capabilities/react-surface.tsx
packages/plugins/plugin-preview/src/components/ContactCard.tsx
packages/plugins/plugin-preview/src/components/OrganizationCard.tsx
packages/plugins/plugin-preview/src/components/ProjectCard.tsx
packages/plugins/plugin-search/src/components/SearchResults/SearchResults.tsx
packages/ui/react-ui-editor/src/stories/Preview.stories.tsx
packages/ui/react-ui-form/src/components/testing.tsx
packages/ui/react-ui-graph/src/components/Graph/Graph.stories.tsx
packages/ui/react-ui-kanban/src/components/Kanban.tsx
packages/ui/react-ui-stack/src/exemplars/Card/Card.stories.tsx
packages/ui/react-ui-stack/src/exemplars/Card/Card.tsx
packages/ui/react-ui-stack/src/exemplars/Card/CardDragPreview.tsx
packages/ui/react-ui-stack/src/exemplars/Card/fragments.ts
packages/ui/react-ui-stack/src/exemplars/CardStack/CardStack.stories.tsx
packages/ui/react-ui-stack/src/exemplars/CardStack/CardStack.tsx
packages/ui/react-ui-theme/src/util/mx.ts

This PR:
- renames `Card.Root` as `CardStack.Item`
- renames `Card.Content` as `Card.StaticRoot`
- renames `Card.Container` as `Card.SurfaceRoot`
- adjusts some other density/spacing issues

refactor: Rename Card subcomponents

---

packages/core/artifact-testing/src/plugins.tsx
packages/plugins/plugin-chess/src/capabilities/react-surface.tsx
packages/plugins/plugin-chess/src/components/ChessContainer.stories.tsx
packages/plugins/plugin-chess/src/components/ChessContainer.tsx
packages/plugins/plugin-deck/src/components/DeckLayout/Popover.tsx
packages/plugins/plugin-map/src/capabilities/react-surface.tsx
packages/plugins/plugin-markdown/src/capabilities/react-surface.tsx
packages/plugins/plugin-markdown/src/components/MarkdownContainer.tsx
packages/plugins/plugin-markdown/src/components/MarkdownPreview/MarkdownPreview.stories.tsx
packages/plugins/plugin-markdown/src/components/MarkdownPreview/MarkdownPreview.tsx
packages/plugins/plugin-preview/src/capabilities/react-surface.tsx
packages/plugins/plugin-preview/src/testing/PopoverPreviews.stories.tsx
packages/plugins/plugin-preview/src/testing/util.tsx
packages/plugins/plugin-space/src/capabilities/react-surface.tsx
packages/plugins/plugin-storybook-layout/src/components/Layout.tsx
packages/plugins/plugin-table/src/capabilities/react-surface.tsx
packages/plugins/plugin-table/src/components/TablePreview.stories.tsx
packages/ui/react-ui-canvas-compute/src/shapes/Surface.tsx
packages/ui/react-ui-editor/src/stories/Preview.stories.tsx
packages/ui/react-ui-graph/src/components/Graph/Graph.stories.tsx
packages/ui/react-ui-stack/src/exemplars/Card/Card.tsx
packages/ui/react-ui-stack/src/testing/CardContainer.tsx
packages/ui/react-ui-table/src/components/Table/Table.tsx

This PR:
- renames roles such that all roles considered by `Card.SurfaceRoot` begin with `card--`
- `transclusion` -> `card--transclusion`
- `popover` -> `card--popover`
- `canvas-node` -> `card--extrinsic`
- Adjusts ChessContainer and ChessPlugin’s react-surface.

chore: Surface name refactor

---

scripts/api-diff.mjs

Adds a new script to analyze and compare public TypeScript APIs between npm package versions.
- Two modes: print all APIs or compare changes between versions  
- Handles `export * from` statements and named re-exports
- Uses TypeScript compiler API for accurate analysis
- Sorts output alphabetically with emoji indicators
- Clean markdown output with TypeScript code blocks
```bash
node scripts/api-diff.mjs <package-name> <version>
node scripts/api-diff.mjs <package-name> <version> --changes <old-version>
```
```bash
node scripts/api-diff.mjs @dxos/echo-db 0.8.3
node scripts/api-diff.mjs @dxos/echo-db 0.8.3 --changes 0.7.4
```

chore: Add API diff script with re-export support

---

packages/ui/lit-grid/src/dx-grid.ts
packages/ui/react-ui-table/src/components/Table/Table.tsx

This PR:
- causes `dx-grid` to dispatch an empty edit request if default is not prevented on a backspace/delete keydown
- adjusts Table’s keydown handler, now on the capture phase, to `preventDefault` if the model is able to clear the value without editing, otherwise it lets dx-grid emit the empty edit request
https://github.com/user-attachments/assets/e9ee59b6-cea6-4dbc-9b86-7be1809b0bef

feat: `dx-grid` handling of backspace/delete

---

packages/ui/react-ui-table/src/components/Table/Table.stories.tsx

This PR fixes Table e2e by restoring `LabelAnnotation` to the test schema.

fix: Table e2e

---

packages/ui/react-ui-table/src/components/Table/Relations.stories.tsx
packages/ui/react-ui-table/src/model/table-model.ts
packages/ui/react-ui-table/src/playwright/smoke.spec.ts

This PR:
- switches to use the recommended `getSnapshot`
- adds an e2e test case so this doesn’t regress
https://github.com/user-attachments/assets/4bda2fd3-8618-4066-8423-bcf4995772e7

fix: deprecated `getSnapshot` causing schema RTE

---

packages/ui/lit-grid/src/dx-grid.ts
packages/ui/lit-grid/src/types.ts
packages/ui/react-ui-table/src/components/Table/Table.tsx

This PR:
- resolves DX-383
- extends `DxGrid` to support `minSize` and `maxSize` in axis meta properties.
https://github.com/user-attachments/assets/18785870-b0a1-4536-8b5d-12ecb5085ad9

feat: Improved DxGrid support for setting axis size extrema

---

packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx
packages/ui/lit-grid/src/defs.ts
packages/ui/lit-grid/src/dx-grid.pcss
packages/ui/lit-grid/src/dx-grid.ts
packages/ui/lit-grid/src/types.ts
packages/ui/lit-ui/src/dx-avatar/dx-avatar.pcss
packages/ui/lit-ui/src/dx-avatar/dx-avatar.ts
packages/ui/react-ui-table/src/components/Table/Table.tsx
packages/ui/react-ui-table/src/model/table-presentation.ts
packages/ui/react-ui/src/components/Avatars/Avatar.stories.tsx

This PR:
- resolves DX-386 and DX-387
- adds a `focusUnfurl` option to cells and axes in `dx-grid` which can disable the focus unfurl layout; maintains the utility class for this in case that is more convenient for consumers
https://github.com/user-attachments/assets/01e10986-01a3-45e7-8005-7aaff1b2d096
https://github.com/user-attachments/assets/a364ee3e-2f11-4387-9388-3c3017ee2b37

fix: Minor visual fixes to DxGrid and DxAvatar

---

.idea/fileTemplates/Typescript storybook༏ext༏.stories.tsx
packages/plugins/plugin-markdown/src/meta.ts
packages/plugins/plugin-markdown/src/types/MarkdownAction.ts
packages/plugins/plugin-meeting/src/capabilities/app-graph-builder.ts
packages/plugins/plugin-meeting/src/capabilities/call-extension.ts
packages/plugins/plugin-meeting/src/capabilities/capabilities.ts
packages/plugins/plugin-meeting/src/capabilities/react-surface.tsx
packages/plugins/plugin-meeting/src/components/MeetingContainer.tsx
packages/plugins/plugin-meeting/src/components/MeetingSettings/MeetingSettings.tsx
packages/plugins/plugin-meeting/src/components/MeetingsList.tsx
packages/plugins/plugin-meeting/src/meta.ts
packages/plugins/plugin-meeting/src/types/MeetingAction.ts
packages/plugins/plugin-transcription/src/meta.ts
packages/plugins/plugin-transcription/src/transcriber/transcriber.ts
packages/plugins/plugin-transcription/src/types/TranscriptAction.ts

Semi-automated via Claude code

fix: Remove not_meta exports and standardize all stories

---

.env.1password
packages/core/ai/src/tools/call.ts
packages/core/assistant-testing/src/blueprints/index.ts
packages/core/assistant-testing/src/blueprints/linear/index.ts
packages/core/assistant-testing/src/blueprints/linear/linear.ts
packages/core/assistant-testing/src/functions/linear/linear.test.ts
packages/core/assistant-testing/src/functions/linear/sync-issues.ts
packages/plugins/plugin-assistant/src/shims.d.ts
packages/plugins/plugin-assistant/src/stories/Chat.stories.tsx
packages/plugins/plugin-assistant/src/stories/testing/testing.tsx
packages/plugins/plugin-assistant/src/typings.d.ts
packages/plugins/plugin-assistant/src/vite-env.d.ts
packages/sdk/schema/src/common/task.ts

This PR adds support for syncing Linear projects along with issues and improves the Linear sync functionality.
- **Linear sync improvements**:
- Added project syncing when syncing Linear issues
- Projects are now created as references on tasks
- Added project ID and name to GraphQL query
- Optimized queries using Filter.foreignKeys instead of post-filtering
- **Schema updates**:
- Added optional `project` field to Task schema as a reference to Project type
- Added Project type to various test configurations
- **Plugin assistant improvements**:
- Added new story `WithLinearSync` for testing Linear sync functionality
- Created `accessTokensFromEnv` helper to safely handle environment variables for API tokens
- Added proper Vite environment type definitions
- **Code cleanup**:
- Removed …

feat: Add Linear project sync support

---

packages/plugins/plugin-assistant/src/capabilities/ai-service.ts
packages/plugins/plugin-markdown/src/components/MarkdownCard/MarkdownCard.stories.tsx
packages/sdk/app-framework/src/core/capabilities.ts
packages/sdk/schema/src/common/DataType.ts
packages/sdk/schema/src/common/index.ts
tsconfig.base.json
tsconfig.paths.json

This PR removes the `baseUrl` configuration from TypeScript configuration files:
- Removed `baseUrl: "."` from `tsconfig.paths.json`
- Removed `baseUrl: "${configDir}"` from `tsconfig.base.json`
- `tsconfig.base.json`: Removed baseUrl configuration
- `tsconfig.paths.json`: Removed baseUrl configuration
The build currently fails with unrelated TypeScript errors in the client-protocol package regarding missing '@dxos/echo-db' module. These errors appear to be pre-existing and not related to the baseUrl removal.

chore: remove baseUrl from tsconfig files

---

packages/ui/lit-grid/src/dx-grid.ts
packages/ui/react-ui-stack/src/components/Stack/Stack.tsx
packages/ui/react-ui-stack/src/components/StackContext.tsx
packages/ui/react-ui-stack/src/components/StackItem/StackItem.tsx
packages/ui/react-ui-tabs/src/Tabs.tsx
packages/ui/react-ui/src/components/Menus/ContextMenu.tsx
packages/ui/react-ui/src/components/Menus/DropdownMenu.tsx
packages/ui/react-ui/src/components/Select/Select.tsx
packages/ui/react-ui/src/components/Toolbar/Toolbar.tsx

To do:
https://github.com/user-attachments/assets/b7ad2c05-9bd7-47b9-9db6-b3ba62fdaed5
https://github.com/user-attachments/assets/1043953d-de4d-4afe-a226-ed8c997bc359

feat: Stack perpendicular arrow focus movement

---

packages/plugins/plugin-inbox/src/components/Mailbox/mailbox.css

This PR fixes an issue which caused styles intended for dx-grid cells to apply to `MessageCard`.

fix: `MessageCard` style bug

---

packages/apps/composer-app/moon.yml

ci: ensure that prebuild runs before bundle

---

packages/plugins/plugin-navtree/src/components/NavTree/NavTree.tsx
packages/plugins/plugin-navtree/src/components/Sidebar/L0Menu.tsx
packages/plugins/plugin-navtree/src/components/UserAccountAvatar/UserAccountAvatar.tsx
packages/ui/lit-ui/src/dx-avatar/dx-avatar.ts

This PR:
- fixes DX-180
- fixes a regression in `dx-avatar` which caused it to stop rendering emoji fallbacks (cc @richburdon)
https://github.com/user-attachments/assets/57402a95-3820-403d-a8b4-f1a57b5c6b98

fix: L0 tab/arrow focus order

---

packages/plugins/plugin-inbox/src/components/Mailbox/Mailbox.stories.tsx
packages/plugins/plugin-inbox/src/components/Mailbox/Mailbox.tsx
packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.stories.tsx
packages/plugins/plugin-sheet/src/components/GridSheet/GridSheet.tsx
packages/plugins/plugin-sheet/src/components/SheetContainer/SheetContainer.stories.tsx
packages/plugins/plugin-sheet/src/components/SheetContainer/SheetContainer.tsx

This PR fixes a caveat of #9940, where grids with an unbounded size needed an extrinsic full size to occupy the full height of the viewport.

fix: Sheet & Mailbox stories
